// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usersetting_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockuserSettingFinder creates a new instance of mockuserSettingFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserSettingFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserSettingFinder {
	mock := &mockuserSettingFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserSettingFinder is an autogenerated mock type for the userSettingFinder type
type mockuserSettingFinder struct {
	mock.Mock
}

type mockuserSettingFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserSettingFinder) EXPECT() *mockuserSettingFinder_Expecter {
	return &mockuserSettingFinder_Expecter{mock: &_m.Mock}
}

// FindByAppUserID provides a mock function for the type mockuserSettingFinder
func (_mock *mockuserSettingFinder) FindByAppUserID(ctx context.Context, appUserID domain.AppUserID) (*domain.UserSetting, error) {
	ret := _mock.Called(ctx, appUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAppUserID")
	}

	var r0 *domain.UserSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppUserID) (*domain.UserSetting, error)); ok {
		return returnFunc(ctx, appUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppUserID) *domain.UserSetting); ok {
		r0 = returnFunc(ctx, appUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AppUserID) error); ok {
		r1 = returnFunc(ctx, appUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserSettingFinder_FindByAppUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAppUserID'
type mockuserSettingFinder_FindByAppUserID_Call struct {
	*mock.Call
}

// FindByAppUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - appUserID domain.AppUserID
func (_e *mockuserSettingFinder_Expecter) FindByAppUserID(ctx interface{}, appUserID interface{}) *mockuserSettingFinder_FindByAppUserID_Call {
	return &mockuserSettingFinder_FindByAppUserID_Call{Call: _e.mock.On("FindByAppUserID", ctx, appUserID)}
}

func (_c *mockuserSettingFinder_FindByAppUserID_Call) Run(run func(ctx context.Context, appUserID domain.AppUserID)) *mockuserSettingFinder_FindByAppUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AppUserID
		if args[1] != nil {
			arg1 = args[1].(domain.AppUserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserSettingFinder_FindByAppUserID_Call) Return(userSetting *domain.UserSetting, err error) *mockuserSettingFinder_FindByAppUserID_Call {
	_c.Call.Return(userSetting, err)
	return _c
}

func (_c *mockuserSettingFinder_FindByAppUserID_Call) RunAndReturn(run func(ctx context.Context, appUserID domain.AppUserID) (*domain.UserSetting, error)) *mockuserSettingFinder_FindByAppUserID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockuserSettingSaver creates a new instance of mockuserSettingSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserSettingSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserSettingSaver {
	mock := &mockuserSettingSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserSettingSaver is an autogenerated mock type for the userSettingSaver type
type mockuserSettingSaver struct {
	mock.Mock
}

type mockuserSettingSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserSettingSaver) EXPECT() *mockuserSettingSaver_Expecter {
	return &mockuserSettingSaver_Expecter{mock: &_m.Mock}
}

// FindByAppUserID provides a mock function for the type mockuserSettingSaver
func (_mock *mockuserSettingSaver) FindByAppUserID(ctx context.Context, appUserID domain.AppUserID) (*domain.UserSetting, error) {
	ret := _mock.Called(ctx, appUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAppUserID")
	}

	var r0 *domain.UserSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppUserID) (*domain.UserSetting, error)); ok {
		return returnFunc(ctx, appUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppUserID) *domain.UserSetting); ok {
		r0 = returnFunc(ctx, appUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AppUserID) error); ok {
		r1 = returnFunc(ctx, appUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserSettingSaver_FindByAppUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAppUserID'
type mockuserSettingSaver_FindByAppUserID_Call struct {
	*mock.Call
}

// FindByAppUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - appUserID domain.AppUserID
func (_e *mockuserSettingSaver_Expecter) FindByAppUserID(ctx interface{}, appUserID interface{}) *mockuserSettingSaver_FindByAppUserID_Call {
	return &mockuserSettingSaver_FindByAppUserID_Call{Call: _e.mock.On("FindByAppUserID", ctx, appUserID)}
}

func (_c *mockuserSettingSaver_FindByAppUserID_Call) Run(run func(ctx context.Context, appUserID domain.AppUserID)) *mockuserSettingSaver_FindByAppUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AppUserID
		if args[1] != nil {
			arg1 = args[1].(domain.AppUserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserSettingSaver_FindByAppUserID_Call) Return(userSetting *domain.UserSetting, err error) *mockuserSettingSaver_FindByAppUserID_Call {
	_c.Call.Return(userSetting, err)
	return _c
}

func (_c *mockuserSettingSaver_FindByAppUserID_Call) RunAndReturn(run func(ctx context.Context, appUserID domain.AppUserID) (*domain.UserSetting, error)) *mockuserSettingSaver_FindByAppUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockuserSettingSaver
func (_mock *mockuserSettingSaver) Save(ctx context.Context, setting *domain.UserSetting) error {
	ret := _mock.Called(ctx, setting)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserSetting) error); ok {
		r0 = returnFunc(ctx, setting)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockuserSettingSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockuserSettingSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - setting *domain.UserSetting
func (_e *mockuserSettingSaver_Expecter) Save(ctx interface{}, setting interface{}) *mockuserSettingSaver_Save_Call {
	return &mockuserSettingSaver_Save_Call{Call: _e.mock.On("Save", ctx, setting)}
}

func (_c *mockuserSettingSaver_Save_Call) Run(run func(ctx context.Context, setting *domain.UserSetting)) *mockuserSettingSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UserSetting
		if args[1] != nil {
			arg1 = args[1].(*domain.UserSetting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserSettingSaver_Save_Call) Return(err error) *mockuserSettingSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockuserSettingSaver_Save_Call) RunAndReturn(run func(ctx context.Context, setting *domain.UserSetting) error) *mockuserSettingSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}
