// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/service/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// ExtendSessionToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) ExtendSessionToken(ctx context.Context, input *auth.ExtendSessionTokenInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ExtendSessionToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ExtendSessionTokenInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_ExtendSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendSessionToken'
type MockAuthUsecase_ExtendSessionToken_Call struct {
	*mock.Call
}

// ExtendSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.ExtendSessionTokenInput
func (_e *MockAuthUsecase_Expecter) ExtendSessionToken(ctx interface{}, input interface{}) *MockAuthUsecase_ExtendSessionToken_Call {
	return &MockAuthUsecase_ExtendSessionToken_Call{Call: _e.mock.On("ExtendSessionToken", ctx, input)}
}

func (_c *MockAuthUsecase_ExtendSessionToken_Call) Run(run func(ctx context.Context, input *auth.ExtendSessionTokenInput)) *MockAuthUsecase_ExtendSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.ExtendSessionTokenInput
		if args[1] != nil {
			arg1 = args[1].(*auth.ExtendSessionTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_ExtendSessionToken_Call) Return(err error) *MockAuthUsecase_ExtendSessionToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_ExtendSessionToken_Call) RunAndReturn(run func(ctx context.Context, input *auth.ExtendSessionTokenInput) error) *MockAuthUsecase_ExtendSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) ValidateAccessToken(ctx context.Context, input *auth.ValidateAccessTokenInput) (*auth.ValidateAccessTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *auth.ValidateAccessTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ValidateAccessTokenInput) (*auth.ValidateAccessTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ValidateAccessTokenInput) *auth.ValidateAccessTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.ValidateAccessTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.ValidateAccessTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockAuthUsecase_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.ValidateAccessTokenInput
func (_e *MockAuthUsecase_Expecter) ValidateAccessToken(ctx interface{}, input interface{}) *MockAuthUsecase_ValidateAccessToken_Call {
	return &MockAuthUsecase_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, input)}
}

func (_c *MockAuthUsecase_ValidateAccessToken_Call) Run(run func(ctx context.Context, input *auth.ValidateAccessTokenInput)) *MockAuthUsecase_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.ValidateAccessTokenInput
		if args[1] != nil {
			arg1 = args[1].(*auth.ValidateAccessTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_ValidateAccessToken_Call) Return(validateAccessTokenOutput *auth.ValidateAccessTokenOutput, err error) *MockAuthUsecase_ValidateAccessToken_Call {
	_c.Call.Return(validateAccessTokenOutput, err)
	return _c
}

func (_c *MockAuthUsecase_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, input *auth.ValidateAccessTokenInput) (*auth.ValidateAccessTokenOutput, error)) *MockAuthUsecase_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSessionToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) ValidateSessionToken(ctx context.Context, input *auth.ValidateSessionTokenInput) (*auth.ValidateSessionTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSessionToken")
	}

	var r0 *auth.ValidateSessionTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ValidateSessionTokenInput) (*auth.ValidateSessionTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ValidateSessionTokenInput) *auth.ValidateSessionTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.ValidateSessionTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.ValidateSessionTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_ValidateSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSessionToken'
type MockAuthUsecase_ValidateSessionToken_Call struct {
	*mock.Call
}

// ValidateSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.ValidateSessionTokenInput
func (_e *MockAuthUsecase_Expecter) ValidateSessionToken(ctx interface{}, input interface{}) *MockAuthUsecase_ValidateSessionToken_Call {
	return &MockAuthUsecase_ValidateSessionToken_Call{Call: _e.mock.On("ValidateSessionToken", ctx, input)}
}

func (_c *MockAuthUsecase_ValidateSessionToken_Call) Run(run func(ctx context.Context, input *auth.ValidateSessionTokenInput)) *MockAuthUsecase_ValidateSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.ValidateSessionTokenInput
		if args[1] != nil {
			arg1 = args[1].(*auth.ValidateSessionTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_ValidateSessionToken_Call) Return(validateSessionTokenOutput *auth.ValidateSessionTokenOutput, err error) *MockAuthUsecase_ValidateSessionToken_Call {
	_c.Call.Return(validateSessionTokenOutput, err)
	return _c
}

func (_c *MockAuthUsecase_ValidateSessionToken_Call) RunAndReturn(run func(ctx context.Context, input *auth.ValidateSessionTokenInput) (*auth.ValidateSessionTokenOutput, error)) *MockAuthUsecase_ValidateSessionToken_Call {
	_c.Call.Return(run)
	return _c
}
