// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockappUserFinder creates a new instance of mockappUserFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockappUserFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockappUserFinder {
	mock := &mockappUserFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockappUserFinder is an autogenerated mock type for the appUserFinder type
type mockappUserFinder struct {
	mock.Mock
}

type mockappUserFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockappUserFinder) EXPECT() *mockappUserFinder_Expecter {
	return &mockappUserFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockappUserFinder
func (_mock *mockappUserFinder) FindByID(ctx context.Context, id int) (*domain.AppUser, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.AppUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.AppUser, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.AppUser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockappUserFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockappUserFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *mockappUserFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockappUserFinder_FindByID_Call {
	return &mockappUserFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockappUserFinder_FindByID_Call) Run(run func(ctx context.Context, id int)) *mockappUserFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockappUserFinder_FindByID_Call) Return(appUser *domain.AppUser, err error) *mockappUserFinder_FindByID_Call {
	_c.Call.Return(appUser, err)
	return _c
}

func (_c *mockappUserFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*domain.AppUser, error)) *mockappUserFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockappUserSaver creates a new instance of mockappUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockappUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockappUserSaver {
	mock := &mockappUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockappUserSaver is an autogenerated mock type for the appUserSaver type
type mockappUserSaver struct {
	mock.Mock
}

type mockappUserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockappUserSaver) EXPECT() *mockappUserSaver_Expecter {
	return &mockappUserSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type mockappUserSaver
func (_mock *mockappUserSaver) Save(ctx context.Context, user *domain.AppUser) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AppUser) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockappUserSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockappUserSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.AppUser
func (_e *mockappUserSaver_Expecter) Save(ctx interface{}, user interface{}) *mockappUserSaver_Save_Call {
	return &mockappUserSaver_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *mockappUserSaver_Save_Call) Run(run func(ctx context.Context, user *domain.AppUser)) *mockappUserSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AppUser
		if args[1] != nil {
			arg1 = args[1].(*domain.AppUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockappUserSaver_Save_Call) Return(err error) *mockappUserSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockappUserSaver_Save_Call) RunAndReturn(run func(ctx context.Context, user *domain.AppUser) error) *mockappUserSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockappUserCreator creates a new instance of mockappUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockappUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockappUserCreator {
	mock := &mockappUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockappUserCreator is an autogenerated mock type for the appUserCreator type
type mockappUserCreator struct {
	mock.Mock
}

type mockappUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockappUserCreator) EXPECT() *mockappUserCreator_Expecter {
	return &mockappUserCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockappUserCreator
func (_mock *mockappUserCreator) Create(ctx context.Context, organizationID int, loginID string, hashedPassword string) (int, error) {
	ret := _mock.Called(ctx, organizationID, loginID, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) (int, error)); ok {
		return returnFunc(ctx, organizationID, loginID, hashedPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) int); ok {
		r0 = returnFunc(ctx, organizationID, loginID, hashedPassword)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = returnFunc(ctx, organizationID, loginID, hashedPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockappUserCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockappUserCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int
//   - loginID string
//   - hashedPassword string
func (_e *mockappUserCreator_Expecter) Create(ctx interface{}, organizationID interface{}, loginID interface{}, hashedPassword interface{}) *mockappUserCreator_Create_Call {
	return &mockappUserCreator_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, loginID, hashedPassword)}
}

func (_c *mockappUserCreator_Create_Call) Run(run func(ctx context.Context, organizationID int, loginID string, hashedPassword string)) *mockappUserCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockappUserCreator_Create_Call) Return(n int, err error) *mockappUserCreator_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockappUserCreator_Create_Call) RunAndReturn(run func(ctx context.Context, organizationID int, loginID string, hashedPassword string) (int, error)) *mockappUserCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockorganizationFinder creates a new instance of mockorganizationFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockorganizationFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockorganizationFinder {
	mock := &mockorganizationFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockorganizationFinder is an autogenerated mock type for the organizationFinder type
type mockorganizationFinder struct {
	mock.Mock
}

type mockorganizationFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockorganizationFinder) EXPECT() *mockorganizationFinder_Expecter {
	return &mockorganizationFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockorganizationFinder
func (_mock *mockorganizationFinder) FindByID(ctx context.Context, id int) (*domain.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockorganizationFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockorganizationFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *mockorganizationFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockorganizationFinder_FindByID_Call {
	return &mockorganizationFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockorganizationFinder_FindByID_Call) Run(run func(ctx context.Context, id int)) *mockorganizationFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockorganizationFinder_FindByID_Call) Return(organization *domain.Organization, err error) *mockorganizationFinder_FindByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *mockorganizationFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*domain.Organization, error)) *mockorganizationFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockactiveUserListRepository creates a new instance of mockactiveUserListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveUserListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveUserListRepository {
	mock := &mockactiveUserListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveUserListRepository is an autogenerated mock type for the activeUserListRepository type
type mockactiveUserListRepository struct {
	mock.Mock
}

type mockactiveUserListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockactiveUserListRepository) EXPECT() *mockactiveUserListRepository_Expecter {
	return &mockactiveUserListRepository_Expecter{mock: &_m.Mock}
}

// FindByOrganizationID provides a mock function for the type mockactiveUserListRepository
func (_mock *mockactiveUserListRepository) FindByOrganizationID(ctx context.Context, organizationID int) (*domain.ActiveUserList, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrganizationID")
	}

	var r0 *domain.ActiveUserList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.ActiveUserList, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.ActiveUserList); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActiveUserList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockactiveUserListRepository_FindByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrganizationID'
type mockactiveUserListRepository_FindByOrganizationID_Call struct {
	*mock.Call
}

// FindByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int
func (_e *mockactiveUserListRepository_Expecter) FindByOrganizationID(ctx interface{}, organizationID interface{}) *mockactiveUserListRepository_FindByOrganizationID_Call {
	return &mockactiveUserListRepository_FindByOrganizationID_Call{Call: _e.mock.On("FindByOrganizationID", ctx, organizationID)}
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) Run(run func(ctx context.Context, organizationID int)) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) Return(activeUserList *domain.ActiveUserList, err error) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Return(activeUserList, err)
	return _c
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) RunAndReturn(run func(ctx context.Context, organizationID int) (*domain.ActiveUserList, error)) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockactiveUserListRepository
func (_mock *mockactiveUserListRepository) Save(ctx context.Context, list *domain.ActiveUserList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ActiveUserList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockactiveUserListRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockactiveUserListRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *domain.ActiveUserList
func (_e *mockactiveUserListRepository_Expecter) Save(ctx interface{}, list interface{}) *mockactiveUserListRepository_Save_Call {
	return &mockactiveUserListRepository_Save_Call{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *mockactiveUserListRepository_Save_Call) Run(run func(ctx context.Context, list *domain.ActiveUserList)) *mockactiveUserListRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ActiveUserList
		if args[1] != nil {
			arg1 = args[1].(*domain.ActiveUserList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveUserListRepository_Save_Call) Return(err error) *mockactiveUserListRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockactiveUserListRepository_Save_Call) RunAndReturn(run func(ctx context.Context, list *domain.ActiveUserList) error) *mockactiveUserListRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockpasswordHasher creates a new instance of mockpasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockpasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockpasswordHasher {
	mock := &mockpasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockpasswordHasher is an autogenerated mock type for the passwordHasher type
type mockpasswordHasher struct {
	mock.Mock
}

type mockpasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockpasswordHasher) EXPECT() *mockpasswordHasher_Expecter {
	return &mockpasswordHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type mockpasswordHasher
func (_mock *mockpasswordHasher) Compare(hashedPassword string, password string) error {
	ret := _mock.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockpasswordHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type mockpasswordHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashedPassword string
//   - password string
func (_e *mockpasswordHasher_Expecter) Compare(hashedPassword interface{}, password interface{}) *mockpasswordHasher_Compare_Call {
	return &mockpasswordHasher_Compare_Call{Call: _e.mock.On("Compare", hashedPassword, password)}
}

func (_c *mockpasswordHasher_Compare_Call) Run(run func(hashedPassword string, password string)) *mockpasswordHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockpasswordHasher_Compare_Call) Return(err error) *mockpasswordHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockpasswordHasher_Compare_Call) RunAndReturn(run func(hashedPassword string, password string) error) *mockpasswordHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type mockpasswordHasher
func (_mock *mockpasswordHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockpasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type mockpasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *mockpasswordHasher_Expecter) Hash(password interface{}) *mockpasswordHasher_Hash_Call {
	return &mockpasswordHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *mockpasswordHasher_Hash_Call) Run(run func(password string)) *mockpasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockpasswordHasher_Hash_Call) Return(s string, err error) *mockpasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockpasswordHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *mockpasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
