---
services:
  local-postgres:
    extends:
      service: local-postgres-base
      file: ./compose.common-postgres.yml
    networks:
      - cocotola

  local-firestore:
    extends:
      service: local-firestore-base
      file: ./compose.common-firestore.yml
    ports:
      - 127.0.0.1:${FIRESTORE_PORT:-8681}:8681
    networks:
      - cocotola

  local-jaeger:
    extends:
      service: local-jaeger-base
      file: ./compose.common-jaeger.yml
    ports:
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:14268:14268
      - 127.0.0.1:16686:16686
      - 127.0.0.1:13133:13133
    networks:
      - cocotola

networks:
  cocotola:
    driver: bridge
