---
services:
  local-mysql:
    extends:
      service: local-mysql-base
      file: ./compose.common-mysql.yml
    networks:
      - cocotola
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - NET_RAW
      - SETFCAP
      - SYS_CHROOT

  local-lgtm:
    extends:
      service: local-lgtm-base
      file: ./compose.common-lgtm.yml
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:4040:4040
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:9090:9090
    networks:
      - cocotola
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - NET_RAW
      - SETFCAP
      - SYS_CHROOT

networks:
  cocotola:
    driver: bridge
