// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package space_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain/rbac"
	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain/space"
	mock "github.com/stretchr/testify/mock"
)

// newMockspaceSaver creates a new instance of mockspaceSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspaceSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspaceSaver {
	mock := &mockspaceSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockspaceSaver is an autogenerated mock type for the spaceSaver type
type mockspaceSaver struct {
	mock.Mock
}

type mockspaceSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspaceSaver) EXPECT() *mockspaceSaver_Expecter {
	return &mockspaceSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type mockspaceSaver
func (_mock *mockspaceSaver) Save(ctx context.Context, space1 *space.Space) error {
	ret := _mock.Called(ctx, space1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *space.Space) error); ok {
		r0 = returnFunc(ctx, space1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockspaceSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockspaceSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - space1 *space.Space
func (_e *mockspaceSaver_Expecter) Save(ctx interface{}, space1 interface{}) *mockspaceSaver_Save_Call {
	return &mockspaceSaver_Save_Call{Call: _e.mock.On("Save", ctx, space1)}
}

func (_c *mockspaceSaver_Save_Call) Run(run func(ctx context.Context, space1 *space.Space)) *mockspaceSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *space.Space
		if args[1] != nil {
			arg1 = args[1].(*space.Space)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockspaceSaver_Save_Call) Return(err error) *mockspaceSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockspaceSaver_Save_Call) RunAndReturn(run func(ctx context.Context, space1 *space.Space) error) *mockspaceSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockorganizationFinderByName creates a new instance of mockorganizationFinderByName. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockorganizationFinderByName(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockorganizationFinderByName {
	mock := &mockorganizationFinderByName{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockorganizationFinderByName is an autogenerated mock type for the organizationFinderByName type
type mockorganizationFinderByName struct {
	mock.Mock
}

type mockorganizationFinderByName_Expecter struct {
	mock *mock.Mock
}

func (_m *mockorganizationFinderByName) EXPECT() *mockorganizationFinderByName_Expecter {
	return &mockorganizationFinderByName_Expecter{mock: &_m.Mock}
}

// FindByName provides a mock function for the type mockorganizationFinderByName
func (_mock *mockorganizationFinderByName) FindByName(ctx context.Context, name string) (*domain.Organization, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Organization, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Organization); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockorganizationFinderByName_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type mockorganizationFinderByName_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *mockorganizationFinderByName_Expecter) FindByName(ctx interface{}, name interface{}) *mockorganizationFinderByName_FindByName_Call {
	return &mockorganizationFinderByName_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *mockorganizationFinderByName_FindByName_Call) Run(run func(ctx context.Context, name string)) *mockorganizationFinderByName_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockorganizationFinderByName_FindByName_Call) Return(organization *domain.Organization, err error) *mockorganizationFinderByName_FindByName_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *mockorganizationFinderByName_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Organization, error)) *mockorganizationFinderByName_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// newMockeventPublisher creates a new instance of mockeventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockeventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockeventPublisher {
	mock := &mockeventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockeventPublisher is an autogenerated mock type for the eventPublisher type
type mockeventPublisher struct {
	mock.Mock
}

type mockeventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockeventPublisher) EXPECT() *mockeventPublisher_Expecter {
	return &mockeventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type mockeventPublisher
func (_mock *mockeventPublisher) Publish(event domain.Event) {
	_mock.Called(event)
	return
}

// mockeventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type mockeventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event domain.Event
func (_e *mockeventPublisher_Expecter) Publish(event interface{}) *mockeventPublisher_Publish_Call {
	return &mockeventPublisher_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *mockeventPublisher_Publish_Call) Run(run func(event domain.Event)) *mockeventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Event
		if args[0] != nil {
			arg0 = args[0].(domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockeventPublisher_Publish_Call) Return() *mockeventPublisher_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockeventPublisher_Publish_Call) RunAndReturn(run func(event domain.Event)) *mockeventPublisher_Publish_Call {
	_c.Run(run)
	return _c
}

// newMockauthorizationChecker creates a new instance of mockauthorizationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauthorizationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauthorizationChecker {
	mock := &mockauthorizationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauthorizationChecker is an autogenerated mock type for the authorizationChecker type
type mockauthorizationChecker struct {
	mock.Mock
}

type mockauthorizationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauthorizationChecker) EXPECT() *mockauthorizationChecker_Expecter {
	return &mockauthorizationChecker_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type mockauthorizationChecker
func (_mock *mockauthorizationChecker) IsAllowed(ctx context.Context, organizationID domain.OrganizationID, operatorID domain.AppUserID, action rbac.Action, resource rbac.Resource) (bool, error) {
	ret := _mock.Called(ctx, organizationID, operatorID, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, domain.AppUserID, rbac.Action, rbac.Resource) (bool, error)); ok {
		return returnFunc(ctx, organizationID, operatorID, action, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, domain.AppUserID, rbac.Action, rbac.Resource) bool); ok {
		r0 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID, domain.AppUserID, rbac.Action, rbac.Resource) error); ok {
		r1 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauthorizationChecker_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type mockauthorizationChecker_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
//   - operatorID domain.AppUserID
//   - action rbac.Action
//   - resource rbac.Resource
func (_e *mockauthorizationChecker_Expecter) IsAllowed(ctx interface{}, organizationID interface{}, operatorID interface{}, action interface{}, resource interface{}) *mockauthorizationChecker_IsAllowed_Call {
	return &mockauthorizationChecker_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, organizationID, operatorID, action, resource)}
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID, operatorID domain.AppUserID, action rbac.Action, resource rbac.Resource)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		var arg2 domain.AppUserID
		if args[2] != nil {
			arg2 = args[2].(domain.AppUserID)
		}
		var arg3 rbac.Action
		if args[3] != nil {
			arg3 = args[3].(rbac.Action)
		}
		var arg4 rbac.Resource
		if args[4] != nil {
			arg4 = args[4].(rbac.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Return(b bool, err error) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID, operatorID domain.AppUserID, action rbac.Action, resource rbac.Resource) (bool, error)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// newMockspaceByIDFinder creates a new instance of mockspaceByIDFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspaceByIDFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspaceByIDFinder {
	mock := &mockspaceByIDFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockspaceByIDFinder is an autogenerated mock type for the spaceByIDFinder type
type mockspaceByIDFinder struct {
	mock.Mock
}

type mockspaceByIDFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspaceByIDFinder) EXPECT() *mockspaceByIDFinder_Expecter {
	return &mockspaceByIDFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockspaceByIDFinder
func (_mock *mockspaceByIDFinder) FindByID(ctx context.Context, id domain.SpaceID) (*space.Space, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *space.Space
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SpaceID) (*space.Space, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SpaceID) *space.Space); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*space.Space)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SpaceID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockspaceByIDFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockspaceByIDFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SpaceID
func (_e *mockspaceByIDFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockspaceByIDFinder_FindByID_Call {
	return &mockspaceByIDFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockspaceByIDFinder_FindByID_Call) Run(run func(ctx context.Context, id domain.SpaceID)) *mockspaceByIDFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SpaceID
		if args[1] != nil {
			arg1 = args[1].(domain.SpaceID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockspaceByIDFinder_FindByID_Call) Return(space1 *space.Space, err error) *mockspaceByIDFinder_FindByID_Call {
	_c.Call.Return(space1, err)
	return _c
}

func (_c *mockspaceByIDFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id domain.SpaceID) (*space.Space, error)) *mockspaceByIDFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockspaceFinder creates a new instance of mockspaceFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspaceFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspaceFinder {
	mock := &mockspaceFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockspaceFinder is an autogenerated mock type for the spaceFinder type
type mockspaceFinder struct {
	mock.Mock
}

type mockspaceFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspaceFinder) EXPECT() *mockspaceFinder_Expecter {
	return &mockspaceFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockspaceFinder
func (_mock *mockspaceFinder) FindByID(ctx context.Context, id domain.SpaceID) (*space.Space, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *space.Space
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SpaceID) (*space.Space, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SpaceID) *space.Space); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*space.Space)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SpaceID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockspaceFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockspaceFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SpaceID
func (_e *mockspaceFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockspaceFinder_FindByID_Call {
	return &mockspaceFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockspaceFinder_FindByID_Call) Run(run func(ctx context.Context, id domain.SpaceID)) *mockspaceFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SpaceID
		if args[1] != nil {
			arg1 = args[1].(domain.SpaceID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockspaceFinder_FindByID_Call) Return(space1 *space.Space, err error) *mockspaceFinder_FindByID_Call {
	_c.Call.Return(space1, err)
	return _c
}

func (_c *mockspaceFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id domain.SpaceID) (*space.Space, error)) *mockspaceFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrganizationID provides a mock function for the type mockspaceFinder
func (_mock *mockspaceFinder) FindByOrganizationID(ctx context.Context, organizationID domain.OrganizationID) ([]space.Space, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrganizationID")
	}

	var r0 []space.Space
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) ([]space.Space, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) []space.Space); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]space.Space)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockspaceFinder_FindByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrganizationID'
type mockspaceFinder_FindByOrganizationID_Call struct {
	*mock.Call
}

// FindByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
func (_e *mockspaceFinder_Expecter) FindByOrganizationID(ctx interface{}, organizationID interface{}) *mockspaceFinder_FindByOrganizationID_Call {
	return &mockspaceFinder_FindByOrganizationID_Call{Call: _e.mock.On("FindByOrganizationID", ctx, organizationID)}
}

func (_c *mockspaceFinder_FindByOrganizationID_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID)) *mockspaceFinder_FindByOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockspaceFinder_FindByOrganizationID_Call) Return(spaces []space.Space, err error) *mockspaceFinder_FindByOrganizationID_Call {
	_c.Call.Return(spaces, err)
	return _c
}

func (_c *mockspaceFinder_FindByOrganizationID_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID) ([]space.Space, error)) *mockspaceFinder_FindByOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}
