load("@rules_go//go:def.bzl", "go_library")
load("//bazel:go_test.bzl", "smart_go_test")

go_library(
    name = "workbook",
    srcs = [
        "create_workbook_handler.go",
        "delete_workbook_handler.go",
        "get_workbook_handler.go",
        "list_workbooks_handler.go",
        "update_workbook_handler.go",
        "workbook.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.26/cocotola-question/controller/handler/workbook",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-lib/logging",
        "//cocotola-question/api",
        "//cocotola-question/controller",
        "//cocotola-question/domain",
        "//cocotola-question/service/workbook",
        "@com_github_gin_gonic_gin//:gin",
    ],
)

smart_go_test(
    name = "workbook_test",
    srcs = [
        "create_workbook_handler_s_test.go",
        "helper_test.go",
        "mocks_test.go",
    ],
    deps = [
        ":workbook",
        "//cocotola-lib/controller",
        "//cocotola-lib/controller/handler",
        "//cocotola-question/controller",
        "//cocotola-question/domain",
        "//cocotola-question/service/workbook",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_ohler55_ojg//jp",
        "@com_github_ohler55_ojg//oj",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
    ],
)
