// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workbook_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/service/workbook"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateWorkbookUsecase creates a new instance of MockCreateWorkbookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateWorkbookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateWorkbookUsecase {
	mock := &MockCreateWorkbookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateWorkbookUsecase is an autogenerated mock type for the CreateWorkbookUsecase type
type MockCreateWorkbookUsecase struct {
	mock.Mock
}

type MockCreateWorkbookUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateWorkbookUsecase) EXPECT() *MockCreateWorkbookUsecase_Expecter {
	return &MockCreateWorkbookUsecase_Expecter{mock: &_m.Mock}
}

// CreateWorkbook provides a mock function for the type MockCreateWorkbookUsecase
func (_mock *MockCreateWorkbookUsecase) CreateWorkbook(ctx context.Context, input *workbook.CreateWorkbookInput) (*workbook.CreateWorkbookOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkbook")
	}

	var r0 *workbook.CreateWorkbookOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.CreateWorkbookInput) (*workbook.CreateWorkbookOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.CreateWorkbookInput) *workbook.CreateWorkbookOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.CreateWorkbookOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *workbook.CreateWorkbookInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateWorkbookUsecase_CreateWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkbook'
type MockCreateWorkbookUsecase_CreateWorkbook_Call struct {
	*mock.Call
}

// CreateWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - input *workbook.CreateWorkbookInput
func (_e *MockCreateWorkbookUsecase_Expecter) CreateWorkbook(ctx interface{}, input interface{}) *MockCreateWorkbookUsecase_CreateWorkbook_Call {
	return &MockCreateWorkbookUsecase_CreateWorkbook_Call{Call: _e.mock.On("CreateWorkbook", ctx, input)}
}

func (_c *MockCreateWorkbookUsecase_CreateWorkbook_Call) Run(run func(ctx context.Context, input *workbook.CreateWorkbookInput)) *MockCreateWorkbookUsecase_CreateWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workbook.CreateWorkbookInput
		if args[1] != nil {
			arg1 = args[1].(*workbook.CreateWorkbookInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateWorkbookUsecase_CreateWorkbook_Call) Return(createWorkbookOutput *workbook.CreateWorkbookOutput, err error) *MockCreateWorkbookUsecase_CreateWorkbook_Call {
	_c.Call.Return(createWorkbookOutput, err)
	return _c
}

func (_c *MockCreateWorkbookUsecase_CreateWorkbook_Call) RunAndReturn(run func(ctx context.Context, input *workbook.CreateWorkbookInput) (*workbook.CreateWorkbookOutput, error)) *MockCreateWorkbookUsecase_CreateWorkbook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteWorkbookUsecase creates a new instance of MockDeleteWorkbookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteWorkbookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteWorkbookUsecase {
	mock := &MockDeleteWorkbookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteWorkbookUsecase is an autogenerated mock type for the DeleteWorkbookUsecase type
type MockDeleteWorkbookUsecase struct {
	mock.Mock
}

type MockDeleteWorkbookUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteWorkbookUsecase) EXPECT() *MockDeleteWorkbookUsecase_Expecter {
	return &MockDeleteWorkbookUsecase_Expecter{mock: &_m.Mock}
}

// DeleteWorkbook provides a mock function for the type MockDeleteWorkbookUsecase
func (_mock *MockDeleteWorkbookUsecase) DeleteWorkbook(ctx context.Context, input *workbook.DeleteWorkbookInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkbook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.DeleteWorkbookInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleteWorkbookUsecase_DeleteWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkbook'
type MockDeleteWorkbookUsecase_DeleteWorkbook_Call struct {
	*mock.Call
}

// DeleteWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - input *workbook.DeleteWorkbookInput
func (_e *MockDeleteWorkbookUsecase_Expecter) DeleteWorkbook(ctx interface{}, input interface{}) *MockDeleteWorkbookUsecase_DeleteWorkbook_Call {
	return &MockDeleteWorkbookUsecase_DeleteWorkbook_Call{Call: _e.mock.On("DeleteWorkbook", ctx, input)}
}

func (_c *MockDeleteWorkbookUsecase_DeleteWorkbook_Call) Run(run func(ctx context.Context, input *workbook.DeleteWorkbookInput)) *MockDeleteWorkbookUsecase_DeleteWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workbook.DeleteWorkbookInput
		if args[1] != nil {
			arg1 = args[1].(*workbook.DeleteWorkbookInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleteWorkbookUsecase_DeleteWorkbook_Call) Return(err error) *MockDeleteWorkbookUsecase_DeleteWorkbook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleteWorkbookUsecase_DeleteWorkbook_Call) RunAndReturn(run func(ctx context.Context, input *workbook.DeleteWorkbookInput) error) *MockDeleteWorkbookUsecase_DeleteWorkbook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetWorkbookUsecase creates a new instance of MockGetWorkbookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetWorkbookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetWorkbookUsecase {
	mock := &MockGetWorkbookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetWorkbookUsecase is an autogenerated mock type for the GetWorkbookUsecase type
type MockGetWorkbookUsecase struct {
	mock.Mock
}

type MockGetWorkbookUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetWorkbookUsecase) EXPECT() *MockGetWorkbookUsecase_Expecter {
	return &MockGetWorkbookUsecase_Expecter{mock: &_m.Mock}
}

// GetWorkbook provides a mock function for the type MockGetWorkbookUsecase
func (_mock *MockGetWorkbookUsecase) GetWorkbook(ctx context.Context, input *workbook.GetWorkbookInput) (*workbook.GetWorkbookOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkbook")
	}

	var r0 *workbook.GetWorkbookOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.GetWorkbookInput) (*workbook.GetWorkbookOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.GetWorkbookInput) *workbook.GetWorkbookOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.GetWorkbookOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *workbook.GetWorkbookInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetWorkbookUsecase_GetWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkbook'
type MockGetWorkbookUsecase_GetWorkbook_Call struct {
	*mock.Call
}

// GetWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - input *workbook.GetWorkbookInput
func (_e *MockGetWorkbookUsecase_Expecter) GetWorkbook(ctx interface{}, input interface{}) *MockGetWorkbookUsecase_GetWorkbook_Call {
	return &MockGetWorkbookUsecase_GetWorkbook_Call{Call: _e.mock.On("GetWorkbook", ctx, input)}
}

func (_c *MockGetWorkbookUsecase_GetWorkbook_Call) Run(run func(ctx context.Context, input *workbook.GetWorkbookInput)) *MockGetWorkbookUsecase_GetWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workbook.GetWorkbookInput
		if args[1] != nil {
			arg1 = args[1].(*workbook.GetWorkbookInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetWorkbookUsecase_GetWorkbook_Call) Return(getWorkbookOutput *workbook.GetWorkbookOutput, err error) *MockGetWorkbookUsecase_GetWorkbook_Call {
	_c.Call.Return(getWorkbookOutput, err)
	return _c
}

func (_c *MockGetWorkbookUsecase_GetWorkbook_Call) RunAndReturn(run func(ctx context.Context, input *workbook.GetWorkbookInput) (*workbook.GetWorkbookOutput, error)) *MockGetWorkbookUsecase_GetWorkbook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListWorkbooksUsecase creates a new instance of MockListWorkbooksUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListWorkbooksUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListWorkbooksUsecase {
	mock := &MockListWorkbooksUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListWorkbooksUsecase is an autogenerated mock type for the ListWorkbooksUsecase type
type MockListWorkbooksUsecase struct {
	mock.Mock
}

type MockListWorkbooksUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListWorkbooksUsecase) EXPECT() *MockListWorkbooksUsecase_Expecter {
	return &MockListWorkbooksUsecase_Expecter{mock: &_m.Mock}
}

// ListWorkbooks provides a mock function for the type MockListWorkbooksUsecase
func (_mock *MockListWorkbooksUsecase) ListWorkbooks(ctx context.Context, input *workbook.ListWorkbooksInput) (*workbook.ListWorkbooksOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkbooks")
	}

	var r0 *workbook.ListWorkbooksOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.ListWorkbooksInput) (*workbook.ListWorkbooksOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.ListWorkbooksInput) *workbook.ListWorkbooksOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.ListWorkbooksOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *workbook.ListWorkbooksInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListWorkbooksUsecase_ListWorkbooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkbooks'
type MockListWorkbooksUsecase_ListWorkbooks_Call struct {
	*mock.Call
}

// ListWorkbooks is a helper method to define mock.On call
//   - ctx context.Context
//   - input *workbook.ListWorkbooksInput
func (_e *MockListWorkbooksUsecase_Expecter) ListWorkbooks(ctx interface{}, input interface{}) *MockListWorkbooksUsecase_ListWorkbooks_Call {
	return &MockListWorkbooksUsecase_ListWorkbooks_Call{Call: _e.mock.On("ListWorkbooks", ctx, input)}
}

func (_c *MockListWorkbooksUsecase_ListWorkbooks_Call) Run(run func(ctx context.Context, input *workbook.ListWorkbooksInput)) *MockListWorkbooksUsecase_ListWorkbooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workbook.ListWorkbooksInput
		if args[1] != nil {
			arg1 = args[1].(*workbook.ListWorkbooksInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListWorkbooksUsecase_ListWorkbooks_Call) Return(listWorkbooksOutput *workbook.ListWorkbooksOutput, err error) *MockListWorkbooksUsecase_ListWorkbooks_Call {
	_c.Call.Return(listWorkbooksOutput, err)
	return _c
}

func (_c *MockListWorkbooksUsecase_ListWorkbooks_Call) RunAndReturn(run func(ctx context.Context, input *workbook.ListWorkbooksInput) (*workbook.ListWorkbooksOutput, error)) *MockListWorkbooksUsecase_ListWorkbooks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateWorkbookUsecase creates a new instance of MockUpdateWorkbookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateWorkbookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateWorkbookUsecase {
	mock := &MockUpdateWorkbookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateWorkbookUsecase is an autogenerated mock type for the UpdateWorkbookUsecase type
type MockUpdateWorkbookUsecase struct {
	mock.Mock
}

type MockUpdateWorkbookUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateWorkbookUsecase) EXPECT() *MockUpdateWorkbookUsecase_Expecter {
	return &MockUpdateWorkbookUsecase_Expecter{mock: &_m.Mock}
}

// UpdateWorkbook provides a mock function for the type MockUpdateWorkbookUsecase
func (_mock *MockUpdateWorkbookUsecase) UpdateWorkbook(ctx context.Context, input *workbook.UpdateWorkbookInput) (*workbook.UpdateWorkbookOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkbook")
	}

	var r0 *workbook.UpdateWorkbookOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.UpdateWorkbookInput) (*workbook.UpdateWorkbookOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.UpdateWorkbookInput) *workbook.UpdateWorkbookOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.UpdateWorkbookOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *workbook.UpdateWorkbookInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateWorkbookUsecase_UpdateWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkbook'
type MockUpdateWorkbookUsecase_UpdateWorkbook_Call struct {
	*mock.Call
}

// UpdateWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - input *workbook.UpdateWorkbookInput
func (_e *MockUpdateWorkbookUsecase_Expecter) UpdateWorkbook(ctx interface{}, input interface{}) *MockUpdateWorkbookUsecase_UpdateWorkbook_Call {
	return &MockUpdateWorkbookUsecase_UpdateWorkbook_Call{Call: _e.mock.On("UpdateWorkbook", ctx, input)}
}

func (_c *MockUpdateWorkbookUsecase_UpdateWorkbook_Call) Run(run func(ctx context.Context, input *workbook.UpdateWorkbookInput)) *MockUpdateWorkbookUsecase_UpdateWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workbook.UpdateWorkbookInput
		if args[1] != nil {
			arg1 = args[1].(*workbook.UpdateWorkbookInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateWorkbookUsecase_UpdateWorkbook_Call) Return(updateWorkbookOutput *workbook.UpdateWorkbookOutput, err error) *MockUpdateWorkbookUsecase_UpdateWorkbook_Call {
	_c.Call.Return(updateWorkbookOutput, err)
	return _c
}

func (_c *MockUpdateWorkbookUsecase_UpdateWorkbook_Call) RunAndReturn(run func(ctx context.Context, input *workbook.UpdateWorkbookInput) (*workbook.UpdateWorkbookOutput, error)) *MockUpdateWorkbookUsecase_UpdateWorkbook_Call {
	_c.Call.Return(run)
	return _c
}
