// Package api contains the OpenAPI-generated request and response types for the
// cocotola-question HTTP API. Code in this package is auto-generated by oapi-codegen
// and should not be edited manually.
package api
