// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for CreateWorkbookRequestVisibility.
const (
	CreateWorkbookRequestVisibilityPrivate CreateWorkbookRequestVisibility = "private"
	CreateWorkbookRequestVisibilityPublic  CreateWorkbookRequestVisibility = "public"
)

// Defines values for UpdateWorkbookRequestVisibility.
const (
	UpdateWorkbookRequestVisibilityPrivate UpdateWorkbookRequestVisibility = "private"
	UpdateWorkbookRequestVisibilityPublic  UpdateWorkbookRequestVisibility = "public"
)

// Defines values for WorkbookResponseVisibility.
const (
	Private WorkbookResponseVisibility = "private"
	Public  WorkbookResponseVisibility = "public"
)

// AddQuestionRequest defines model for AddQuestionRequest.
type AddQuestionRequest struct {
	Content      string `binding:"required,max=10000" json:"content"`
	OrderIndex   int32  `binding:"gte=0" json:"orderIndex"`
	QuestionType string `binding:"required" json:"questionType"`
}

// CreateWorkbookRequest defines model for CreateWorkbookRequest.
type CreateWorkbookRequest struct {
	Description *string                         `binding:"max=1000" json:"description,omitempty"`
	SpaceID     int32                           `binding:"required" json:"spaceId"`
	Title       string                          `binding:"required,max=200" json:"title"`
	Visibility  CreateWorkbookRequestVisibility `binding:"required,oneof=private public" json:"visibility"`
}

// CreateWorkbookRequestVisibility defines model for CreateWorkbookRequest.Visibility.
type CreateWorkbookRequestVisibility string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse struct {
	Status string `json:"status"`
}

// ListPublicResponse defines model for ListPublicResponse.
type ListPublicResponse struct {
	Workbooks []PublicWorkbookResponse `json:"workbooks"`
}

// ListQuestionsResponse defines model for ListQuestionsResponse.
type ListQuestionsResponse struct {
	Questions []QuestionResponse `json:"questions"`
}

// ListSharedResponse defines model for ListSharedResponse.
type ListSharedResponse struct {
	References []SharedItemResponse `json:"references"`
}

// ListWorkbooksResponse defines model for ListWorkbooksResponse.
type ListWorkbooksResponse struct {
	Workbooks []WorkbookResponse `json:"workbooks"`
}

// PublicWorkbookResponse defines model for PublicWorkbookResponse.
type PublicWorkbookResponse struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description string    `json:"description"`
	OwnerID     string    `json:"ownerId"`
	Title       string    `json:"title"`
	WorkbookID  string    `json:"workbookId"`
}

// QuestionResponse defines model for QuestionResponse.
type QuestionResponse struct {
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"createdAt"`
	OrderIndex   int32     `json:"orderIndex"`
	QuestionID   string    `json:"questionId"`
	QuestionType string    `json:"questionType"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// ShareWorkbookResponse defines model for ShareWorkbookResponse.
type ShareWorkbookResponse struct {
	AddedAt     time.Time `json:"addedAt"`
	ReferenceID string    `json:"referenceId"`
	WorkbookID  string    `json:"workbookId"`
}

// SharedItemResponse defines model for SharedItemResponse.
type SharedItemResponse struct {
	AddedAt     time.Time `json:"addedAt"`
	ReferenceID string    `json:"referenceId"`
	WorkbookID  string    `json:"workbookId"`
}

// UpdateQuestionRequest defines model for UpdateQuestionRequest.
type UpdateQuestionRequest struct {
	Content    string `binding:"required,max=10000" json:"content"`
	OrderIndex int32  `binding:"gte=0" json:"orderIndex"`
}

// UpdateWorkbookRequest defines model for UpdateWorkbookRequest.
type UpdateWorkbookRequest struct {
	Description *string                         `binding:"max=1000" json:"description,omitempty"`
	Title       string                          `binding:"required,max=200" json:"title"`
	Visibility  UpdateWorkbookRequestVisibility `binding:"required,oneof=private public" json:"visibility"`
}

// UpdateWorkbookRequestVisibility defines model for UpdateWorkbookRequest.Visibility.
type UpdateWorkbookRequestVisibility string

// WorkbookResponse defines model for WorkbookResponse.
type WorkbookResponse struct {
	CreatedAt      time.Time                  `json:"createdAt"`
	Description    string                     `json:"description"`
	OrganizationID string                     `json:"organizationId"`
	OwnerID        string                     `json:"ownerId"`
	SpaceID        int32                      `json:"spaceId"`
	Title          string                     `json:"title"`
	UpdatedAt      time.Time                  `json:"updatedAt"`
	Visibility     WorkbookResponseVisibility `json:"visibility"`
	WorkbookID     string                     `json:"workbookId"`
}

// WorkbookResponseVisibility defines model for WorkbookResponse.Visibility.
type WorkbookResponseVisibility string

// CreateWorkbookJSONRequestBody defines body for CreateWorkbook for application/json ContentType.
type CreateWorkbookJSONRequestBody = CreateWorkbookRequest

// UpdateWorkbookJSONRequestBody defines body for UpdateWorkbook for application/json ContentType.
type UpdateWorkbookJSONRequestBody = UpdateWorkbookRequest

// AddQuestionJSONRequestBody defines body for AddQuestion for application/json ContentType.
type AddQuestionJSONRequestBody = AddQuestionRequest

// UpdateQuestionJSONRequestBody defines body for UpdateQuestion for application/json ContentType.
type UpdateQuestionJSONRequestBody = UpdateQuestionRequest
