// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package question_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/service/question"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAudioBatchUsecase creates a new instance of MockAudioBatchUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudioBatchUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudioBatchUsecase {
	mock := &MockAudioBatchUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudioBatchUsecase is an autogenerated mock type for the AudioBatchUsecase type
type MockAudioBatchUsecase struct {
	mock.Mock
}

type MockAudioBatchUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudioBatchUsecase) EXPECT() *MockAudioBatchUsecase_Expecter {
	return &MockAudioBatchUsecase_Expecter{mock: &_m.Mock}
}

// ClaimAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) ClaimAudio(ctx context.Context, input *question.ClaimAudioInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ClaimAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ClaimAudioInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioBatchUsecase_ClaimAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimAudio'
type MockAudioBatchUsecase_ClaimAudio_Call struct {
	*mock.Call
}

// ClaimAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.ClaimAudioInput
func (_e *MockAudioBatchUsecase_Expecter) ClaimAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_ClaimAudio_Call {
	return &MockAudioBatchUsecase_ClaimAudio_Call{Call: _e.mock.On("ClaimAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_ClaimAudio_Call) Run(run func(ctx context.Context, input *question.ClaimAudioInput)) *MockAudioBatchUsecase_ClaimAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.ClaimAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.ClaimAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_ClaimAudio_Call) Return(err error) *MockAudioBatchUsecase_ClaimAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioBatchUsecase_ClaimAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.ClaimAudioInput) error) *MockAudioBatchUsecase_ClaimAudio_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) CompleteAudio(ctx context.Context, input *question.CompleteAudioInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CompleteAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.CompleteAudioInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioBatchUsecase_CompleteAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteAudio'
type MockAudioBatchUsecase_CompleteAudio_Call struct {
	*mock.Call
}

// CompleteAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.CompleteAudioInput
func (_e *MockAudioBatchUsecase_Expecter) CompleteAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_CompleteAudio_Call {
	return &MockAudioBatchUsecase_CompleteAudio_Call{Call: _e.mock.On("CompleteAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_CompleteAudio_Call) Run(run func(ctx context.Context, input *question.CompleteAudioInput)) *MockAudioBatchUsecase_CompleteAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.CompleteAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.CompleteAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_CompleteAudio_Call) Return(err error) *MockAudioBatchUsecase_CompleteAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioBatchUsecase_CompleteAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.CompleteAudioInput) error) *MockAudioBatchUsecase_CompleteAudio_Call {
	_c.Call.Return(run)
	return _c
}

// FailAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) FailAudio(ctx context.Context, input *question.FailAudioInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for FailAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.FailAudioInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioBatchUsecase_FailAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailAudio'
type MockAudioBatchUsecase_FailAudio_Call struct {
	*mock.Call
}

// FailAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.FailAudioInput
func (_e *MockAudioBatchUsecase_Expecter) FailAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_FailAudio_Call {
	return &MockAudioBatchUsecase_FailAudio_Call{Call: _e.mock.On("FailAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_FailAudio_Call) Run(run func(ctx context.Context, input *question.FailAudioInput)) *MockAudioBatchUsecase_FailAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.FailAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.FailAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_FailAudio_Call) Return(err error) *MockAudioBatchUsecase_FailAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioBatchUsecase_FailAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.FailAudioInput) error) *MockAudioBatchUsecase_FailAudio_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) ListPendingAudio(ctx context.Context, input *question.ListPendingAudioInput) (*question.ListPendingAudioOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingAudio")
	}

	var r0 *question.ListPendingAudioOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ListPendingAudioInput) (*question.ListPendingAudioOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ListPendingAudioInput) *question.ListPendingAudioOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.ListPendingAudioOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.ListPendingAudioInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudioBatchUsecase_ListPendingAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingAudio'
type MockAudioBatchUsecase_ListPendingAudio_Call struct {
	*mock.Call
}

// ListPendingAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.ListPendingAudioInput
func (_e *MockAudioBatchUsecase_Expecter) ListPendingAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_ListPendingAudio_Call {
	return &MockAudioBatchUsecase_ListPendingAudio_Call{Call: _e.mock.On("ListPendingAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_ListPendingAudio_Call) Run(run func(ctx context.Context, input *question.ListPendingAudioInput)) *MockAudioBatchUsecase_ListPendingAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.ListPendingAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.ListPendingAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_ListPendingAudio_Call) Return(listPendingAudioOutput *question.ListPendingAudioOutput, err error) *MockAudioBatchUsecase_ListPendingAudio_Call {
	_c.Call.Return(listPendingAudioOutput, err)
	return _c
}

func (_c *MockAudioBatchUsecase_ListPendingAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.ListPendingAudioInput) (*question.ListPendingAudioOutput, error)) *MockAudioBatchUsecase_ListPendingAudio_Call {
	_c.Call.Return(run)
	return _c
}

// ReclaimStaleAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) ReclaimStaleAudio(ctx context.Context, input *question.ReclaimStaleAudioInput) (*question.ReclaimStaleAudioOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ReclaimStaleAudio")
	}

	var r0 *question.ReclaimStaleAudioOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ReclaimStaleAudioInput) (*question.ReclaimStaleAudioOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ReclaimStaleAudioInput) *question.ReclaimStaleAudioOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.ReclaimStaleAudioOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.ReclaimStaleAudioInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudioBatchUsecase_ReclaimStaleAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReclaimStaleAudio'
type MockAudioBatchUsecase_ReclaimStaleAudio_Call struct {
	*mock.Call
}

// ReclaimStaleAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.ReclaimStaleAudioInput
func (_e *MockAudioBatchUsecase_Expecter) ReclaimStaleAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	return &MockAudioBatchUsecase_ReclaimStaleAudio_Call{Call: _e.mock.On("ReclaimStaleAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_ReclaimStaleAudio_Call) Run(run func(ctx context.Context, input *question.ReclaimStaleAudioInput)) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.ReclaimStaleAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.ReclaimStaleAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_ReclaimStaleAudio_Call) Return(reclaimStaleAudioOutput *question.ReclaimStaleAudioOutput, err error) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	_c.Call.Return(reclaimStaleAudioOutput, err)
	return _c
}

func (_c *MockAudioBatchUsecase_ReclaimStaleAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.ReclaimStaleAudioInput) (*question.ReclaimStaleAudioOutput, error)) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	_c.Call.Return(run)
	return _c
}
