// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package question_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/service/question"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAddQuestionUsecase creates a new instance of MockAddQuestionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddQuestionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddQuestionUsecase {
	mock := &MockAddQuestionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAddQuestionUsecase is an autogenerated mock type for the AddQuestionUsecase type
type MockAddQuestionUsecase struct {
	mock.Mock
}

type MockAddQuestionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddQuestionUsecase) EXPECT() *MockAddQuestionUsecase_Expecter {
	return &MockAddQuestionUsecase_Expecter{mock: &_m.Mock}
}

// AddQuestion provides a mock function for the type MockAddQuestionUsecase
func (_mock *MockAddQuestionUsecase) AddQuestion(ctx context.Context, input *question.AddQuestionInput) (*question.AddQuestionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddQuestion")
	}

	var r0 *question.AddQuestionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.AddQuestionInput) (*question.AddQuestionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.AddQuestionInput) *question.AddQuestionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.AddQuestionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.AddQuestionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddQuestionUsecase_AddQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddQuestion'
type MockAddQuestionUsecase_AddQuestion_Call struct {
	*mock.Call
}

// AddQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.AddQuestionInput
func (_e *MockAddQuestionUsecase_Expecter) AddQuestion(ctx interface{}, input interface{}) *MockAddQuestionUsecase_AddQuestion_Call {
	return &MockAddQuestionUsecase_AddQuestion_Call{Call: _e.mock.On("AddQuestion", ctx, input)}
}

func (_c *MockAddQuestionUsecase_AddQuestion_Call) Run(run func(ctx context.Context, input *question.AddQuestionInput)) *MockAddQuestionUsecase_AddQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.AddQuestionInput
		if args[1] != nil {
			arg1 = args[1].(*question.AddQuestionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAddQuestionUsecase_AddQuestion_Call) Return(addQuestionOutput *question.AddQuestionOutput, err error) *MockAddQuestionUsecase_AddQuestion_Call {
	_c.Call.Return(addQuestionOutput, err)
	return _c
}

func (_c *MockAddQuestionUsecase_AddQuestion_Call) RunAndReturn(run func(ctx context.Context, input *question.AddQuestionInput) (*question.AddQuestionOutput, error)) *MockAddQuestionUsecase_AddQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAudioBatchUsecase creates a new instance of MockAudioBatchUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudioBatchUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudioBatchUsecase {
	mock := &MockAudioBatchUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudioBatchUsecase is an autogenerated mock type for the AudioBatchUsecase type
type MockAudioBatchUsecase struct {
	mock.Mock
}

type MockAudioBatchUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudioBatchUsecase) EXPECT() *MockAudioBatchUsecase_Expecter {
	return &MockAudioBatchUsecase_Expecter{mock: &_m.Mock}
}

// ClaimAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) ClaimAudio(ctx context.Context, input *question.ClaimAudioInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ClaimAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ClaimAudioInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioBatchUsecase_ClaimAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimAudio'
type MockAudioBatchUsecase_ClaimAudio_Call struct {
	*mock.Call
}

// ClaimAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.ClaimAudioInput
func (_e *MockAudioBatchUsecase_Expecter) ClaimAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_ClaimAudio_Call {
	return &MockAudioBatchUsecase_ClaimAudio_Call{Call: _e.mock.On("ClaimAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_ClaimAudio_Call) Run(run func(ctx context.Context, input *question.ClaimAudioInput)) *MockAudioBatchUsecase_ClaimAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.ClaimAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.ClaimAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_ClaimAudio_Call) Return(err error) *MockAudioBatchUsecase_ClaimAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioBatchUsecase_ClaimAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.ClaimAudioInput) error) *MockAudioBatchUsecase_ClaimAudio_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) CompleteAudio(ctx context.Context, input *question.CompleteAudioInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CompleteAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.CompleteAudioInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioBatchUsecase_CompleteAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteAudio'
type MockAudioBatchUsecase_CompleteAudio_Call struct {
	*mock.Call
}

// CompleteAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.CompleteAudioInput
func (_e *MockAudioBatchUsecase_Expecter) CompleteAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_CompleteAudio_Call {
	return &MockAudioBatchUsecase_CompleteAudio_Call{Call: _e.mock.On("CompleteAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_CompleteAudio_Call) Run(run func(ctx context.Context, input *question.CompleteAudioInput)) *MockAudioBatchUsecase_CompleteAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.CompleteAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.CompleteAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_CompleteAudio_Call) Return(err error) *MockAudioBatchUsecase_CompleteAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioBatchUsecase_CompleteAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.CompleteAudioInput) error) *MockAudioBatchUsecase_CompleteAudio_Call {
	_c.Call.Return(run)
	return _c
}

// FailAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) FailAudio(ctx context.Context, input *question.FailAudioInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for FailAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.FailAudioInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioBatchUsecase_FailAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailAudio'
type MockAudioBatchUsecase_FailAudio_Call struct {
	*mock.Call
}

// FailAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.FailAudioInput
func (_e *MockAudioBatchUsecase_Expecter) FailAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_FailAudio_Call {
	return &MockAudioBatchUsecase_FailAudio_Call{Call: _e.mock.On("FailAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_FailAudio_Call) Run(run func(ctx context.Context, input *question.FailAudioInput)) *MockAudioBatchUsecase_FailAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.FailAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.FailAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_FailAudio_Call) Return(err error) *MockAudioBatchUsecase_FailAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioBatchUsecase_FailAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.FailAudioInput) error) *MockAudioBatchUsecase_FailAudio_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) ListPendingAudio(ctx context.Context, input *question.ListPendingAudioInput) (*question.ListPendingAudioOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingAudio")
	}

	var r0 *question.ListPendingAudioOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ListPendingAudioInput) (*question.ListPendingAudioOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ListPendingAudioInput) *question.ListPendingAudioOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.ListPendingAudioOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.ListPendingAudioInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudioBatchUsecase_ListPendingAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingAudio'
type MockAudioBatchUsecase_ListPendingAudio_Call struct {
	*mock.Call
}

// ListPendingAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.ListPendingAudioInput
func (_e *MockAudioBatchUsecase_Expecter) ListPendingAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_ListPendingAudio_Call {
	return &MockAudioBatchUsecase_ListPendingAudio_Call{Call: _e.mock.On("ListPendingAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_ListPendingAudio_Call) Run(run func(ctx context.Context, input *question.ListPendingAudioInput)) *MockAudioBatchUsecase_ListPendingAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.ListPendingAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.ListPendingAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_ListPendingAudio_Call) Return(listPendingAudioOutput *question.ListPendingAudioOutput, err error) *MockAudioBatchUsecase_ListPendingAudio_Call {
	_c.Call.Return(listPendingAudioOutput, err)
	return _c
}

func (_c *MockAudioBatchUsecase_ListPendingAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.ListPendingAudioInput) (*question.ListPendingAudioOutput, error)) *MockAudioBatchUsecase_ListPendingAudio_Call {
	_c.Call.Return(run)
	return _c
}

// ReclaimStaleAudio provides a mock function for the type MockAudioBatchUsecase
func (_mock *MockAudioBatchUsecase) ReclaimStaleAudio(ctx context.Context, input *question.ReclaimStaleAudioInput) (*question.ReclaimStaleAudioOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ReclaimStaleAudio")
	}

	var r0 *question.ReclaimStaleAudioOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ReclaimStaleAudioInput) (*question.ReclaimStaleAudioOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ReclaimStaleAudioInput) *question.ReclaimStaleAudioOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.ReclaimStaleAudioOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.ReclaimStaleAudioInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudioBatchUsecase_ReclaimStaleAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReclaimStaleAudio'
type MockAudioBatchUsecase_ReclaimStaleAudio_Call struct {
	*mock.Call
}

// ReclaimStaleAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.ReclaimStaleAudioInput
func (_e *MockAudioBatchUsecase_Expecter) ReclaimStaleAudio(ctx interface{}, input interface{}) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	return &MockAudioBatchUsecase_ReclaimStaleAudio_Call{Call: _e.mock.On("ReclaimStaleAudio", ctx, input)}
}

func (_c *MockAudioBatchUsecase_ReclaimStaleAudio_Call) Run(run func(ctx context.Context, input *question.ReclaimStaleAudioInput)) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.ReclaimStaleAudioInput
		if args[1] != nil {
			arg1 = args[1].(*question.ReclaimStaleAudioInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioBatchUsecase_ReclaimStaleAudio_Call) Return(reclaimStaleAudioOutput *question.ReclaimStaleAudioOutput, err error) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	_c.Call.Return(reclaimStaleAudioOutput, err)
	return _c
}

func (_c *MockAudioBatchUsecase_ReclaimStaleAudio_Call) RunAndReturn(run func(ctx context.Context, input *question.ReclaimStaleAudioInput) (*question.ReclaimStaleAudioOutput, error)) *MockAudioBatchUsecase_ReclaimStaleAudio_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteQuestionUsecase creates a new instance of MockDeleteQuestionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteQuestionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteQuestionUsecase {
	mock := &MockDeleteQuestionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteQuestionUsecase is an autogenerated mock type for the DeleteQuestionUsecase type
type MockDeleteQuestionUsecase struct {
	mock.Mock
}

type MockDeleteQuestionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteQuestionUsecase) EXPECT() *MockDeleteQuestionUsecase_Expecter {
	return &MockDeleteQuestionUsecase_Expecter{mock: &_m.Mock}
}

// DeleteQuestion provides a mock function for the type MockDeleteQuestionUsecase
func (_mock *MockDeleteQuestionUsecase) DeleteQuestion(ctx context.Context, input *question.DeleteQuestionInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.DeleteQuestionInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleteQuestionUsecase_DeleteQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuestion'
type MockDeleteQuestionUsecase_DeleteQuestion_Call struct {
	*mock.Call
}

// DeleteQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.DeleteQuestionInput
func (_e *MockDeleteQuestionUsecase_Expecter) DeleteQuestion(ctx interface{}, input interface{}) *MockDeleteQuestionUsecase_DeleteQuestion_Call {
	return &MockDeleteQuestionUsecase_DeleteQuestion_Call{Call: _e.mock.On("DeleteQuestion", ctx, input)}
}

func (_c *MockDeleteQuestionUsecase_DeleteQuestion_Call) Run(run func(ctx context.Context, input *question.DeleteQuestionInput)) *MockDeleteQuestionUsecase_DeleteQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.DeleteQuestionInput
		if args[1] != nil {
			arg1 = args[1].(*question.DeleteQuestionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleteQuestionUsecase_DeleteQuestion_Call) Return(err error) *MockDeleteQuestionUsecase_DeleteQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleteQuestionUsecase_DeleteQuestion_Call) RunAndReturn(run func(ctx context.Context, input *question.DeleteQuestionInput) error) *MockDeleteQuestionUsecase_DeleteQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetQuestionUsecase creates a new instance of MockGetQuestionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetQuestionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetQuestionUsecase {
	mock := &MockGetQuestionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetQuestionUsecase is an autogenerated mock type for the GetQuestionUsecase type
type MockGetQuestionUsecase struct {
	mock.Mock
}

type MockGetQuestionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetQuestionUsecase) EXPECT() *MockGetQuestionUsecase_Expecter {
	return &MockGetQuestionUsecase_Expecter{mock: &_m.Mock}
}

// GetQuestion provides a mock function for the type MockGetQuestionUsecase
func (_mock *MockGetQuestionUsecase) GetQuestion(ctx context.Context, input *question.GetQuestionInput) (*question.GetQuestionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestion")
	}

	var r0 *question.GetQuestionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.GetQuestionInput) (*question.GetQuestionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.GetQuestionInput) *question.GetQuestionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.GetQuestionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.GetQuestionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetQuestionUsecase_GetQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestion'
type MockGetQuestionUsecase_GetQuestion_Call struct {
	*mock.Call
}

// GetQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.GetQuestionInput
func (_e *MockGetQuestionUsecase_Expecter) GetQuestion(ctx interface{}, input interface{}) *MockGetQuestionUsecase_GetQuestion_Call {
	return &MockGetQuestionUsecase_GetQuestion_Call{Call: _e.mock.On("GetQuestion", ctx, input)}
}

func (_c *MockGetQuestionUsecase_GetQuestion_Call) Run(run func(ctx context.Context, input *question.GetQuestionInput)) *MockGetQuestionUsecase_GetQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.GetQuestionInput
		if args[1] != nil {
			arg1 = args[1].(*question.GetQuestionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetQuestionUsecase_GetQuestion_Call) Return(getQuestionOutput *question.GetQuestionOutput, err error) *MockGetQuestionUsecase_GetQuestion_Call {
	_c.Call.Return(getQuestionOutput, err)
	return _c
}

func (_c *MockGetQuestionUsecase_GetQuestion_Call) RunAndReturn(run func(ctx context.Context, input *question.GetQuestionInput) (*question.GetQuestionOutput, error)) *MockGetQuestionUsecase_GetQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListQuestionsUsecase creates a new instance of MockListQuestionsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListQuestionsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListQuestionsUsecase {
	mock := &MockListQuestionsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListQuestionsUsecase is an autogenerated mock type for the ListQuestionsUsecase type
type MockListQuestionsUsecase struct {
	mock.Mock
}

type MockListQuestionsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListQuestionsUsecase) EXPECT() *MockListQuestionsUsecase_Expecter {
	return &MockListQuestionsUsecase_Expecter{mock: &_m.Mock}
}

// ListQuestions provides a mock function for the type MockListQuestionsUsecase
func (_mock *MockListQuestionsUsecase) ListQuestions(ctx context.Context, input *question.ListQuestionsInput) (*question.ListQuestionsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListQuestions")
	}

	var r0 *question.ListQuestionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ListQuestionsInput) (*question.ListQuestionsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.ListQuestionsInput) *question.ListQuestionsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.ListQuestionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.ListQuestionsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListQuestionsUsecase_ListQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuestions'
type MockListQuestionsUsecase_ListQuestions_Call struct {
	*mock.Call
}

// ListQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.ListQuestionsInput
func (_e *MockListQuestionsUsecase_Expecter) ListQuestions(ctx interface{}, input interface{}) *MockListQuestionsUsecase_ListQuestions_Call {
	return &MockListQuestionsUsecase_ListQuestions_Call{Call: _e.mock.On("ListQuestions", ctx, input)}
}

func (_c *MockListQuestionsUsecase_ListQuestions_Call) Run(run func(ctx context.Context, input *question.ListQuestionsInput)) *MockListQuestionsUsecase_ListQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.ListQuestionsInput
		if args[1] != nil {
			arg1 = args[1].(*question.ListQuestionsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListQuestionsUsecase_ListQuestions_Call) Return(listQuestionsOutput *question.ListQuestionsOutput, err error) *MockListQuestionsUsecase_ListQuestions_Call {
	_c.Call.Return(listQuestionsOutput, err)
	return _c
}

func (_c *MockListQuestionsUsecase_ListQuestions_Call) RunAndReturn(run func(ctx context.Context, input *question.ListQuestionsInput) (*question.ListQuestionsOutput, error)) *MockListQuestionsUsecase_ListQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateQuestionUsecase creates a new instance of MockUpdateQuestionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateQuestionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateQuestionUsecase {
	mock := &MockUpdateQuestionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateQuestionUsecase is an autogenerated mock type for the UpdateQuestionUsecase type
type MockUpdateQuestionUsecase struct {
	mock.Mock
}

type MockUpdateQuestionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateQuestionUsecase) EXPECT() *MockUpdateQuestionUsecase_Expecter {
	return &MockUpdateQuestionUsecase_Expecter{mock: &_m.Mock}
}

// UpdateQuestion provides a mock function for the type MockUpdateQuestionUsecase
func (_mock *MockUpdateQuestionUsecase) UpdateQuestion(ctx context.Context, input *question.UpdateQuestionInput) (*question.UpdateQuestionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuestion")
	}

	var r0 *question.UpdateQuestionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.UpdateQuestionInput) (*question.UpdateQuestionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.UpdateQuestionInput) *question.UpdateQuestionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.UpdateQuestionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *question.UpdateQuestionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateQuestionUsecase_UpdateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuestion'
type MockUpdateQuestionUsecase_UpdateQuestion_Call struct {
	*mock.Call
}

// UpdateQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - input *question.UpdateQuestionInput
func (_e *MockUpdateQuestionUsecase_Expecter) UpdateQuestion(ctx interface{}, input interface{}) *MockUpdateQuestionUsecase_UpdateQuestion_Call {
	return &MockUpdateQuestionUsecase_UpdateQuestion_Call{Call: _e.mock.On("UpdateQuestion", ctx, input)}
}

func (_c *MockUpdateQuestionUsecase_UpdateQuestion_Call) Run(run func(ctx context.Context, input *question.UpdateQuestionInput)) *MockUpdateQuestionUsecase_UpdateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.UpdateQuestionInput
		if args[1] != nil {
			arg1 = args[1].(*question.UpdateQuestionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateQuestionUsecase_UpdateQuestion_Call) Return(updateQuestionOutput *question.UpdateQuestionOutput, err error) *MockUpdateQuestionUsecase_UpdateQuestion_Call {
	_c.Call.Return(updateQuestionOutput, err)
	return _c
}

func (_c *MockUpdateQuestionUsecase_UpdateQuestion_Call) RunAndReturn(run func(ctx context.Context, input *question.UpdateQuestionInput) (*question.UpdateQuestionOutput, error)) *MockUpdateQuestionUsecase_UpdateQuestion_Call {
	_c.Call.Return(run)
	return _c
}
