load("@rules_go//go:def.bzl", "go_library")
load("//bazel:go_test.bzl", "smart_go_test")

go_library(
    name = "group",
    srcs = [
        "command.go",
        "create_group_command.go",
        "doc.go",
    ],
    importpath = "github.com/mocoarow/cocotola-1.26/cocotola-auth/usecase/group",
    visibility = ["//visibility:public"],
    deps = [
        "//cocotola-auth/domain",
        "//cocotola-auth/domain/group",
        "//cocotola-auth/domain/rbac",
        "//cocotola-auth/service/group",
    ],
)

smart_go_test(
    name = "group_test",
    srcs = [
        "create_group_command_s_test.go",
        "fixtures_test.go",
        "mocks_test.go",
    ],
    deps = [
        ":group",
        "//cocotola-auth/domain",
        "//cocotola-auth/domain/group",
        "//cocotola-auth/domain/rbac",
        "//cocotola-auth/service/group",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
    ],
)
