// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package seed_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-init/seed"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkbookAPIClient creates a new instance of MockWorkbookAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkbookAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkbookAPIClient {
	mock := &MockWorkbookAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkbookAPIClient is an autogenerated mock type for the WorkbookAPIClient type
type MockWorkbookAPIClient struct {
	mock.Mock
}

type MockWorkbookAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkbookAPIClient) EXPECT() *MockWorkbookAPIClient_Expecter {
	return &MockWorkbookAPIClient_Expecter{mock: &_m.Mock}
}

// AddQuestion provides a mock function for the type MockWorkbookAPIClient
func (_mock *MockWorkbookAPIClient) AddQuestion(ctx context.Context, organizationID string, workbookID string, body seed.AddQuestionRequest) error {
	ret := _mock.Called(ctx, organizationID, workbookID, body)

	if len(ret) == 0 {
		panic("no return value specified for AddQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, seed.AddQuestionRequest) error); ok {
		r0 = returnFunc(ctx, organizationID, workbookID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkbookAPIClient_AddQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddQuestion'
type MockWorkbookAPIClient_AddQuestion_Call struct {
	*mock.Call
}

// AddQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - workbookID string
//   - body seed.AddQuestionRequest
func (_e *MockWorkbookAPIClient_Expecter) AddQuestion(ctx interface{}, organizationID interface{}, workbookID interface{}, body interface{}) *MockWorkbookAPIClient_AddQuestion_Call {
	return &MockWorkbookAPIClient_AddQuestion_Call{Call: _e.mock.On("AddQuestion", ctx, organizationID, workbookID, body)}
}

func (_c *MockWorkbookAPIClient_AddQuestion_Call) Run(run func(ctx context.Context, organizationID string, workbookID string, body seed.AddQuestionRequest)) *MockWorkbookAPIClient_AddQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 seed.AddQuestionRequest
		if args[3] != nil {
			arg3 = args[3].(seed.AddQuestionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWorkbookAPIClient_AddQuestion_Call) Return(err error) *MockWorkbookAPIClient_AddQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkbookAPIClient_AddQuestion_Call) RunAndReturn(run func(ctx context.Context, organizationID string, workbookID string, body seed.AddQuestionRequest) error) *MockWorkbookAPIClient_AddQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkbook provides a mock function for the type MockWorkbookAPIClient
func (_mock *MockWorkbookAPIClient) CreateWorkbook(ctx context.Context, organizationID string, body seed.CreateWorkbookRequest) (string, error) {
	ret := _mock.Called(ctx, organizationID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkbook")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, seed.CreateWorkbookRequest) (string, error)); ok {
		return returnFunc(ctx, organizationID, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, seed.CreateWorkbookRequest) string); ok {
		r0 = returnFunc(ctx, organizationID, body)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, seed.CreateWorkbookRequest) error); ok {
		r1 = returnFunc(ctx, organizationID, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkbookAPIClient_CreateWorkbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkbook'
type MockWorkbookAPIClient_CreateWorkbook_Call struct {
	*mock.Call
}

// CreateWorkbook is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - body seed.CreateWorkbookRequest
func (_e *MockWorkbookAPIClient_Expecter) CreateWorkbook(ctx interface{}, organizationID interface{}, body interface{}) *MockWorkbookAPIClient_CreateWorkbook_Call {
	return &MockWorkbookAPIClient_CreateWorkbook_Call{Call: _e.mock.On("CreateWorkbook", ctx, organizationID, body)}
}

func (_c *MockWorkbookAPIClient_CreateWorkbook_Call) Run(run func(ctx context.Context, organizationID string, body seed.CreateWorkbookRequest)) *MockWorkbookAPIClient_CreateWorkbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 seed.CreateWorkbookRequest
		if args[2] != nil {
			arg2 = args[2].(seed.CreateWorkbookRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkbookAPIClient_CreateWorkbook_Call) Return(s string, err error) *MockWorkbookAPIClient_CreateWorkbook_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockWorkbookAPIClient_CreateWorkbook_Call) RunAndReturn(run func(ctx context.Context, organizationID string, body seed.CreateWorkbookRequest) (string, error)) *MockWorkbookAPIClient_CreateWorkbook_Call {
	_c.Call.Return(run)
	return _c
}

// ListQuestions provides a mock function for the type MockWorkbookAPIClient
func (_mock *MockWorkbookAPIClient) ListQuestions(ctx context.Context, organizationID string, workbookID string) ([]seed.QuestionListItem, error) {
	ret := _mock.Called(ctx, organizationID, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for ListQuestions")
	}

	var r0 []seed.QuestionListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]seed.QuestionListItem, error)); ok {
		return returnFunc(ctx, organizationID, workbookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []seed.QuestionListItem); ok {
		r0 = returnFunc(ctx, organizationID, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]seed.QuestionListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, organizationID, workbookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkbookAPIClient_ListQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuestions'
type MockWorkbookAPIClient_ListQuestions_Call struct {
	*mock.Call
}

// ListQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - workbookID string
func (_e *MockWorkbookAPIClient_Expecter) ListQuestions(ctx interface{}, organizationID interface{}, workbookID interface{}) *MockWorkbookAPIClient_ListQuestions_Call {
	return &MockWorkbookAPIClient_ListQuestions_Call{Call: _e.mock.On("ListQuestions", ctx, organizationID, workbookID)}
}

func (_c *MockWorkbookAPIClient_ListQuestions_Call) Run(run func(ctx context.Context, organizationID string, workbookID string)) *MockWorkbookAPIClient_ListQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkbookAPIClient_ListQuestions_Call) Return(questionListItems []seed.QuestionListItem, err error) *MockWorkbookAPIClient_ListQuestions_Call {
	_c.Call.Return(questionListItems, err)
	return _c
}

func (_c *MockWorkbookAPIClient_ListQuestions_Call) RunAndReturn(run func(ctx context.Context, organizationID string, workbookID string) ([]seed.QuestionListItem, error)) *MockWorkbookAPIClient_ListQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkbooks provides a mock function for the type MockWorkbookAPIClient
func (_mock *MockWorkbookAPIClient) ListWorkbooks(ctx context.Context, organizationID string, spaceID string) ([]seed.WorkbookListItem, error) {
	ret := _mock.Called(ctx, organizationID, spaceID)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkbooks")
	}

	var r0 []seed.WorkbookListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]seed.WorkbookListItem, error)); ok {
		return returnFunc(ctx, organizationID, spaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []seed.WorkbookListItem); ok {
		r0 = returnFunc(ctx, organizationID, spaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]seed.WorkbookListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, organizationID, spaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkbookAPIClient_ListWorkbooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkbooks'
type MockWorkbookAPIClient_ListWorkbooks_Call struct {
	*mock.Call
}

// ListWorkbooks is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - spaceID string
func (_e *MockWorkbookAPIClient_Expecter) ListWorkbooks(ctx interface{}, organizationID interface{}, spaceID interface{}) *MockWorkbookAPIClient_ListWorkbooks_Call {
	return &MockWorkbookAPIClient_ListWorkbooks_Call{Call: _e.mock.On("ListWorkbooks", ctx, organizationID, spaceID)}
}

func (_c *MockWorkbookAPIClient_ListWorkbooks_Call) Run(run func(ctx context.Context, organizationID string, spaceID string)) *MockWorkbookAPIClient_ListWorkbooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkbookAPIClient_ListWorkbooks_Call) Return(workbookListItems []seed.WorkbookListItem, err error) *MockWorkbookAPIClient_ListWorkbooks_Call {
	_c.Call.Return(workbookListItems, err)
	return _c
}

func (_c *MockWorkbookAPIClient_ListWorkbooks_Call) RunAndReturn(run func(ctx context.Context, organizationID string, spaceID string) ([]seed.WorkbookListItem, error)) *MockWorkbookAPIClient_ListWorkbooks_Call {
	_c.Call.Return(run)
	return _c
}
