// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workbook_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/workbook"
	mock "github.com/stretchr/testify/mock"
)

// newMockworkbookCreator creates a new instance of mockworkbookCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkbookCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkbookCreator {
	mock := &mockworkbookCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkbookCreator is an autogenerated mock type for the workbookCreator type
type mockworkbookCreator struct {
	mock.Mock
}

type mockworkbookCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkbookCreator) EXPECT() *mockworkbookCreator_Expecter {
	return &mockworkbookCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockworkbookCreator
func (_mock *mockworkbookCreator) Create(ctx context.Context, spaceID string, ownerID string, organizationID string, title string, description string, visibility string) (string, error) {
	ret := _mock.Called(ctx, spaceID, ownerID, organizationID, title, description, visibility)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (string, error)); ok {
		return returnFunc(ctx, spaceID, ownerID, organizationID, title, description, visibility)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) string); ok {
		r0 = returnFunc(ctx, spaceID, ownerID, organizationID, title, description, visibility)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, spaceID, ownerID, organizationID, title, description, visibility)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkbookCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockworkbookCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spaceID string
//   - ownerID string
//   - organizationID string
//   - title string
//   - description string
//   - visibility string
func (_e *mockworkbookCreator_Expecter) Create(ctx interface{}, spaceID interface{}, ownerID interface{}, organizationID interface{}, title interface{}, description interface{}, visibility interface{}) *mockworkbookCreator_Create_Call {
	return &mockworkbookCreator_Create_Call{Call: _e.mock.On("Create", ctx, spaceID, ownerID, organizationID, title, description, visibility)}
}

func (_c *mockworkbookCreator_Create_Call) Run(run func(ctx context.Context, spaceID string, ownerID string, organizationID string, title string, description string, visibility string)) *mockworkbookCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *mockworkbookCreator_Create_Call) Return(s string, err error) *mockworkbookCreator_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockworkbookCreator_Create_Call) RunAndReturn(run func(ctx context.Context, spaceID string, ownerID string, organizationID string, title string, description string, visibility string) (string, error)) *mockworkbookCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkbookFinder creates a new instance of mockworkbookFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkbookFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkbookFinder {
	mock := &mockworkbookFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkbookFinder is an autogenerated mock type for the workbookFinder type
type mockworkbookFinder struct {
	mock.Mock
}

type mockworkbookFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkbookFinder) EXPECT() *mockworkbookFinder_Expecter {
	return &mockworkbookFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockworkbookFinder
func (_mock *mockworkbookFinder) FindByID(ctx context.Context, id string) (*workbook.Workbook, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *workbook.Workbook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*workbook.Workbook, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *workbook.Workbook); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.Workbook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkbookFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockworkbookFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockworkbookFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockworkbookFinder_FindByID_Call {
	return &mockworkbookFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockworkbookFinder_FindByID_Call) Run(run func(ctx context.Context, id string)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) Return(workbook1 *workbook.Workbook, err error) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(workbook1, err)
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*workbook.Workbook, error)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySpaceID provides a mock function for the type mockworkbookFinder
func (_mock *mockworkbookFinder) FindBySpaceID(ctx context.Context, spaceID string) ([]workbook.Workbook, error) {
	ret := _mock.Called(ctx, spaceID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySpaceID")
	}

	var r0 []workbook.Workbook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]workbook.Workbook, error)); ok {
		return returnFunc(ctx, spaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []workbook.Workbook); ok {
		r0 = returnFunc(ctx, spaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]workbook.Workbook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, spaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkbookFinder_FindBySpaceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySpaceID'
type mockworkbookFinder_FindBySpaceID_Call struct {
	*mock.Call
}

// FindBySpaceID is a helper method to define mock.On call
//   - ctx context.Context
//   - spaceID string
func (_e *mockworkbookFinder_Expecter) FindBySpaceID(ctx interface{}, spaceID interface{}) *mockworkbookFinder_FindBySpaceID_Call {
	return &mockworkbookFinder_FindBySpaceID_Call{Call: _e.mock.On("FindBySpaceID", ctx, spaceID)}
}

func (_c *mockworkbookFinder_FindBySpaceID_Call) Run(run func(ctx context.Context, spaceID string)) *mockworkbookFinder_FindBySpaceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkbookFinder_FindBySpaceID_Call) Return(workbooks []workbook.Workbook, err error) *mockworkbookFinder_FindBySpaceID_Call {
	_c.Call.Return(workbooks, err)
	return _c
}

func (_c *mockworkbookFinder_FindBySpaceID_Call) RunAndReturn(run func(ctx context.Context, spaceID string) ([]workbook.Workbook, error)) *mockworkbookFinder_FindBySpaceID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkbookUpdater creates a new instance of mockworkbookUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkbookUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkbookUpdater {
	mock := &mockworkbookUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkbookUpdater is an autogenerated mock type for the workbookUpdater type
type mockworkbookUpdater struct {
	mock.Mock
}

type mockworkbookUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkbookUpdater) EXPECT() *mockworkbookUpdater_Expecter {
	return &mockworkbookUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type mockworkbookUpdater
func (_mock *mockworkbookUpdater) Update(ctx context.Context, wb *workbook.Workbook) error {
	ret := _mock.Called(ctx, wb)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *workbook.Workbook) error); ok {
		r0 = returnFunc(ctx, wb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkbookUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockworkbookUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - wb *workbook.Workbook
func (_e *mockworkbookUpdater_Expecter) Update(ctx interface{}, wb interface{}) *mockworkbookUpdater_Update_Call {
	return &mockworkbookUpdater_Update_Call{Call: _e.mock.On("Update", ctx, wb)}
}

func (_c *mockworkbookUpdater_Update_Call) Run(run func(ctx context.Context, wb *workbook.Workbook)) *mockworkbookUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *workbook.Workbook
		if args[1] != nil {
			arg1 = args[1].(*workbook.Workbook)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkbookUpdater_Update_Call) Return(err error) *mockworkbookUpdater_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkbookUpdater_Update_Call) RunAndReturn(run func(ctx context.Context, wb *workbook.Workbook) error) *mockworkbookUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkbookDeleter creates a new instance of mockworkbookDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkbookDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkbookDeleter {
	mock := &mockworkbookDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkbookDeleter is an autogenerated mock type for the workbookDeleter type
type mockworkbookDeleter struct {
	mock.Mock
}

type mockworkbookDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkbookDeleter) EXPECT() *mockworkbookDeleter_Expecter {
	return &mockworkbookDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type mockworkbookDeleter
func (_mock *mockworkbookDeleter) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkbookDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockworkbookDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockworkbookDeleter_Expecter) Delete(ctx interface{}, id interface{}) *mockworkbookDeleter_Delete_Call {
	return &mockworkbookDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *mockworkbookDeleter_Delete_Call) Run(run func(ctx context.Context, id string)) *mockworkbookDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkbookDeleter_Delete_Call) Return(err error) *mockworkbookDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkbookDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockworkbookDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// newMockauthorizationChecker creates a new instance of mockauthorizationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauthorizationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauthorizationChecker {
	mock := &mockauthorizationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauthorizationChecker is an autogenerated mock type for the authorizationChecker type
type mockauthorizationChecker struct {
	mock.Mock
}

type mockauthorizationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauthorizationChecker) EXPECT() *mockauthorizationChecker_Expecter {
	return &mockauthorizationChecker_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type mockauthorizationChecker
func (_mock *mockauthorizationChecker) IsAllowed(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error) {
	ret := _mock.Called(ctx, organizationID, operatorID, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) (bool, error)); ok {
		return returnFunc(ctx, organizationID, operatorID, action, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) bool); ok {
		r0 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.Action, domain.Resource) error); ok {
		r1 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauthorizationChecker_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type mockauthorizationChecker_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - operatorID string
//   - action domain.Action
//   - resource domain.Resource
func (_e *mockauthorizationChecker_Expecter) IsAllowed(ctx interface{}, organizationID interface{}, operatorID interface{}, action interface{}, resource interface{}) *mockauthorizationChecker_IsAllowed_Call {
	return &mockauthorizationChecker_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, organizationID, operatorID, action, resource)}
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Run(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.Action
		if args[3] != nil {
			arg3 = args[3].(domain.Action)
		}
		var arg4 domain.Resource
		if args[4] != nil {
			arg4 = args[4].(domain.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Return(b bool, err error) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// newMockpolicyAdder creates a new instance of mockpolicyAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockpolicyAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockpolicyAdder {
	mock := &mockpolicyAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockpolicyAdder is an autogenerated mock type for the policyAdder type
type mockpolicyAdder struct {
	mock.Mock
}

type mockpolicyAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockpolicyAdder) EXPECT() *mockpolicyAdder_Expecter {
	return &mockpolicyAdder_Expecter{mock: &_m.Mock}
}

// AddPolicyForUser provides a mock function for the type mockpolicyAdder
func (_mock *mockpolicyAdder) AddPolicyForUser(ctx context.Context, organizationID string, userID string, action domain.Action, resource domain.Resource, effect domain.Effect) error {
	ret := _mock.Called(ctx, organizationID, userID, action, resource, effect)

	if len(ret) == 0 {
		panic("no return value specified for AddPolicyForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource, domain.Effect) error); ok {
		r0 = returnFunc(ctx, organizationID, userID, action, resource, effect)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockpolicyAdder_AddPolicyForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPolicyForUser'
type mockpolicyAdder_AddPolicyForUser_Call struct {
	*mock.Call
}

// AddPolicyForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - userID string
//   - action domain.Action
//   - resource domain.Resource
//   - effect domain.Effect
func (_e *mockpolicyAdder_Expecter) AddPolicyForUser(ctx interface{}, organizationID interface{}, userID interface{}, action interface{}, resource interface{}, effect interface{}) *mockpolicyAdder_AddPolicyForUser_Call {
	return &mockpolicyAdder_AddPolicyForUser_Call{Call: _e.mock.On("AddPolicyForUser", ctx, organizationID, userID, action, resource, effect)}
}

func (_c *mockpolicyAdder_AddPolicyForUser_Call) Run(run func(ctx context.Context, organizationID string, userID string, action domain.Action, resource domain.Resource, effect domain.Effect)) *mockpolicyAdder_AddPolicyForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.Action
		if args[3] != nil {
			arg3 = args[3].(domain.Action)
		}
		var arg4 domain.Resource
		if args[4] != nil {
			arg4 = args[4].(domain.Resource)
		}
		var arg5 domain.Effect
		if args[5] != nil {
			arg5 = args[5].(domain.Effect)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockpolicyAdder_AddPolicyForUser_Call) Return(err error) *mockpolicyAdder_AddPolicyForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockpolicyAdder_AddPolicyForUser_Call) RunAndReturn(run func(ctx context.Context, organizationID string, userID string, action domain.Action, resource domain.Resource, effect domain.Effect) error) *mockpolicyAdder_AddPolicyForUser_Call {
	_c.Call.Return(run)
	return _c
}

// newMockownedWorkbookListFinder creates a new instance of mockownedWorkbookListFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockownedWorkbookListFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockownedWorkbookListFinder {
	mock := &mockownedWorkbookListFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockownedWorkbookListFinder is an autogenerated mock type for the ownedWorkbookListFinder type
type mockownedWorkbookListFinder struct {
	mock.Mock
}

type mockownedWorkbookListFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockownedWorkbookListFinder) EXPECT() *mockownedWorkbookListFinder_Expecter {
	return &mockownedWorkbookListFinder_Expecter{mock: &_m.Mock}
}

// FindByOwnerID provides a mock function for the type mockownedWorkbookListFinder
func (_mock *mockownedWorkbookListFinder) FindByOwnerID(ctx context.Context, ownerID string) (*domain.OwnedWorkbookList, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOwnerID")
	}

	var r0 *domain.OwnedWorkbookList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.OwnedWorkbookList, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.OwnedWorkbookList); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OwnedWorkbookList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockownedWorkbookListFinder_FindByOwnerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOwnerID'
type mockownedWorkbookListFinder_FindByOwnerID_Call struct {
	*mock.Call
}

// FindByOwnerID is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *mockownedWorkbookListFinder_Expecter) FindByOwnerID(ctx interface{}, ownerID interface{}) *mockownedWorkbookListFinder_FindByOwnerID_Call {
	return &mockownedWorkbookListFinder_FindByOwnerID_Call{Call: _e.mock.On("FindByOwnerID", ctx, ownerID)}
}

func (_c *mockownedWorkbookListFinder_FindByOwnerID_Call) Run(run func(ctx context.Context, ownerID string)) *mockownedWorkbookListFinder_FindByOwnerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockownedWorkbookListFinder_FindByOwnerID_Call) Return(ownedWorkbookList *domain.OwnedWorkbookList, err error) *mockownedWorkbookListFinder_FindByOwnerID_Call {
	_c.Call.Return(ownedWorkbookList, err)
	return _c
}

func (_c *mockownedWorkbookListFinder_FindByOwnerID_Call) RunAndReturn(run func(ctx context.Context, ownerID string) (*domain.OwnedWorkbookList, error)) *mockownedWorkbookListFinder_FindByOwnerID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockownedWorkbookListSaver creates a new instance of mockownedWorkbookListSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockownedWorkbookListSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockownedWorkbookListSaver {
	mock := &mockownedWorkbookListSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockownedWorkbookListSaver is an autogenerated mock type for the ownedWorkbookListSaver type
type mockownedWorkbookListSaver struct {
	mock.Mock
}

type mockownedWorkbookListSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockownedWorkbookListSaver) EXPECT() *mockownedWorkbookListSaver_Expecter {
	return &mockownedWorkbookListSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type mockownedWorkbookListSaver
func (_mock *mockownedWorkbookListSaver) Save(ctx context.Context, list *domain.OwnedWorkbookList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.OwnedWorkbookList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockownedWorkbookListSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockownedWorkbookListSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *domain.OwnedWorkbookList
func (_e *mockownedWorkbookListSaver_Expecter) Save(ctx interface{}, list interface{}) *mockownedWorkbookListSaver_Save_Call {
	return &mockownedWorkbookListSaver_Save_Call{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *mockownedWorkbookListSaver_Save_Call) Run(run func(ctx context.Context, list *domain.OwnedWorkbookList)) *mockownedWorkbookListSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.OwnedWorkbookList
		if args[1] != nil {
			arg1 = args[1].(*domain.OwnedWorkbookList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockownedWorkbookListSaver_Save_Call) Return(err error) *mockownedWorkbookListSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockownedWorkbookListSaver_Save_Call) RunAndReturn(run func(ctx context.Context, list *domain.OwnedWorkbookList) error) *mockownedWorkbookListSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockmaxWorkbooksFetcher creates a new instance of mockmaxWorkbooksFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmaxWorkbooksFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmaxWorkbooksFetcher {
	mock := &mockmaxWorkbooksFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmaxWorkbooksFetcher is an autogenerated mock type for the maxWorkbooksFetcher type
type mockmaxWorkbooksFetcher struct {
	mock.Mock
}

type mockmaxWorkbooksFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmaxWorkbooksFetcher) EXPECT() *mockmaxWorkbooksFetcher_Expecter {
	return &mockmaxWorkbooksFetcher_Expecter{mock: &_m.Mock}
}

// FetchMaxWorkbooks provides a mock function for the type mockmaxWorkbooksFetcher
func (_mock *mockmaxWorkbooksFetcher) FetchMaxWorkbooks(ctx context.Context, userID string) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchMaxWorkbooks")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMaxWorkbooks'
type mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call struct {
	*mock.Call
}

// FetchMaxWorkbooks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockmaxWorkbooksFetcher_Expecter) FetchMaxWorkbooks(ctx interface{}, userID interface{}) *mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call {
	return &mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call{Call: _e.mock.On("FetchMaxWorkbooks", ctx, userID)}
}

func (_c *mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call) Run(run func(ctx context.Context, userID string)) *mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call) Return(n int, err error) *mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call) RunAndReturn(run func(ctx context.Context, userID string) (int, error)) *mockmaxWorkbooksFetcher_FetchMaxWorkbooks_Call {
	_c.Call.Return(run)
	return _c
}
