// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package event_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain/rbac"
	mock "github.com/stretchr/testify/mock"
)

// newMockactiveGroupListRepository creates a new instance of mockactiveGroupListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveGroupListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveGroupListRepository {
	mock := &mockactiveGroupListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveGroupListRepository is an autogenerated mock type for the activeGroupListRepository type
type mockactiveGroupListRepository struct {
	mock.Mock
}

type mockactiveGroupListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockactiveGroupListRepository) EXPECT() *mockactiveGroupListRepository_Expecter {
	return &mockactiveGroupListRepository_Expecter{mock: &_m.Mock}
}

// FindByOrganizationID provides a mock function for the type mockactiveGroupListRepository
func (_mock *mockactiveGroupListRepository) FindByOrganizationID(ctx context.Context, organizationID domain.OrganizationID) (*domain.ActiveGroupList, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrganizationID")
	}

	var r0 *domain.ActiveGroupList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) (*domain.ActiveGroupList, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) *domain.ActiveGroupList); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActiveGroupList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockactiveGroupListRepository_FindByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrganizationID'
type mockactiveGroupListRepository_FindByOrganizationID_Call struct {
	*mock.Call
}

// FindByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
func (_e *mockactiveGroupListRepository_Expecter) FindByOrganizationID(ctx interface{}, organizationID interface{}) *mockactiveGroupListRepository_FindByOrganizationID_Call {
	return &mockactiveGroupListRepository_FindByOrganizationID_Call{Call: _e.mock.On("FindByOrganizationID", ctx, organizationID)}
}

func (_c *mockactiveGroupListRepository_FindByOrganizationID_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID)) *mockactiveGroupListRepository_FindByOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveGroupListRepository_FindByOrganizationID_Call) Return(activeGroupList *domain.ActiveGroupList, err error) *mockactiveGroupListRepository_FindByOrganizationID_Call {
	_c.Call.Return(activeGroupList, err)
	return _c
}

func (_c *mockactiveGroupListRepository_FindByOrganizationID_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID) (*domain.ActiveGroupList, error)) *mockactiveGroupListRepository_FindByOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockactiveGroupListRepository
func (_mock *mockactiveGroupListRepository) Save(ctx context.Context, list *domain.ActiveGroupList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ActiveGroupList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockactiveGroupListRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockactiveGroupListRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *domain.ActiveGroupList
func (_e *mockactiveGroupListRepository_Expecter) Save(ctx interface{}, list interface{}) *mockactiveGroupListRepository_Save_Call {
	return &mockactiveGroupListRepository_Save_Call{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *mockactiveGroupListRepository_Save_Call) Run(run func(ctx context.Context, list *domain.ActiveGroupList)) *mockactiveGroupListRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ActiveGroupList
		if args[1] != nil {
			arg1 = args[1].(*domain.ActiveGroupList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveGroupListRepository_Save_Call) Return(err error) *mockactiveGroupListRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockactiveGroupListRepository_Save_Call) RunAndReturn(run func(ctx context.Context, list *domain.ActiveGroupList) error) *mockactiveGroupListRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockactiveList creates a new instance of mockactiveList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveList[T any, E any](t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveList[T, E] {
	mock := &mockactiveList[T, E]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveList is an autogenerated mock type for the activeList type
type mockactiveList[T any, E any] struct {
	mock.Mock
}

type mockactiveList_Expecter[T any, E any] struct {
	mock *mock.Mock
}

func (_m *mockactiveList[T, E]) EXPECT() *mockactiveList_Expecter[T, E] {
	return &mockactiveList_Expecter[T, E]{mock: &_m.Mock}
}

// Add provides a mock function for the type mockactiveList
func (_mock *mockactiveList[T, E]) Add(id E, limit int) error {
	ret := _mock.Called(id, limit)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(E, int) error); ok {
		r0 = returnFunc(id, limit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockactiveList_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type mockactiveList_Add_Call[T any, E any] struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - id E
//   - limit int
func (_e *mockactiveList_Expecter[T, E]) Add(id interface{}, limit interface{}) *mockactiveList_Add_Call[T, E] {
	return &mockactiveList_Add_Call[T, E]{Call: _e.mock.On("Add", id, limit)}
}

func (_c *mockactiveList_Add_Call[T, E]) Run(run func(id E, limit int)) *mockactiveList_Add_Call[T, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 E
		if args[0] != nil {
			arg0 = args[0].(E)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveList_Add_Call[T, E]) Return(err error) *mockactiveList_Add_Call[T, E] {
	_c.Call.Return(err)
	return _c
}

func (_c *mockactiveList_Add_Call[T, E]) RunAndReturn(run func(id E, limit int) error) *mockactiveList_Add_Call[T, E] {
	_c.Call.Return(run)
	return _c
}

// newMockactiveListRepo creates a new instance of mockactiveListRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveListRepo[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveListRepo[T] {
	mock := &mockactiveListRepo[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveListRepo is an autogenerated mock type for the activeListRepo type
type mockactiveListRepo[T any] struct {
	mock.Mock
}

type mockactiveListRepo_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *mockactiveListRepo[T]) EXPECT() *mockactiveListRepo_Expecter[T] {
	return &mockactiveListRepo_Expecter[T]{mock: &_m.Mock}
}

// FindByOrganizationID provides a mock function for the type mockactiveListRepo
func (_mock *mockactiveListRepo[T]) FindByOrganizationID(ctx context.Context, organizationID domain.OrganizationID) (*T, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrganizationID")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) (*T, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) *T); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockactiveListRepo_FindByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrganizationID'
type mockactiveListRepo_FindByOrganizationID_Call[T any] struct {
	*mock.Call
}

// FindByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
func (_e *mockactiveListRepo_Expecter[T]) FindByOrganizationID(ctx interface{}, organizationID interface{}) *mockactiveListRepo_FindByOrganizationID_Call[T] {
	return &mockactiveListRepo_FindByOrganizationID_Call[T]{Call: _e.mock.On("FindByOrganizationID", ctx, organizationID)}
}

func (_c *mockactiveListRepo_FindByOrganizationID_Call[T]) Run(run func(ctx context.Context, organizationID domain.OrganizationID)) *mockactiveListRepo_FindByOrganizationID_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveListRepo_FindByOrganizationID_Call[T]) Return(v *T, err error) *mockactiveListRepo_FindByOrganizationID_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mockactiveListRepo_FindByOrganizationID_Call[T]) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID) (*T, error)) *mockactiveListRepo_FindByOrganizationID_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockactiveListRepo
func (_mock *mockactiveListRepo[T]) Save(ctx context.Context, list *T) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockactiveListRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockactiveListRepo_Save_Call[T any] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *T
func (_e *mockactiveListRepo_Expecter[T]) Save(ctx interface{}, list interface{}) *mockactiveListRepo_Save_Call[T] {
	return &mockactiveListRepo_Save_Call[T]{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *mockactiveListRepo_Save_Call[T]) Run(run func(ctx context.Context, list *T)) *mockactiveListRepo_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *T
		if args[1] != nil {
			arg1 = args[1].(*T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveListRepo_Save_Call[T]) Return(err error) *mockactiveListRepo_Save_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *mockactiveListRepo_Save_Call[T]) RunAndReturn(run func(ctx context.Context, list *T) error) *mockactiveListRepo_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// newMockactiveUserListRepository creates a new instance of mockactiveUserListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveUserListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveUserListRepository {
	mock := &mockactiveUserListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveUserListRepository is an autogenerated mock type for the activeUserListRepository type
type mockactiveUserListRepository struct {
	mock.Mock
}

type mockactiveUserListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockactiveUserListRepository) EXPECT() *mockactiveUserListRepository_Expecter {
	return &mockactiveUserListRepository_Expecter{mock: &_m.Mock}
}

// FindByOrganizationID provides a mock function for the type mockactiveUserListRepository
func (_mock *mockactiveUserListRepository) FindByOrganizationID(ctx context.Context, organizationID domain.OrganizationID) (*domain.ActiveUserList, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrganizationID")
	}

	var r0 *domain.ActiveUserList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) (*domain.ActiveUserList, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) *domain.ActiveUserList); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActiveUserList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockactiveUserListRepository_FindByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrganizationID'
type mockactiveUserListRepository_FindByOrganizationID_Call struct {
	*mock.Call
}

// FindByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
func (_e *mockactiveUserListRepository_Expecter) FindByOrganizationID(ctx interface{}, organizationID interface{}) *mockactiveUserListRepository_FindByOrganizationID_Call {
	return &mockactiveUserListRepository_FindByOrganizationID_Call{Call: _e.mock.On("FindByOrganizationID", ctx, organizationID)}
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID)) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) Return(activeUserList *domain.ActiveUserList, err error) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Return(activeUserList, err)
	return _c
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID) (*domain.ActiveUserList, error)) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockactiveUserListRepository
func (_mock *mockactiveUserListRepository) Save(ctx context.Context, list *domain.ActiveUserList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ActiveUserList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockactiveUserListRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockactiveUserListRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *domain.ActiveUserList
func (_e *mockactiveUserListRepository_Expecter) Save(ctx interface{}, list interface{}) *mockactiveUserListRepository_Save_Call {
	return &mockactiveUserListRepository_Save_Call{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *mockactiveUserListRepository_Save_Call) Run(run func(ctx context.Context, list *domain.ActiveUserList)) *mockactiveUserListRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ActiveUserList
		if args[1] != nil {
			arg1 = args[1].(*domain.ActiveUserList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveUserListRepository_Save_Call) Return(err error) *mockactiveUserListRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockactiveUserListRepository_Save_Call) RunAndReturn(run func(ctx context.Context, list *domain.ActiveUserList) error) *mockactiveUserListRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockorganizationFinder creates a new instance of mockorganizationFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockorganizationFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockorganizationFinder {
	mock := &mockorganizationFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockorganizationFinder is an autogenerated mock type for the organizationFinder type
type mockorganizationFinder struct {
	mock.Mock
}

type mockorganizationFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockorganizationFinder) EXPECT() *mockorganizationFinder_Expecter {
	return &mockorganizationFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockorganizationFinder
func (_mock *mockorganizationFinder) FindByID(ctx context.Context, id domain.OrganizationID) (*domain.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) (*domain.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) *domain.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockorganizationFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockorganizationFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.OrganizationID
func (_e *mockorganizationFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockorganizationFinder_FindByID_Call {
	return &mockorganizationFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockorganizationFinder_FindByID_Call) Run(run func(ctx context.Context, id domain.OrganizationID)) *mockorganizationFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockorganizationFinder_FindByID_Call) Return(organization *domain.Organization, err error) *mockorganizationFinder_FindByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *mockorganizationFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id domain.OrganizationID) (*domain.Organization, error)) *mockorganizationFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockspaceCreator creates a new instance of mockspaceCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspaceCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspaceCreator {
	mock := &mockspaceCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockspaceCreator is an autogenerated mock type for the spaceCreator type
type mockspaceCreator struct {
	mock.Mock
}

type mockspaceCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspaceCreator) EXPECT() *mockspaceCreator_Expecter {
	return &mockspaceCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockspaceCreator
func (_mock *mockspaceCreator) Create(ctx context.Context, organizationID domain.OrganizationID, ownerID domain.AppUserID, keyName string, name string, spaceType string, createdBy domain.AppUserID) (domain.SpaceID, error) {
	ret := _mock.Called(ctx, organizationID, ownerID, keyName, name, spaceType, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.SpaceID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, domain.AppUserID, string, string, string, domain.AppUserID) (domain.SpaceID, error)); ok {
		return returnFunc(ctx, organizationID, ownerID, keyName, name, spaceType, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, domain.AppUserID, string, string, string, domain.AppUserID) domain.SpaceID); ok {
		r0 = returnFunc(ctx, organizationID, ownerID, keyName, name, spaceType, createdBy)
	} else {
		r0 = ret.Get(0).(domain.SpaceID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID, domain.AppUserID, string, string, string, domain.AppUserID) error); ok {
		r1 = returnFunc(ctx, organizationID, ownerID, keyName, name, spaceType, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockspaceCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockspaceCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
//   - ownerID domain.AppUserID
//   - keyName string
//   - name string
//   - spaceType string
//   - createdBy domain.AppUserID
func (_e *mockspaceCreator_Expecter) Create(ctx interface{}, organizationID interface{}, ownerID interface{}, keyName interface{}, name interface{}, spaceType interface{}, createdBy interface{}) *mockspaceCreator_Create_Call {
	return &mockspaceCreator_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, ownerID, keyName, name, spaceType, createdBy)}
}

func (_c *mockspaceCreator_Create_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID, ownerID domain.AppUserID, keyName string, name string, spaceType string, createdBy domain.AppUserID)) *mockspaceCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		var arg2 domain.AppUserID
		if args[2] != nil {
			arg2 = args[2].(domain.AppUserID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 domain.AppUserID
		if args[6] != nil {
			arg6 = args[6].(domain.AppUserID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *mockspaceCreator_Create_Call) Return(spaceID domain.SpaceID, err error) *mockspaceCreator_Create_Call {
	_c.Call.Return(spaceID, err)
	return _c
}

func (_c *mockspaceCreator_Create_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID, ownerID domain.AppUserID, keyName string, name string, spaceType string, createdBy domain.AppUserID) (domain.SpaceID, error)) *mockspaceCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockuserPolicyAdder creates a new instance of mockuserPolicyAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserPolicyAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserPolicyAdder {
	mock := &mockuserPolicyAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserPolicyAdder is an autogenerated mock type for the userPolicyAdder type
type mockuserPolicyAdder struct {
	mock.Mock
}

type mockuserPolicyAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserPolicyAdder) EXPECT() *mockuserPolicyAdder_Expecter {
	return &mockuserPolicyAdder_Expecter{mock: &_m.Mock}
}

// AddPolicyForUser provides a mock function for the type mockuserPolicyAdder
func (_mock *mockuserPolicyAdder) AddPolicyForUser(ctx context.Context, organizationID domain.OrganizationID, userID domain.AppUserID, action rbac.Action, resource rbac.Resource, effect rbac.Effect) error {
	ret := _mock.Called(ctx, organizationID, userID, action, resource, effect)

	if len(ret) == 0 {
		panic("no return value specified for AddPolicyForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, domain.AppUserID, rbac.Action, rbac.Resource, rbac.Effect) error); ok {
		r0 = returnFunc(ctx, organizationID, userID, action, resource, effect)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockuserPolicyAdder_AddPolicyForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPolicyForUser'
type mockuserPolicyAdder_AddPolicyForUser_Call struct {
	*mock.Call
}

// AddPolicyForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
//   - userID domain.AppUserID
//   - action rbac.Action
//   - resource rbac.Resource
//   - effect rbac.Effect
func (_e *mockuserPolicyAdder_Expecter) AddPolicyForUser(ctx interface{}, organizationID interface{}, userID interface{}, action interface{}, resource interface{}, effect interface{}) *mockuserPolicyAdder_AddPolicyForUser_Call {
	return &mockuserPolicyAdder_AddPolicyForUser_Call{Call: _e.mock.On("AddPolicyForUser", ctx, organizationID, userID, action, resource, effect)}
}

func (_c *mockuserPolicyAdder_AddPolicyForUser_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID, userID domain.AppUserID, action rbac.Action, resource rbac.Resource, effect rbac.Effect)) *mockuserPolicyAdder_AddPolicyForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		var arg2 domain.AppUserID
		if args[2] != nil {
			arg2 = args[2].(domain.AppUserID)
		}
		var arg3 rbac.Action
		if args[3] != nil {
			arg3 = args[3].(rbac.Action)
		}
		var arg4 rbac.Resource
		if args[4] != nil {
			arg4 = args[4].(rbac.Resource)
		}
		var arg5 rbac.Effect
		if args[5] != nil {
			arg5 = args[5].(rbac.Effect)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockuserPolicyAdder_AddPolicyForUser_Call) Return(err error) *mockuserPolicyAdder_AddPolicyForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockuserPolicyAdder_AddPolicyForUser_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID, userID domain.AppUserID, action rbac.Action, resource rbac.Resource, effect rbac.Effect) error) *mockuserPolicyAdder_AddPolicyForUser_Call {
	_c.Call.Return(run)
	return _c
}
