// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package event_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockactiveUserListRepository creates a new instance of mockactiveUserListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveUserListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveUserListRepository {
	mock := &mockactiveUserListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveUserListRepository is an autogenerated mock type for the activeUserListRepository type
type mockactiveUserListRepository struct {
	mock.Mock
}

type mockactiveUserListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockactiveUserListRepository) EXPECT() *mockactiveUserListRepository_Expecter {
	return &mockactiveUserListRepository_Expecter{mock: &_m.Mock}
}

// FindByOrganizationID provides a mock function for the type mockactiveUserListRepository
func (_mock *mockactiveUserListRepository) FindByOrganizationID(ctx context.Context, organizationID int) (*domain.ActiveUserList, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrganizationID")
	}

	var r0 *domain.ActiveUserList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.ActiveUserList, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.ActiveUserList); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActiveUserList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockactiveUserListRepository_FindByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrganizationID'
type mockactiveUserListRepository_FindByOrganizationID_Call struct {
	*mock.Call
}

// FindByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int
func (_e *mockactiveUserListRepository_Expecter) FindByOrganizationID(ctx interface{}, organizationID interface{}) *mockactiveUserListRepository_FindByOrganizationID_Call {
	return &mockactiveUserListRepository_FindByOrganizationID_Call{Call: _e.mock.On("FindByOrganizationID", ctx, organizationID)}
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) Run(run func(ctx context.Context, organizationID int)) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) Return(activeUserList *domain.ActiveUserList, err error) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Return(activeUserList, err)
	return _c
}

func (_c *mockactiveUserListRepository_FindByOrganizationID_Call) RunAndReturn(run func(ctx context.Context, organizationID int) (*domain.ActiveUserList, error)) *mockactiveUserListRepository_FindByOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockactiveUserListRepository
func (_mock *mockactiveUserListRepository) Save(ctx context.Context, list *domain.ActiveUserList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ActiveUserList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockactiveUserListRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockactiveUserListRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *domain.ActiveUserList
func (_e *mockactiveUserListRepository_Expecter) Save(ctx interface{}, list interface{}) *mockactiveUserListRepository_Save_Call {
	return &mockactiveUserListRepository_Save_Call{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *mockactiveUserListRepository_Save_Call) Run(run func(ctx context.Context, list *domain.ActiveUserList)) *mockactiveUserListRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ActiveUserList
		if args[1] != nil {
			arg1 = args[1].(*domain.ActiveUserList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveUserListRepository_Save_Call) Return(err error) *mockactiveUserListRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockactiveUserListRepository_Save_Call) RunAndReturn(run func(ctx context.Context, list *domain.ActiveUserList) error) *mockactiveUserListRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockorganizationFinder creates a new instance of mockorganizationFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockorganizationFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockorganizationFinder {
	mock := &mockorganizationFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockorganizationFinder is an autogenerated mock type for the organizationFinder type
type mockorganizationFinder struct {
	mock.Mock
}

type mockorganizationFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockorganizationFinder) EXPECT() *mockorganizationFinder_Expecter {
	return &mockorganizationFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockorganizationFinder
func (_mock *mockorganizationFinder) FindByID(ctx context.Context, id int) (*domain.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockorganizationFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockorganizationFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *mockorganizationFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockorganizationFinder_FindByID_Call {
	return &mockorganizationFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockorganizationFinder_FindByID_Call) Run(run func(ctx context.Context, id int)) *mockorganizationFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockorganizationFinder_FindByID_Call) Return(organization *domain.Organization, err error) *mockorganizationFinder_FindByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *mockorganizationFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*domain.Organization, error)) *mockorganizationFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
