// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authz_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain/rbac"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorizationChecker creates a new instance of MockAuthorizationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizationChecker {
	mock := &MockAuthorizationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorizationChecker is an autogenerated mock type for the AuthorizationChecker type
type MockAuthorizationChecker struct {
	mock.Mock
}

type MockAuthorizationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizationChecker) EXPECT() *MockAuthorizationChecker_Expecter {
	return &MockAuthorizationChecker_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type MockAuthorizationChecker
func (_mock *MockAuthorizationChecker) IsAllowed(ctx context.Context, organizationID domain.OrganizationID, operatorID domain.AppUserID, action rbac.Action, resource rbac.Resource) (bool, error) {
	ret := _mock.Called(ctx, organizationID, operatorID, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, domain.AppUserID, rbac.Action, rbac.Resource) (bool, error)); ok {
		return returnFunc(ctx, organizationID, operatorID, action, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, domain.AppUserID, rbac.Action, rbac.Resource) bool); ok {
		r0 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID, domain.AppUserID, rbac.Action, rbac.Resource) error); ok {
		r1 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthorizationChecker_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type MockAuthorizationChecker_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
//   - operatorID domain.AppUserID
//   - action rbac.Action
//   - resource rbac.Resource
func (_e *MockAuthorizationChecker_Expecter) IsAllowed(ctx interface{}, organizationID interface{}, operatorID interface{}, action interface{}, resource interface{}) *MockAuthorizationChecker_IsAllowed_Call {
	return &MockAuthorizationChecker_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, organizationID, operatorID, action, resource)}
}

func (_c *MockAuthorizationChecker_IsAllowed_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID, operatorID domain.AppUserID, action rbac.Action, resource rbac.Resource)) *MockAuthorizationChecker_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		var arg2 domain.AppUserID
		if args[2] != nil {
			arg2 = args[2].(domain.AppUserID)
		}
		var arg3 rbac.Action
		if args[3] != nil {
			arg3 = args[3].(rbac.Action)
		}
		var arg4 rbac.Resource
		if args[4] != nil {
			arg4 = args[4].(rbac.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthorizationChecker_IsAllowed_Call) Return(b bool, err error) *MockAuthorizationChecker_IsAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuthorizationChecker_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID, operatorID domain.AppUserID, action rbac.Action, resource rbac.Resource) (bool, error)) *MockAuthorizationChecker_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}
