// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package study_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/service/study"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetStudyQuestionsUsecase creates a new instance of MockGetStudyQuestionsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetStudyQuestionsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetStudyQuestionsUsecase {
	mock := &MockGetStudyQuestionsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetStudyQuestionsUsecase is an autogenerated mock type for the GetStudyQuestionsUsecase type
type MockGetStudyQuestionsUsecase struct {
	mock.Mock
}

type MockGetStudyQuestionsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetStudyQuestionsUsecase) EXPECT() *MockGetStudyQuestionsUsecase_Expecter {
	return &MockGetStudyQuestionsUsecase_Expecter{mock: &_m.Mock}
}

// GetStudyQuestions provides a mock function for the type MockGetStudyQuestionsUsecase
func (_mock *MockGetStudyQuestionsUsecase) GetStudyQuestions(ctx context.Context, input *study.GetStudyQuestionsInput) (*study.GetStudyQuestionsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetStudyQuestions")
	}

	var r0 *study.GetStudyQuestionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *study.GetStudyQuestionsInput) (*study.GetStudyQuestionsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *study.GetStudyQuestionsInput) *study.GetStudyQuestionsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*study.GetStudyQuestionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *study.GetStudyQuestionsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetStudyQuestionsUsecase_GetStudyQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudyQuestions'
type MockGetStudyQuestionsUsecase_GetStudyQuestions_Call struct {
	*mock.Call
}

// GetStudyQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - input *study.GetStudyQuestionsInput
func (_e *MockGetStudyQuestionsUsecase_Expecter) GetStudyQuestions(ctx interface{}, input interface{}) *MockGetStudyQuestionsUsecase_GetStudyQuestions_Call {
	return &MockGetStudyQuestionsUsecase_GetStudyQuestions_Call{Call: _e.mock.On("GetStudyQuestions", ctx, input)}
}

func (_c *MockGetStudyQuestionsUsecase_GetStudyQuestions_Call) Run(run func(ctx context.Context, input *study.GetStudyQuestionsInput)) *MockGetStudyQuestionsUsecase_GetStudyQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *study.GetStudyQuestionsInput
		if args[1] != nil {
			arg1 = args[1].(*study.GetStudyQuestionsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetStudyQuestionsUsecase_GetStudyQuestions_Call) Return(getStudyQuestionsOutput *study.GetStudyQuestionsOutput, err error) *MockGetStudyQuestionsUsecase_GetStudyQuestions_Call {
	_c.Call.Return(getStudyQuestionsOutput, err)
	return _c
}

func (_c *MockGetStudyQuestionsUsecase_GetStudyQuestions_Call) RunAndReturn(run func(ctx context.Context, input *study.GetStudyQuestionsInput) (*study.GetStudyQuestionsOutput, error)) *MockGetStudyQuestionsUsecase_GetStudyQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecordAnswerUsecase creates a new instance of MockRecordAnswerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordAnswerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordAnswerUsecase {
	mock := &MockRecordAnswerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecordAnswerUsecase is an autogenerated mock type for the RecordAnswerUsecase type
type MockRecordAnswerUsecase struct {
	mock.Mock
}

type MockRecordAnswerUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordAnswerUsecase) EXPECT() *MockRecordAnswerUsecase_Expecter {
	return &MockRecordAnswerUsecase_Expecter{mock: &_m.Mock}
}

// RecordAnswer provides a mock function for the type MockRecordAnswerUsecase
func (_mock *MockRecordAnswerUsecase) RecordAnswer(ctx context.Context, input *study.RecordAnswerInput) (*study.RecordAnswerOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RecordAnswer")
	}

	var r0 *study.RecordAnswerOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *study.RecordAnswerInput) (*study.RecordAnswerOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *study.RecordAnswerInput) *study.RecordAnswerOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*study.RecordAnswerOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *study.RecordAnswerInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRecordAnswerUsecase_RecordAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAnswer'
type MockRecordAnswerUsecase_RecordAnswer_Call struct {
	*mock.Call
}

// RecordAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - input *study.RecordAnswerInput
func (_e *MockRecordAnswerUsecase_Expecter) RecordAnswer(ctx interface{}, input interface{}) *MockRecordAnswerUsecase_RecordAnswer_Call {
	return &MockRecordAnswerUsecase_RecordAnswer_Call{Call: _e.mock.On("RecordAnswer", ctx, input)}
}

func (_c *MockRecordAnswerUsecase_RecordAnswer_Call) Run(run func(ctx context.Context, input *study.RecordAnswerInput)) *MockRecordAnswerUsecase_RecordAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *study.RecordAnswerInput
		if args[1] != nil {
			arg1 = args[1].(*study.RecordAnswerInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecordAnswerUsecase_RecordAnswer_Call) Return(recordAnswerOutput *study.RecordAnswerOutput, err error) *MockRecordAnswerUsecase_RecordAnswer_Call {
	_c.Call.Return(recordAnswerOutput, err)
	return _c
}

func (_c *MockRecordAnswerUsecase_RecordAnswer_Call) RunAndReturn(run func(ctx context.Context, input *study.RecordAnswerInput) (*study.RecordAnswerOutput, error)) *MockRecordAnswerUsecase_RecordAnswer_Call {
	_c.Call.Return(run)
	return _c
}
