// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package importer_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-init/seed"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublicSpaceFinder creates a new instance of MockPublicSpaceFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublicSpaceFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublicSpaceFinder {
	mock := &MockPublicSpaceFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublicSpaceFinder is an autogenerated mock type for the PublicSpaceFinder type
type MockPublicSpaceFinder struct {
	mock.Mock
}

type MockPublicSpaceFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublicSpaceFinder) EXPECT() *MockPublicSpaceFinder_Expecter {
	return &MockPublicSpaceFinder_Expecter{mock: &_m.Mock}
}

// FindPublicSpaceID provides a mock function for the type MockPublicSpaceFinder
func (_mock *MockPublicSpaceFinder) FindPublicSpaceID(ctx context.Context, organizationID domain.OrganizationID) (domain.SpaceID, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindPublicSpaceID")
	}

	var r0 domain.SpaceID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) (domain.SpaceID, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) domain.SpaceID); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		r0 = ret.Get(0).(domain.SpaceID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublicSpaceFinder_FindPublicSpaceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPublicSpaceID'
type MockPublicSpaceFinder_FindPublicSpaceID_Call struct {
	*mock.Call
}

// FindPublicSpaceID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID domain.OrganizationID
func (_e *MockPublicSpaceFinder_Expecter) FindPublicSpaceID(ctx interface{}, organizationID interface{}) *MockPublicSpaceFinder_FindPublicSpaceID_Call {
	return &MockPublicSpaceFinder_FindPublicSpaceID_Call{Call: _e.mock.On("FindPublicSpaceID", ctx, organizationID)}
}

func (_c *MockPublicSpaceFinder_FindPublicSpaceID_Call) Run(run func(ctx context.Context, organizationID domain.OrganizationID)) *MockPublicSpaceFinder_FindPublicSpaceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublicSpaceFinder_FindPublicSpaceID_Call) Return(spaceID domain.SpaceID, err error) *MockPublicSpaceFinder_FindPublicSpaceID_Call {
	_c.Call.Return(spaceID, err)
	return _c
}

func (_c *MockPublicSpaceFinder_FindPublicSpaceID_Call) RunAndReturn(run func(ctx context.Context, organizationID domain.OrganizationID) (domain.SpaceID, error)) *MockPublicSpaceFinder_FindPublicSpaceID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCSVWorkbookLoader creates a new instance of MockCSVWorkbookLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCSVWorkbookLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCSVWorkbookLoader {
	mock := &MockCSVWorkbookLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCSVWorkbookLoader is an autogenerated mock type for the CSVWorkbookLoader type
type MockCSVWorkbookLoader struct {
	mock.Mock
}

type MockCSVWorkbookLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCSVWorkbookLoader) EXPECT() *MockCSVWorkbookLoader_Expecter {
	return &MockCSVWorkbookLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockCSVWorkbookLoader
func (_mock *MockCSVWorkbookLoader) Load(ctx context.Context) ([]seed.CSVWorkbookSeed, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []seed.CSVWorkbookSeed
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]seed.CSVWorkbookSeed, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []seed.CSVWorkbookSeed); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]seed.CSVWorkbookSeed)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCSVWorkbookLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockCSVWorkbookLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCSVWorkbookLoader_Expecter) Load(ctx interface{}) *MockCSVWorkbookLoader_Load_Call {
	return &MockCSVWorkbookLoader_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockCSVWorkbookLoader_Load_Call) Run(run func(ctx context.Context)) *MockCSVWorkbookLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCSVWorkbookLoader_Load_Call) Return(cSVWorkbookSeeds []seed.CSVWorkbookSeed, err error) *MockCSVWorkbookLoader_Load_Call {
	_c.Call.Return(cSVWorkbookSeeds, err)
	return _c
}

func (_c *MockCSVWorkbookLoader_Load_Call) RunAndReturn(run func(ctx context.Context) ([]seed.CSVWorkbookSeed, error)) *MockCSVWorkbookLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkbookSeeder creates a new instance of MockWorkbookSeeder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkbookSeeder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkbookSeeder {
	mock := &MockWorkbookSeeder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkbookSeeder is an autogenerated mock type for the WorkbookSeeder type
type MockWorkbookSeeder struct {
	mock.Mock
}

type MockWorkbookSeeder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkbookSeeder) EXPECT() *MockWorkbookSeeder_Expecter {
	return &MockWorkbookSeeder_Expecter{mock: &_m.Mock}
}

// SeedWorkbooks provides a mock function for the type MockWorkbookSeeder
func (_mock *MockWorkbookSeeder) SeedWorkbooks(ctx context.Context, organizationID string, publicSpaceID string, seeds []seed.PublicWorkbookSeed) ([]seed.WorkbookOutput, error) {
	ret := _mock.Called(ctx, organizationID, publicSpaceID, seeds)

	if len(ret) == 0 {
		panic("no return value specified for SeedWorkbooks")
	}

	var r0 []seed.WorkbookOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []seed.PublicWorkbookSeed) ([]seed.WorkbookOutput, error)); ok {
		return returnFunc(ctx, organizationID, publicSpaceID, seeds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []seed.PublicWorkbookSeed) []seed.WorkbookOutput); ok {
		r0 = returnFunc(ctx, organizationID, publicSpaceID, seeds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]seed.WorkbookOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []seed.PublicWorkbookSeed) error); ok {
		r1 = returnFunc(ctx, organizationID, publicSpaceID, seeds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkbookSeeder_SeedWorkbooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedWorkbooks'
type MockWorkbookSeeder_SeedWorkbooks_Call struct {
	*mock.Call
}

// SeedWorkbooks is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - publicSpaceID string
//   - seeds []seed.PublicWorkbookSeed
func (_e *MockWorkbookSeeder_Expecter) SeedWorkbooks(ctx interface{}, organizationID interface{}, publicSpaceID interface{}, seeds interface{}) *MockWorkbookSeeder_SeedWorkbooks_Call {
	return &MockWorkbookSeeder_SeedWorkbooks_Call{Call: _e.mock.On("SeedWorkbooks", ctx, organizationID, publicSpaceID, seeds)}
}

func (_c *MockWorkbookSeeder_SeedWorkbooks_Call) Run(run func(ctx context.Context, organizationID string, publicSpaceID string, seeds []seed.PublicWorkbookSeed)) *MockWorkbookSeeder_SeedWorkbooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []seed.PublicWorkbookSeed
		if args[3] != nil {
			arg3 = args[3].([]seed.PublicWorkbookSeed)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWorkbookSeeder_SeedWorkbooks_Call) Return(workbookOutputs []seed.WorkbookOutput, err error) *MockWorkbookSeeder_SeedWorkbooks_Call {
	_c.Call.Return(workbookOutputs, err)
	return _c
}

func (_c *MockWorkbookSeeder_SeedWorkbooks_Call) RunAndReturn(run func(ctx context.Context, organizationID string, publicSpaceID string, seeds []seed.PublicWorkbookSeed) ([]seed.WorkbookOutput, error)) *MockWorkbookSeeder_SeedWorkbooks_Call {
	_c.Call.Return(run)
	return _c
}
