// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package study_test

import (
	"context"
	"time"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/question"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/study"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/workbook"
	mock "github.com/stretchr/testify/mock"
)

// newMockquestionRepository creates a new instance of mockquestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionRepository {
	mock := &mockquestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionRepository is an autogenerated mock type for the questionRepository type
type mockquestionRepository struct {
	mock.Mock
}

type mockquestionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionRepository) EXPECT() *mockquestionRepository_Expecter {
	return &mockquestionRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockquestionRepository
func (_mock *mockquestionRepository) FindByID(ctx context.Context, workbookID string, questionID string) (*question.Question, error) {
	ret := _mock.Called(ctx, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*question.Question, error)); ok {
		return returnFunc(ctx, workbookID, questionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *question.Question); ok {
		r0 = returnFunc(ctx, workbookID, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workbookID, questionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockquestionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionID string
func (_e *mockquestionRepository_Expecter) FindByID(ctx interface{}, workbookID interface{}, questionID interface{}) *mockquestionRepository_FindByID_Call {
	return &mockquestionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, workbookID, questionID)}
}

func (_c *mockquestionRepository_FindByID_Call) Run(run func(ctx context.Context, workbookID string, questionID string)) *mockquestionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionRepository_FindByID_Call) Return(question1 *question.Question, err error) *mockquestionRepository_FindByID_Call {
	_c.Call.Return(question1, err)
	return _c
}

func (_c *mockquestionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionID string) (*question.Question, error)) *mockquestionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function for the type mockquestionRepository
func (_mock *mockquestionRepository) FindByIDs(ctx context.Context, workbookID string, questionIDs []string) ([]question.Question, error) {
	ret := _mock.Called(ctx, workbookID, questionIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]question.Question, error)); ok {
		return returnFunc(ctx, workbookID, questionIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []question.Question); ok {
		r0 = returnFunc(ctx, workbookID, questionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, workbookID, questionIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type mockquestionRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionIDs []string
func (_e *mockquestionRepository_Expecter) FindByIDs(ctx interface{}, workbookID interface{}, questionIDs interface{}) *mockquestionRepository_FindByIDs_Call {
	return &mockquestionRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, workbookID, questionIDs)}
}

func (_c *mockquestionRepository_FindByIDs_Call) Run(run func(ctx context.Context, workbookID string, questionIDs []string)) *mockquestionRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionRepository_FindByIDs_Call) Return(questions []question.Question, err error) *mockquestionRepository_FindByIDs_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *mockquestionRepository_FindByIDs_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionIDs []string) ([]question.Question, error)) *mockquestionRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstudyRecordRepository creates a new instance of mockstudyRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstudyRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstudyRecordRepository {
	mock := &mockstudyRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstudyRecordRepository is an autogenerated mock type for the studyRecordRepository type
type mockstudyRecordRepository struct {
	mock.Mock
}

type mockstudyRecordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstudyRecordRepository) EXPECT() *mockstudyRecordRepository_Expecter {
	return &mockstudyRecordRepository_Expecter{mock: &_m.Mock}
}

// DeleteByWorkbookID provides a mock function for the type mockstudyRecordRepository
func (_mock *mockstudyRecordRepository) DeleteByWorkbookID(ctx context.Context, userID string, workbookID string) error {
	ret := _mock.Called(ctx, userID, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByWorkbookID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, workbookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstudyRecordRepository_DeleteByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByWorkbookID'
type mockstudyRecordRepository_DeleteByWorkbookID_Call struct {
	*mock.Call
}

// DeleteByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - workbookID string
func (_e *mockstudyRecordRepository_Expecter) DeleteByWorkbookID(ctx interface{}, userID interface{}, workbookID interface{}) *mockstudyRecordRepository_DeleteByWorkbookID_Call {
	return &mockstudyRecordRepository_DeleteByWorkbookID_Call{Call: _e.mock.On("DeleteByWorkbookID", ctx, userID, workbookID)}
}

func (_c *mockstudyRecordRepository_DeleteByWorkbookID_Call) Run(run func(ctx context.Context, userID string, workbookID string)) *mockstudyRecordRepository_DeleteByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockstudyRecordRepository_DeleteByWorkbookID_Call) Return(err error) *mockstudyRecordRepository_DeleteByWorkbookID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstudyRecordRepository_DeleteByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, userID string, workbookID string) error) *mockstudyRecordRepository_DeleteByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type mockstudyRecordRepository
func (_mock *mockstudyRecordRepository) FindByID(ctx context.Context, userID string, workbookID string, questionID string) (*study.Record, error) {
	ret := _mock.Called(ctx, userID, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *study.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*study.Record, error)); ok {
		return returnFunc(ctx, userID, workbookID, questionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *study.Record); ok {
		r0 = returnFunc(ctx, userID, workbookID, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*study.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, workbookID, questionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstudyRecordRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockstudyRecordRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - workbookID string
//   - questionID string
func (_e *mockstudyRecordRepository_Expecter) FindByID(ctx interface{}, userID interface{}, workbookID interface{}, questionID interface{}) *mockstudyRecordRepository_FindByID_Call {
	return &mockstudyRecordRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, workbookID, questionID)}
}

func (_c *mockstudyRecordRepository_FindByID_Call) Run(run func(ctx context.Context, userID string, workbookID string, questionID string)) *mockstudyRecordRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockstudyRecordRepository_FindByID_Call) Return(record *study.Record, err error) *mockstudyRecordRepository_FindByID_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *mockstudyRecordRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID string, workbookID string, questionID string) (*study.Record, error)) *mockstudyRecordRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByWorkbookID provides a mock function for the type mockstudyRecordRepository
func (_mock *mockstudyRecordRepository) FindByWorkbookID(ctx context.Context, userID string, workbookID string) ([]study.Record, error) {
	ret := _mock.Called(ctx, userID, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkbookID")
	}

	var r0 []study.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]study.Record, error)); ok {
		return returnFunc(ctx, userID, workbookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []study.Record); ok {
		r0 = returnFunc(ctx, userID, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]study.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, workbookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstudyRecordRepository_FindByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWorkbookID'
type mockstudyRecordRepository_FindByWorkbookID_Call struct {
	*mock.Call
}

// FindByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - workbookID string
func (_e *mockstudyRecordRepository_Expecter) FindByWorkbookID(ctx interface{}, userID interface{}, workbookID interface{}) *mockstudyRecordRepository_FindByWorkbookID_Call {
	return &mockstudyRecordRepository_FindByWorkbookID_Call{Call: _e.mock.On("FindByWorkbookID", ctx, userID, workbookID)}
}

func (_c *mockstudyRecordRepository_FindByWorkbookID_Call) Run(run func(ctx context.Context, userID string, workbookID string)) *mockstudyRecordRepository_FindByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockstudyRecordRepository_FindByWorkbookID_Call) Return(records []study.Record, err error) *mockstudyRecordRepository_FindByWorkbookID_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *mockstudyRecordRepository_FindByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, userID string, workbookID string) ([]study.Record, error)) *mockstudyRecordRepository_FindByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockstudyRecordRepository
func (_mock *mockstudyRecordRepository) Save(ctx context.Context, userID string, record *study.Record) error {
	ret := _mock.Called(ctx, userID, record)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *study.Record) error); ok {
		r0 = returnFunc(ctx, userID, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstudyRecordRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockstudyRecordRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - record *study.Record
func (_e *mockstudyRecordRepository_Expecter) Save(ctx interface{}, userID interface{}, record interface{}) *mockstudyRecordRepository_Save_Call {
	return &mockstudyRecordRepository_Save_Call{Call: _e.mock.On("Save", ctx, userID, record)}
}

func (_c *mockstudyRecordRepository_Save_Call) Run(run func(ctx context.Context, userID string, record *study.Record)) *mockstudyRecordRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *study.Record
		if args[2] != nil {
			arg2 = args[2].(*study.Record)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockstudyRecordRepository_Save_Call) Return(err error) *mockstudyRecordRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstudyRecordRepository_Save_Call) RunAndReturn(run func(ctx context.Context, userID string, record *study.Record) error) *mockstudyRecordRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdailyStatsRepository creates a new instance of mockdailyStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdailyStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdailyStatsRepository {
	mock := &mockdailyStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdailyStatsRepository is an autogenerated mock type for the dailyStatsRepository type
type mockdailyStatsRepository struct {
	mock.Mock
}

type mockdailyStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdailyStatsRepository) EXPECT() *mockdailyStatsRepository_Expecter {
	return &mockdailyStatsRepository_Expecter{mock: &_m.Mock}
}

// FindRange provides a mock function for the type mockdailyStatsRepository
func (_mock *mockdailyStatsRepository) FindRange(ctx context.Context, userID string, fromDateKey string, toDateKey string) ([]study.DailyStat, error) {
	ret := _mock.Called(ctx, userID, fromDateKey, toDateKey)

	if len(ret) == 0 {
		panic("no return value specified for FindRange")
	}

	var r0 []study.DailyStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]study.DailyStat, error)); ok {
		return returnFunc(ctx, userID, fromDateKey, toDateKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []study.DailyStat); ok {
		r0 = returnFunc(ctx, userID, fromDateKey, toDateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]study.DailyStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, fromDateKey, toDateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdailyStatsRepository_FindRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRange'
type mockdailyStatsRepository_FindRange_Call struct {
	*mock.Call
}

// FindRange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - fromDateKey string
//   - toDateKey string
func (_e *mockdailyStatsRepository_Expecter) FindRange(ctx interface{}, userID interface{}, fromDateKey interface{}, toDateKey interface{}) *mockdailyStatsRepository_FindRange_Call {
	return &mockdailyStatsRepository_FindRange_Call{Call: _e.mock.On("FindRange", ctx, userID, fromDateKey, toDateKey)}
}

func (_c *mockdailyStatsRepository_FindRange_Call) Run(run func(ctx context.Context, userID string, fromDateKey string, toDateKey string)) *mockdailyStatsRepository_FindRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockdailyStatsRepository_FindRange_Call) Return(dailyStats []study.DailyStat, err error) *mockdailyStatsRepository_FindRange_Call {
	_c.Call.Return(dailyStats, err)
	return _c
}

func (_c *mockdailyStatsRepository_FindRange_Call) RunAndReturn(run func(ctx context.Context, userID string, fromDateKey string, toDateKey string) ([]study.DailyStat, error)) *mockdailyStatsRepository_FindRange_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementToday provides a mock function for the type mockdailyStatsRepository
func (_mock *mockdailyStatsRepository) IncrementToday(ctx context.Context, userID string, dateKey string, timezone string, correct bool, now time.Time) error {
	ret := _mock.Called(ctx, userID, dateKey, timezone, correct, now)

	if len(ret) == 0 {
		panic("no return value specified for IncrementToday")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, dateKey, timezone, correct, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdailyStatsRepository_IncrementToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementToday'
type mockdailyStatsRepository_IncrementToday_Call struct {
	*mock.Call
}

// IncrementToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - dateKey string
//   - timezone string
//   - correct bool
//   - now time.Time
func (_e *mockdailyStatsRepository_Expecter) IncrementToday(ctx interface{}, userID interface{}, dateKey interface{}, timezone interface{}, correct interface{}, now interface{}) *mockdailyStatsRepository_IncrementToday_Call {
	return &mockdailyStatsRepository_IncrementToday_Call{Call: _e.mock.On("IncrementToday", ctx, userID, dateKey, timezone, correct, now)}
}

func (_c *mockdailyStatsRepository_IncrementToday_Call) Run(run func(ctx context.Context, userID string, dateKey string, timezone string, correct bool, now time.Time)) *mockdailyStatsRepository_IncrementToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockdailyStatsRepository_IncrementToday_Call) Return(err error) *mockdailyStatsRepository_IncrementToday_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdailyStatsRepository_IncrementToday_Call) RunAndReturn(run func(ctx context.Context, userID string, dateKey string, timezone string, correct bool, now time.Time) error) *mockdailyStatsRepository_IncrementToday_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstudyRecordFinder creates a new instance of mockstudyRecordFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstudyRecordFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstudyRecordFinder {
	mock := &mockstudyRecordFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstudyRecordFinder is an autogenerated mock type for the studyRecordFinder type
type mockstudyRecordFinder struct {
	mock.Mock
}

type mockstudyRecordFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstudyRecordFinder) EXPECT() *mockstudyRecordFinder_Expecter {
	return &mockstudyRecordFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockstudyRecordFinder
func (_mock *mockstudyRecordFinder) FindByID(ctx context.Context, userID string, workbookID string, questionID string) (*study.Record, error) {
	ret := _mock.Called(ctx, userID, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *study.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*study.Record, error)); ok {
		return returnFunc(ctx, userID, workbookID, questionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *study.Record); ok {
		r0 = returnFunc(ctx, userID, workbookID, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*study.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, workbookID, questionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstudyRecordFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockstudyRecordFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - workbookID string
//   - questionID string
func (_e *mockstudyRecordFinder_Expecter) FindByID(ctx interface{}, userID interface{}, workbookID interface{}, questionID interface{}) *mockstudyRecordFinder_FindByID_Call {
	return &mockstudyRecordFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID, workbookID, questionID)}
}

func (_c *mockstudyRecordFinder_FindByID_Call) Run(run func(ctx context.Context, userID string, workbookID string, questionID string)) *mockstudyRecordFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockstudyRecordFinder_FindByID_Call) Return(record *study.Record, err error) *mockstudyRecordFinder_FindByID_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *mockstudyRecordFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID string, workbookID string, questionID string) (*study.Record, error)) *mockstudyRecordFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByWorkbookID provides a mock function for the type mockstudyRecordFinder
func (_mock *mockstudyRecordFinder) FindByWorkbookID(ctx context.Context, userID string, workbookID string) ([]study.Record, error) {
	ret := _mock.Called(ctx, userID, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkbookID")
	}

	var r0 []study.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]study.Record, error)); ok {
		return returnFunc(ctx, userID, workbookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []study.Record); ok {
		r0 = returnFunc(ctx, userID, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]study.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, workbookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstudyRecordFinder_FindByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWorkbookID'
type mockstudyRecordFinder_FindByWorkbookID_Call struct {
	*mock.Call
}

// FindByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - workbookID string
func (_e *mockstudyRecordFinder_Expecter) FindByWorkbookID(ctx interface{}, userID interface{}, workbookID interface{}) *mockstudyRecordFinder_FindByWorkbookID_Call {
	return &mockstudyRecordFinder_FindByWorkbookID_Call{Call: _e.mock.On("FindByWorkbookID", ctx, userID, workbookID)}
}

func (_c *mockstudyRecordFinder_FindByWorkbookID_Call) Run(run func(ctx context.Context, userID string, workbookID string)) *mockstudyRecordFinder_FindByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockstudyRecordFinder_FindByWorkbookID_Call) Return(records []study.Record, err error) *mockstudyRecordFinder_FindByWorkbookID_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *mockstudyRecordFinder_FindByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, userID string, workbookID string) ([]study.Record, error)) *mockstudyRecordFinder_FindByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstudyRecordSaver creates a new instance of mockstudyRecordSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstudyRecordSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstudyRecordSaver {
	mock := &mockstudyRecordSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstudyRecordSaver is an autogenerated mock type for the studyRecordSaver type
type mockstudyRecordSaver struct {
	mock.Mock
}

type mockstudyRecordSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstudyRecordSaver) EXPECT() *mockstudyRecordSaver_Expecter {
	return &mockstudyRecordSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type mockstudyRecordSaver
func (_mock *mockstudyRecordSaver) Save(ctx context.Context, userID string, record *study.Record) error {
	ret := _mock.Called(ctx, userID, record)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *study.Record) error); ok {
		r0 = returnFunc(ctx, userID, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstudyRecordSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockstudyRecordSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - record *study.Record
func (_e *mockstudyRecordSaver_Expecter) Save(ctx interface{}, userID interface{}, record interface{}) *mockstudyRecordSaver_Save_Call {
	return &mockstudyRecordSaver_Save_Call{Call: _e.mock.On("Save", ctx, userID, record)}
}

func (_c *mockstudyRecordSaver_Save_Call) Run(run func(ctx context.Context, userID string, record *study.Record)) *mockstudyRecordSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *study.Record
		if args[2] != nil {
			arg2 = args[2].(*study.Record)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockstudyRecordSaver_Save_Call) Return(err error) *mockstudyRecordSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstudyRecordSaver_Save_Call) RunAndReturn(run func(ctx context.Context, userID string, record *study.Record) error) *mockstudyRecordSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstudyRecordDeleter creates a new instance of mockstudyRecordDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstudyRecordDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstudyRecordDeleter {
	mock := &mockstudyRecordDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstudyRecordDeleter is an autogenerated mock type for the studyRecordDeleter type
type mockstudyRecordDeleter struct {
	mock.Mock
}

type mockstudyRecordDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstudyRecordDeleter) EXPECT() *mockstudyRecordDeleter_Expecter {
	return &mockstudyRecordDeleter_Expecter{mock: &_m.Mock}
}

// DeleteByWorkbookID provides a mock function for the type mockstudyRecordDeleter
func (_mock *mockstudyRecordDeleter) DeleteByWorkbookID(ctx context.Context, userID string, workbookID string) error {
	ret := _mock.Called(ctx, userID, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByWorkbookID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, workbookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstudyRecordDeleter_DeleteByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByWorkbookID'
type mockstudyRecordDeleter_DeleteByWorkbookID_Call struct {
	*mock.Call
}

// DeleteByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - workbookID string
func (_e *mockstudyRecordDeleter_Expecter) DeleteByWorkbookID(ctx interface{}, userID interface{}, workbookID interface{}) *mockstudyRecordDeleter_DeleteByWorkbookID_Call {
	return &mockstudyRecordDeleter_DeleteByWorkbookID_Call{Call: _e.mock.On("DeleteByWorkbookID", ctx, userID, workbookID)}
}

func (_c *mockstudyRecordDeleter_DeleteByWorkbookID_Call) Run(run func(ctx context.Context, userID string, workbookID string)) *mockstudyRecordDeleter_DeleteByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockstudyRecordDeleter_DeleteByWorkbookID_Call) Return(err error) *mockstudyRecordDeleter_DeleteByWorkbookID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstudyRecordDeleter_DeleteByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, userID string, workbookID string) error) *mockstudyRecordDeleter_DeleteByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdailyStatsIncrementer creates a new instance of mockdailyStatsIncrementer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdailyStatsIncrementer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdailyStatsIncrementer {
	mock := &mockdailyStatsIncrementer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdailyStatsIncrementer is an autogenerated mock type for the dailyStatsIncrementer type
type mockdailyStatsIncrementer struct {
	mock.Mock
}

type mockdailyStatsIncrementer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdailyStatsIncrementer) EXPECT() *mockdailyStatsIncrementer_Expecter {
	return &mockdailyStatsIncrementer_Expecter{mock: &_m.Mock}
}

// IncrementToday provides a mock function for the type mockdailyStatsIncrementer
func (_mock *mockdailyStatsIncrementer) IncrementToday(ctx context.Context, userID string, dateKey string, timezone string, correct bool, now time.Time) error {
	ret := _mock.Called(ctx, userID, dateKey, timezone, correct, now)

	if len(ret) == 0 {
		panic("no return value specified for IncrementToday")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, dateKey, timezone, correct, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdailyStatsIncrementer_IncrementToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementToday'
type mockdailyStatsIncrementer_IncrementToday_Call struct {
	*mock.Call
}

// IncrementToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - dateKey string
//   - timezone string
//   - correct bool
//   - now time.Time
func (_e *mockdailyStatsIncrementer_Expecter) IncrementToday(ctx interface{}, userID interface{}, dateKey interface{}, timezone interface{}, correct interface{}, now interface{}) *mockdailyStatsIncrementer_IncrementToday_Call {
	return &mockdailyStatsIncrementer_IncrementToday_Call{Call: _e.mock.On("IncrementToday", ctx, userID, dateKey, timezone, correct, now)}
}

func (_c *mockdailyStatsIncrementer_IncrementToday_Call) Run(run func(ctx context.Context, userID string, dateKey string, timezone string, correct bool, now time.Time)) *mockdailyStatsIncrementer_IncrementToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockdailyStatsIncrementer_IncrementToday_Call) Return(err error) *mockdailyStatsIncrementer_IncrementToday_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdailyStatsIncrementer_IncrementToday_Call) RunAndReturn(run func(ctx context.Context, userID string, dateKey string, timezone string, correct bool, now time.Time) error) *mockdailyStatsIncrementer_IncrementToday_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdailyStatsFinder creates a new instance of mockdailyStatsFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdailyStatsFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdailyStatsFinder {
	mock := &mockdailyStatsFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdailyStatsFinder is an autogenerated mock type for the dailyStatsFinder type
type mockdailyStatsFinder struct {
	mock.Mock
}

type mockdailyStatsFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdailyStatsFinder) EXPECT() *mockdailyStatsFinder_Expecter {
	return &mockdailyStatsFinder_Expecter{mock: &_m.Mock}
}

// FindRange provides a mock function for the type mockdailyStatsFinder
func (_mock *mockdailyStatsFinder) FindRange(ctx context.Context, userID string, fromDateKey string, toDateKey string) ([]study.DailyStat, error) {
	ret := _mock.Called(ctx, userID, fromDateKey, toDateKey)

	if len(ret) == 0 {
		panic("no return value specified for FindRange")
	}

	var r0 []study.DailyStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]study.DailyStat, error)); ok {
		return returnFunc(ctx, userID, fromDateKey, toDateKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []study.DailyStat); ok {
		r0 = returnFunc(ctx, userID, fromDateKey, toDateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]study.DailyStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, fromDateKey, toDateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdailyStatsFinder_FindRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRange'
type mockdailyStatsFinder_FindRange_Call struct {
	*mock.Call
}

// FindRange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - fromDateKey string
//   - toDateKey string
func (_e *mockdailyStatsFinder_Expecter) FindRange(ctx interface{}, userID interface{}, fromDateKey interface{}, toDateKey interface{}) *mockdailyStatsFinder_FindRange_Call {
	return &mockdailyStatsFinder_FindRange_Call{Call: _e.mock.On("FindRange", ctx, userID, fromDateKey, toDateKey)}
}

func (_c *mockdailyStatsFinder_FindRange_Call) Run(run func(ctx context.Context, userID string, fromDateKey string, toDateKey string)) *mockdailyStatsFinder_FindRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockdailyStatsFinder_FindRange_Call) Return(dailyStats []study.DailyStat, err error) *mockdailyStatsFinder_FindRange_Call {
	_c.Call.Return(dailyStats, err)
	return _c
}

func (_c *mockdailyStatsFinder_FindRange_Call) RunAndReturn(run func(ctx context.Context, userID string, fromDateKey string, toDateKey string) ([]study.DailyStat, error)) *mockdailyStatsFinder_FindRange_Call {
	_c.Call.Return(run)
	return _c
}

// newMockactiveQuestionListFinder creates a new instance of mockactiveQuestionListFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveQuestionListFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveQuestionListFinder {
	mock := &mockactiveQuestionListFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveQuestionListFinder is an autogenerated mock type for the activeQuestionListFinder type
type mockactiveQuestionListFinder struct {
	mock.Mock
}

type mockactiveQuestionListFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockactiveQuestionListFinder) EXPECT() *mockactiveQuestionListFinder_Expecter {
	return &mockactiveQuestionListFinder_Expecter{mock: &_m.Mock}
}

// FindByWorkbookID provides a mock function for the type mockactiveQuestionListFinder
func (_mock *mockactiveQuestionListFinder) FindByWorkbookID(ctx context.Context, workbookID string) (*domain.ActiveQuestionList, error) {
	ret := _mock.Called(ctx, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkbookID")
	}

	var r0 *domain.ActiveQuestionList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.ActiveQuestionList, error)); ok {
		return returnFunc(ctx, workbookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.ActiveQuestionList); ok {
		r0 = returnFunc(ctx, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActiveQuestionList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workbookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockactiveQuestionListFinder_FindByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWorkbookID'
type mockactiveQuestionListFinder_FindByWorkbookID_Call struct {
	*mock.Call
}

// FindByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
func (_e *mockactiveQuestionListFinder_Expecter) FindByWorkbookID(ctx interface{}, workbookID interface{}) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	return &mockactiveQuestionListFinder_FindByWorkbookID_Call{Call: _e.mock.On("FindByWorkbookID", ctx, workbookID)}
}

func (_c *mockactiveQuestionListFinder_FindByWorkbookID_Call) Run(run func(ctx context.Context, workbookID string)) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveQuestionListFinder_FindByWorkbookID_Call) Return(activeQuestionList *domain.ActiveQuestionList, err error) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	_c.Call.Return(activeQuestionList, err)
	return _c
}

func (_c *mockactiveQuestionListFinder_FindByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, workbookID string) (*domain.ActiveQuestionList, error)) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockquestionBatchFinder creates a new instance of mockquestionBatchFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionBatchFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionBatchFinder {
	mock := &mockquestionBatchFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionBatchFinder is an autogenerated mock type for the questionBatchFinder type
type mockquestionBatchFinder struct {
	mock.Mock
}

type mockquestionBatchFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionBatchFinder) EXPECT() *mockquestionBatchFinder_Expecter {
	return &mockquestionBatchFinder_Expecter{mock: &_m.Mock}
}

// FindByIDs provides a mock function for the type mockquestionBatchFinder
func (_mock *mockquestionBatchFinder) FindByIDs(ctx context.Context, workbookID string, questionIDs []string) ([]question.Question, error) {
	ret := _mock.Called(ctx, workbookID, questionIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]question.Question, error)); ok {
		return returnFunc(ctx, workbookID, questionIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []question.Question); ok {
		r0 = returnFunc(ctx, workbookID, questionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, workbookID, questionIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionBatchFinder_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type mockquestionBatchFinder_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionIDs []string
func (_e *mockquestionBatchFinder_Expecter) FindByIDs(ctx interface{}, workbookID interface{}, questionIDs interface{}) *mockquestionBatchFinder_FindByIDs_Call {
	return &mockquestionBatchFinder_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, workbookID, questionIDs)}
}

func (_c *mockquestionBatchFinder_FindByIDs_Call) Run(run func(ctx context.Context, workbookID string, questionIDs []string)) *mockquestionBatchFinder_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionBatchFinder_FindByIDs_Call) Return(questions []question.Question, err error) *mockquestionBatchFinder_FindByIDs_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *mockquestionBatchFinder_FindByIDs_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionIDs []string) ([]question.Question, error)) *mockquestionBatchFinder_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// newMockquestionFinder creates a new instance of mockquestionFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionFinder {
	mock := &mockquestionFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionFinder is an autogenerated mock type for the questionFinder type
type mockquestionFinder struct {
	mock.Mock
}

type mockquestionFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionFinder) EXPECT() *mockquestionFinder_Expecter {
	return &mockquestionFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockquestionFinder
func (_mock *mockquestionFinder) FindByID(ctx context.Context, workbookID string, questionID string) (*question.Question, error) {
	ret := _mock.Called(ctx, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*question.Question, error)); ok {
		return returnFunc(ctx, workbookID, questionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *question.Question); ok {
		r0 = returnFunc(ctx, workbookID, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workbookID, questionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockquestionFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionID string
func (_e *mockquestionFinder_Expecter) FindByID(ctx interface{}, workbookID interface{}, questionID interface{}) *mockquestionFinder_FindByID_Call {
	return &mockquestionFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, workbookID, questionID)}
}

func (_c *mockquestionFinder_FindByID_Call) Run(run func(ctx context.Context, workbookID string, questionID string)) *mockquestionFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionFinder_FindByID_Call) Return(question1 *question.Question, err error) *mockquestionFinder_FindByID_Call {
	_c.Call.Return(question1, err)
	return _c
}

func (_c *mockquestionFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionID string) (*question.Question, error)) *mockquestionFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkbookFinder creates a new instance of mockworkbookFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkbookFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkbookFinder {
	mock := &mockworkbookFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkbookFinder is an autogenerated mock type for the workbookFinder type
type mockworkbookFinder struct {
	mock.Mock
}

type mockworkbookFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkbookFinder) EXPECT() *mockworkbookFinder_Expecter {
	return &mockworkbookFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockworkbookFinder
func (_mock *mockworkbookFinder) FindByID(ctx context.Context, id string) (*workbook.Workbook, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *workbook.Workbook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*workbook.Workbook, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *workbook.Workbook); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.Workbook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkbookFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockworkbookFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockworkbookFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockworkbookFinder_FindByID_Call {
	return &mockworkbookFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockworkbookFinder_FindByID_Call) Run(run func(ctx context.Context, id string)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) Return(workbook1 *workbook.Workbook, err error) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(workbook1, err)
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*workbook.Workbook, error)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockauthorizationChecker creates a new instance of mockauthorizationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauthorizationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauthorizationChecker {
	mock := &mockauthorizationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauthorizationChecker is an autogenerated mock type for the authorizationChecker type
type mockauthorizationChecker struct {
	mock.Mock
}

type mockauthorizationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauthorizationChecker) EXPECT() *mockauthorizationChecker_Expecter {
	return &mockauthorizationChecker_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type mockauthorizationChecker
func (_mock *mockauthorizationChecker) IsAllowed(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error) {
	ret := _mock.Called(ctx, organizationID, operatorID, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) (bool, error)); ok {
		return returnFunc(ctx, organizationID, operatorID, action, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) bool); ok {
		r0 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.Action, domain.Resource) error); ok {
		r1 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauthorizationChecker_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type mockauthorizationChecker_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - operatorID string
//   - action domain.Action
//   - resource domain.Resource
func (_e *mockauthorizationChecker_Expecter) IsAllowed(ctx interface{}, organizationID interface{}, operatorID interface{}, action interface{}, resource interface{}) *mockauthorizationChecker_IsAllowed_Call {
	return &mockauthorizationChecker_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, organizationID, operatorID, action, resource)}
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Run(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.Action
		if args[3] != nil {
			arg3 = args[3].(domain.Action)
		}
		var arg4 domain.Resource
		if args[4] != nil {
			arg4 = args[4].(domain.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Return(b bool, err error) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}
