// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package question_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/question"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/workbook"
	mock "github.com/stretchr/testify/mock"
)

// newMockquestionFinder creates a new instance of mockquestionFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionFinder {
	mock := &mockquestionFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionFinder is an autogenerated mock type for the questionFinder type
type mockquestionFinder struct {
	mock.Mock
}

type mockquestionFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionFinder) EXPECT() *mockquestionFinder_Expecter {
	return &mockquestionFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockquestionFinder
func (_mock *mockquestionFinder) FindByID(ctx context.Context, workbookID string, questionID string) (*question.Question, error) {
	ret := _mock.Called(ctx, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*question.Question, error)); ok {
		return returnFunc(ctx, workbookID, questionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *question.Question); ok {
		r0 = returnFunc(ctx, workbookID, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workbookID, questionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockquestionFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionID string
func (_e *mockquestionFinder_Expecter) FindByID(ctx interface{}, workbookID interface{}, questionID interface{}) *mockquestionFinder_FindByID_Call {
	return &mockquestionFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, workbookID, questionID)}
}

func (_c *mockquestionFinder_FindByID_Call) Run(run func(ctx context.Context, workbookID string, questionID string)) *mockquestionFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionFinder_FindByID_Call) Return(question1 *question.Question, err error) *mockquestionFinder_FindByID_Call {
	_c.Call.Return(question1, err)
	return _c
}

func (_c *mockquestionFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionID string) (*question.Question, error)) *mockquestionFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByWorkbookID provides a mock function for the type mockquestionFinder
func (_mock *mockquestionFinder) FindByWorkbookID(ctx context.Context, workbookID string) ([]question.Question, error) {
	ret := _mock.Called(ctx, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkbookID")
	}

	var r0 []question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]question.Question, error)); ok {
		return returnFunc(ctx, workbookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []question.Question); ok {
		r0 = returnFunc(ctx, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workbookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionFinder_FindByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWorkbookID'
type mockquestionFinder_FindByWorkbookID_Call struct {
	*mock.Call
}

// FindByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
func (_e *mockquestionFinder_Expecter) FindByWorkbookID(ctx interface{}, workbookID interface{}) *mockquestionFinder_FindByWorkbookID_Call {
	return &mockquestionFinder_FindByWorkbookID_Call{Call: _e.mock.On("FindByWorkbookID", ctx, workbookID)}
}

func (_c *mockquestionFinder_FindByWorkbookID_Call) Run(run func(ctx context.Context, workbookID string)) *mockquestionFinder_FindByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockquestionFinder_FindByWorkbookID_Call) Return(questions []question.Question, err error) *mockquestionFinder_FindByWorkbookID_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *mockquestionFinder_FindByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, workbookID string) ([]question.Question, error)) *mockquestionFinder_FindByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockquestionSaver creates a new instance of mockquestionSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionSaver {
	mock := &mockquestionSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionSaver is an autogenerated mock type for the questionSaver type
type mockquestionSaver struct {
	mock.Mock
}

type mockquestionSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionSaver) EXPECT() *mockquestionSaver_Expecter {
	return &mockquestionSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type mockquestionSaver
func (_mock *mockquestionSaver) Save(ctx context.Context, q *question.Question) error {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *question.Question) error); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockquestionSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockquestionSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - q *question.Question
func (_e *mockquestionSaver_Expecter) Save(ctx interface{}, q interface{}) *mockquestionSaver_Save_Call {
	return &mockquestionSaver_Save_Call{Call: _e.mock.On("Save", ctx, q)}
}

func (_c *mockquestionSaver_Save_Call) Run(run func(ctx context.Context, q *question.Question)) *mockquestionSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *question.Question
		if args[1] != nil {
			arg1 = args[1].(*question.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockquestionSaver_Save_Call) Return(err error) *mockquestionSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockquestionSaver_Save_Call) RunAndReturn(run func(ctx context.Context, q *question.Question) error) *mockquestionSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockquestionDeleter creates a new instance of mockquestionDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionDeleter {
	mock := &mockquestionDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionDeleter is an autogenerated mock type for the questionDeleter type
type mockquestionDeleter struct {
	mock.Mock
}

type mockquestionDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionDeleter) EXPECT() *mockquestionDeleter_Expecter {
	return &mockquestionDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type mockquestionDeleter
func (_mock *mockquestionDeleter) Delete(ctx context.Context, workbookID string, questionID string) error {
	ret := _mock.Called(ctx, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, workbookID, questionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockquestionDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockquestionDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionID string
func (_e *mockquestionDeleter_Expecter) Delete(ctx interface{}, workbookID interface{}, questionID interface{}) *mockquestionDeleter_Delete_Call {
	return &mockquestionDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, workbookID, questionID)}
}

func (_c *mockquestionDeleter_Delete_Call) Run(run func(ctx context.Context, workbookID string, questionID string)) *mockquestionDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionDeleter_Delete_Call) Return(err error) *mockquestionDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockquestionDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionID string) error) *mockquestionDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkbookFinder creates a new instance of mockworkbookFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkbookFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkbookFinder {
	mock := &mockworkbookFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkbookFinder is an autogenerated mock type for the workbookFinder type
type mockworkbookFinder struct {
	mock.Mock
}

type mockworkbookFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkbookFinder) EXPECT() *mockworkbookFinder_Expecter {
	return &mockworkbookFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockworkbookFinder
func (_mock *mockworkbookFinder) FindByID(ctx context.Context, id string) (*workbook.Workbook, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *workbook.Workbook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*workbook.Workbook, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *workbook.Workbook); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.Workbook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkbookFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockworkbookFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockworkbookFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockworkbookFinder_FindByID_Call {
	return &mockworkbookFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockworkbookFinder_FindByID_Call) Run(run func(ctx context.Context, id string)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) Return(workbook1 *workbook.Workbook, err error) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(workbook1, err)
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*workbook.Workbook, error)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockactiveQuestionListFinder creates a new instance of mockactiveQuestionListFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveQuestionListFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveQuestionListFinder {
	mock := &mockactiveQuestionListFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveQuestionListFinder is an autogenerated mock type for the activeQuestionListFinder type
type mockactiveQuestionListFinder struct {
	mock.Mock
}

type mockactiveQuestionListFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockactiveQuestionListFinder) EXPECT() *mockactiveQuestionListFinder_Expecter {
	return &mockactiveQuestionListFinder_Expecter{mock: &_m.Mock}
}

// FindByWorkbookID provides a mock function for the type mockactiveQuestionListFinder
func (_mock *mockactiveQuestionListFinder) FindByWorkbookID(ctx context.Context, workbookID string) (*domain.ActiveQuestionList, error) {
	ret := _mock.Called(ctx, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkbookID")
	}

	var r0 *domain.ActiveQuestionList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.ActiveQuestionList, error)); ok {
		return returnFunc(ctx, workbookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.ActiveQuestionList); ok {
		r0 = returnFunc(ctx, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActiveQuestionList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workbookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockactiveQuestionListFinder_FindByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWorkbookID'
type mockactiveQuestionListFinder_FindByWorkbookID_Call struct {
	*mock.Call
}

// FindByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
func (_e *mockactiveQuestionListFinder_Expecter) FindByWorkbookID(ctx interface{}, workbookID interface{}) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	return &mockactiveQuestionListFinder_FindByWorkbookID_Call{Call: _e.mock.On("FindByWorkbookID", ctx, workbookID)}
}

func (_c *mockactiveQuestionListFinder_FindByWorkbookID_Call) Run(run func(ctx context.Context, workbookID string)) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveQuestionListFinder_FindByWorkbookID_Call) Return(activeQuestionList *domain.ActiveQuestionList, err error) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	_c.Call.Return(activeQuestionList, err)
	return _c
}

func (_c *mockactiveQuestionListFinder_FindByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, workbookID string) (*domain.ActiveQuestionList, error)) *mockactiveQuestionListFinder_FindByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockactiveQuestionListSaver creates a new instance of mockactiveQuestionListSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockactiveQuestionListSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockactiveQuestionListSaver {
	mock := &mockactiveQuestionListSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockactiveQuestionListSaver is an autogenerated mock type for the activeQuestionListSaver type
type mockactiveQuestionListSaver struct {
	mock.Mock
}

type mockactiveQuestionListSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockactiveQuestionListSaver) EXPECT() *mockactiveQuestionListSaver_Expecter {
	return &mockactiveQuestionListSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type mockactiveQuestionListSaver
func (_mock *mockactiveQuestionListSaver) Save(ctx context.Context, list *domain.ActiveQuestionList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ActiveQuestionList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockactiveQuestionListSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockactiveQuestionListSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *domain.ActiveQuestionList
func (_e *mockactiveQuestionListSaver_Expecter) Save(ctx interface{}, list interface{}) *mockactiveQuestionListSaver_Save_Call {
	return &mockactiveQuestionListSaver_Save_Call{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *mockactiveQuestionListSaver_Save_Call) Run(run func(ctx context.Context, list *domain.ActiveQuestionList)) *mockactiveQuestionListSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ActiveQuestionList
		if args[1] != nil {
			arg1 = args[1].(*domain.ActiveQuestionList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockactiveQuestionListSaver_Save_Call) Return(err error) *mockactiveQuestionListSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockactiveQuestionListSaver_Save_Call) RunAndReturn(run func(ctx context.Context, list *domain.ActiveQuestionList) error) *mockactiveQuestionListSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockauthorizationChecker creates a new instance of mockauthorizationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauthorizationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauthorizationChecker {
	mock := &mockauthorizationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauthorizationChecker is an autogenerated mock type for the authorizationChecker type
type mockauthorizationChecker struct {
	mock.Mock
}

type mockauthorizationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauthorizationChecker) EXPECT() *mockauthorizationChecker_Expecter {
	return &mockauthorizationChecker_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type mockauthorizationChecker
func (_mock *mockauthorizationChecker) IsAllowed(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error) {
	ret := _mock.Called(ctx, organizationID, operatorID, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) (bool, error)); ok {
		return returnFunc(ctx, organizationID, operatorID, action, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) bool); ok {
		r0 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.Action, domain.Resource) error); ok {
		r1 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauthorizationChecker_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type mockauthorizationChecker_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - operatorID string
//   - action domain.Action
//   - resource domain.Resource
func (_e *mockauthorizationChecker_Expecter) IsAllowed(ctx interface{}, organizationID interface{}, operatorID interface{}, action interface{}, resource interface{}) *mockauthorizationChecker_IsAllowed_Call {
	return &mockauthorizationChecker_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, organizationID, operatorID, action, resource)}
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Run(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.Action
		if args[3] != nil {
			arg3 = args[3].(domain.Action)
		}
		var arg4 domain.Resource
		if args[4] != nil {
			arg4 = args[4].(domain.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Return(b bool, err error) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}
