// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package question_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/question"
	"github.com/mocoarow/cocotola-1.26/cocotola-question/domain/workbook"
	mock "github.com/stretchr/testify/mock"
)

// newMockquestionAdder creates a new instance of mockquestionAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionAdder {
	mock := &mockquestionAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionAdder is an autogenerated mock type for the questionAdder type
type mockquestionAdder struct {
	mock.Mock
}

type mockquestionAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionAdder) EXPECT() *mockquestionAdder_Expecter {
	return &mockquestionAdder_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type mockquestionAdder
func (_mock *mockquestionAdder) Add(ctx context.Context, workbookID string, questionType string, content string, tags []string, orderIndex int) (string, error) {
	ret := _mock.Called(ctx, workbookID, questionType, content, tags, orderIndex)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string, int) (string, error)); ok {
		return returnFunc(ctx, workbookID, questionType, content, tags, orderIndex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string, int) string); ok {
		r0 = returnFunc(ctx, workbookID, questionType, content, tags, orderIndex)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []string, int) error); ok {
		r1 = returnFunc(ctx, workbookID, questionType, content, tags, orderIndex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionAdder_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type mockquestionAdder_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionType string
//   - content string
//   - tags []string
//   - orderIndex int
func (_e *mockquestionAdder_Expecter) Add(ctx interface{}, workbookID interface{}, questionType interface{}, content interface{}, tags interface{}, orderIndex interface{}) *mockquestionAdder_Add_Call {
	return &mockquestionAdder_Add_Call{Call: _e.mock.On("Add", ctx, workbookID, questionType, content, tags, orderIndex)}
}

func (_c *mockquestionAdder_Add_Call) Run(run func(ctx context.Context, workbookID string, questionType string, content string, tags []string, orderIndex int)) *mockquestionAdder_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockquestionAdder_Add_Call) Return(s string, err error) *mockquestionAdder_Add_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockquestionAdder_Add_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionType string, content string, tags []string, orderIndex int) (string, error)) *mockquestionAdder_Add_Call {
	_c.Call.Return(run)
	return _c
}

// newMockquestionFinder creates a new instance of mockquestionFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionFinder {
	mock := &mockquestionFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionFinder is an autogenerated mock type for the questionFinder type
type mockquestionFinder struct {
	mock.Mock
}

type mockquestionFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionFinder) EXPECT() *mockquestionFinder_Expecter {
	return &mockquestionFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockquestionFinder
func (_mock *mockquestionFinder) FindByID(ctx context.Context, workbookID string, questionID string) (*question.Question, error) {
	ret := _mock.Called(ctx, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*question.Question, error)); ok {
		return returnFunc(ctx, workbookID, questionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *question.Question); ok {
		r0 = returnFunc(ctx, workbookID, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workbookID, questionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockquestionFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionID string
func (_e *mockquestionFinder_Expecter) FindByID(ctx interface{}, workbookID interface{}, questionID interface{}) *mockquestionFinder_FindByID_Call {
	return &mockquestionFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, workbookID, questionID)}
}

func (_c *mockquestionFinder_FindByID_Call) Run(run func(ctx context.Context, workbookID string, questionID string)) *mockquestionFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionFinder_FindByID_Call) Return(question1 *question.Question, err error) *mockquestionFinder_FindByID_Call {
	_c.Call.Return(question1, err)
	return _c
}

func (_c *mockquestionFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionID string) (*question.Question, error)) *mockquestionFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByWorkbookID provides a mock function for the type mockquestionFinder
func (_mock *mockquestionFinder) FindByWorkbookID(ctx context.Context, workbookID string) ([]question.Question, error) {
	ret := _mock.Called(ctx, workbookID)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkbookID")
	}

	var r0 []question.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]question.Question, error)); ok {
		return returnFunc(ctx, workbookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []question.Question); ok {
		r0 = returnFunc(ctx, workbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]question.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workbookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockquestionFinder_FindByWorkbookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWorkbookID'
type mockquestionFinder_FindByWorkbookID_Call struct {
	*mock.Call
}

// FindByWorkbookID is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
func (_e *mockquestionFinder_Expecter) FindByWorkbookID(ctx interface{}, workbookID interface{}) *mockquestionFinder_FindByWorkbookID_Call {
	return &mockquestionFinder_FindByWorkbookID_Call{Call: _e.mock.On("FindByWorkbookID", ctx, workbookID)}
}

func (_c *mockquestionFinder_FindByWorkbookID_Call) Run(run func(ctx context.Context, workbookID string)) *mockquestionFinder_FindByWorkbookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockquestionFinder_FindByWorkbookID_Call) Return(questions []question.Question, err error) *mockquestionFinder_FindByWorkbookID_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *mockquestionFinder_FindByWorkbookID_Call) RunAndReturn(run func(ctx context.Context, workbookID string) ([]question.Question, error)) *mockquestionFinder_FindByWorkbookID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockquestionUpdater creates a new instance of mockquestionUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionUpdater {
	mock := &mockquestionUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionUpdater is an autogenerated mock type for the questionUpdater type
type mockquestionUpdater struct {
	mock.Mock
}

type mockquestionUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionUpdater) EXPECT() *mockquestionUpdater_Expecter {
	return &mockquestionUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type mockquestionUpdater
func (_mock *mockquestionUpdater) Update(ctx context.Context, workbookID string, questionID string, content string, tags []string, orderIndex int) error {
	ret := _mock.Called(ctx, workbookID, questionID, content, tags, orderIndex)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string, int) error); ok {
		r0 = returnFunc(ctx, workbookID, questionID, content, tags, orderIndex)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockquestionUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockquestionUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionID string
//   - content string
//   - tags []string
//   - orderIndex int
func (_e *mockquestionUpdater_Expecter) Update(ctx interface{}, workbookID interface{}, questionID interface{}, content interface{}, tags interface{}, orderIndex interface{}) *mockquestionUpdater_Update_Call {
	return &mockquestionUpdater_Update_Call{Call: _e.mock.On("Update", ctx, workbookID, questionID, content, tags, orderIndex)}
}

func (_c *mockquestionUpdater_Update_Call) Run(run func(ctx context.Context, workbookID string, questionID string, content string, tags []string, orderIndex int)) *mockquestionUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockquestionUpdater_Update_Call) Return(err error) *mockquestionUpdater_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockquestionUpdater_Update_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionID string, content string, tags []string, orderIndex int) error) *mockquestionUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockquestionDeleter creates a new instance of mockquestionDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockquestionDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockquestionDeleter {
	mock := &mockquestionDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockquestionDeleter is an autogenerated mock type for the questionDeleter type
type mockquestionDeleter struct {
	mock.Mock
}

type mockquestionDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockquestionDeleter) EXPECT() *mockquestionDeleter_Expecter {
	return &mockquestionDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type mockquestionDeleter
func (_mock *mockquestionDeleter) Delete(ctx context.Context, workbookID string, questionID string) error {
	ret := _mock.Called(ctx, workbookID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, workbookID, questionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockquestionDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockquestionDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - workbookID string
//   - questionID string
func (_e *mockquestionDeleter_Expecter) Delete(ctx interface{}, workbookID interface{}, questionID interface{}) *mockquestionDeleter_Delete_Call {
	return &mockquestionDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, workbookID, questionID)}
}

func (_c *mockquestionDeleter_Delete_Call) Run(run func(ctx context.Context, workbookID string, questionID string)) *mockquestionDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockquestionDeleter_Delete_Call) Return(err error) *mockquestionDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockquestionDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, workbookID string, questionID string) error) *mockquestionDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkbookFinder creates a new instance of mockworkbookFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkbookFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkbookFinder {
	mock := &mockworkbookFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkbookFinder is an autogenerated mock type for the workbookFinder type
type mockworkbookFinder struct {
	mock.Mock
}

type mockworkbookFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkbookFinder) EXPECT() *mockworkbookFinder_Expecter {
	return &mockworkbookFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type mockworkbookFinder
func (_mock *mockworkbookFinder) FindByID(ctx context.Context, id string) (*workbook.Workbook, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *workbook.Workbook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*workbook.Workbook, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *workbook.Workbook); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workbook.Workbook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkbookFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockworkbookFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockworkbookFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockworkbookFinder_FindByID_Call {
	return &mockworkbookFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockworkbookFinder_FindByID_Call) Run(run func(ctx context.Context, id string)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) Return(workbook1 *workbook.Workbook, err error) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(workbook1, err)
	return _c
}

func (_c *mockworkbookFinder_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*workbook.Workbook, error)) *mockworkbookFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockauthorizationChecker creates a new instance of mockauthorizationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauthorizationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauthorizationChecker {
	mock := &mockauthorizationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauthorizationChecker is an autogenerated mock type for the authorizationChecker type
type mockauthorizationChecker struct {
	mock.Mock
}

type mockauthorizationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauthorizationChecker) EXPECT() *mockauthorizationChecker_Expecter {
	return &mockauthorizationChecker_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type mockauthorizationChecker
func (_mock *mockauthorizationChecker) IsAllowed(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error) {
	ret := _mock.Called(ctx, organizationID, operatorID, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) (bool, error)); ok {
		return returnFunc(ctx, organizationID, operatorID, action, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.Action, domain.Resource) bool); ok {
		r0 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.Action, domain.Resource) error); ok {
		r1 = returnFunc(ctx, organizationID, operatorID, action, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauthorizationChecker_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type mockauthorizationChecker_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - operatorID string
//   - action domain.Action
//   - resource domain.Resource
func (_e *mockauthorizationChecker_Expecter) IsAllowed(ctx interface{}, organizationID interface{}, operatorID interface{}, action interface{}, resource interface{}) *mockauthorizationChecker_IsAllowed_Call {
	return &mockauthorizationChecker_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, organizationID, operatorID, action, resource)}
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Run(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.Action
		if args[3] != nil {
			arg3 = args[3].(domain.Action)
		}
		var arg4 domain.Resource
		if args[4] != nil {
			arg4 = args[4].(domain.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) Return(b bool, err error) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockauthorizationChecker_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, organizationID string, operatorID string, action domain.Action, resource domain.Resource) (bool, error)) *mockauthorizationChecker_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}
