---
app:
  ownerLoginId: ${OWNER_LOGIN_ID}
  ownerPassword: ${OWNER_PASSWORD}
db:
  driverName: ${APP_DB_DRIVER_NAME:-postgres}
  postgres:
    username: ${AUTH_POSTGRES_USERNAME}
    password: ${AUTH_POSTGRES_PASSWORD}
    host: ${AUTH_POSTGRES_HOST:-127.0.0.1}
    port: ${AUTH_POSTGRES_PORT:-5432}
    database: ${AUTH_POSTGRES_DATABASE:-local}
log:
  level: ${LOG_LEVEL:-info}
  exporter: ${LOG_EXPORTER:-none}
