// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package space_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/service/space"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateSpaceUsecase creates a new instance of MockCreateSpaceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateSpaceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateSpaceUsecase {
	mock := &MockCreateSpaceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateSpaceUsecase is an autogenerated mock type for the CreateSpaceUsecase type
type MockCreateSpaceUsecase struct {
	mock.Mock
}

type MockCreateSpaceUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateSpaceUsecase) EXPECT() *MockCreateSpaceUsecase_Expecter {
	return &MockCreateSpaceUsecase_Expecter{mock: &_m.Mock}
}

// CreateSpace provides a mock function for the type MockCreateSpaceUsecase
func (_mock *MockCreateSpaceUsecase) CreateSpace(ctx context.Context, input *space.CreateSpaceInput) (*space.CreateSpaceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateSpace")
	}

	var r0 *space.CreateSpaceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *space.CreateSpaceInput) (*space.CreateSpaceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *space.CreateSpaceInput) *space.CreateSpaceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*space.CreateSpaceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *space.CreateSpaceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateSpaceUsecase_CreateSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSpace'
type MockCreateSpaceUsecase_CreateSpace_Call struct {
	*mock.Call
}

// CreateSpace is a helper method to define mock.On call
//   - ctx context.Context
//   - input *space.CreateSpaceInput
func (_e *MockCreateSpaceUsecase_Expecter) CreateSpace(ctx interface{}, input interface{}) *MockCreateSpaceUsecase_CreateSpace_Call {
	return &MockCreateSpaceUsecase_CreateSpace_Call{Call: _e.mock.On("CreateSpace", ctx, input)}
}

func (_c *MockCreateSpaceUsecase_CreateSpace_Call) Run(run func(ctx context.Context, input *space.CreateSpaceInput)) *MockCreateSpaceUsecase_CreateSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *space.CreateSpaceInput
		if args[1] != nil {
			arg1 = args[1].(*space.CreateSpaceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateSpaceUsecase_CreateSpace_Call) Return(createSpaceOutput *space.CreateSpaceOutput, err error) *MockCreateSpaceUsecase_CreateSpace_Call {
	_c.Call.Return(createSpaceOutput, err)
	return _c
}

func (_c *MockCreateSpaceUsecase_CreateSpace_Call) RunAndReturn(run func(ctx context.Context, input *space.CreateSpaceInput) (*space.CreateSpaceOutput, error)) *MockCreateSpaceUsecase_CreateSpace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindSpaceUsecase creates a new instance of MockFindSpaceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindSpaceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindSpaceUsecase {
	mock := &MockFindSpaceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFindSpaceUsecase is an autogenerated mock type for the FindSpaceUsecase type
type MockFindSpaceUsecase struct {
	mock.Mock
}

type MockFindSpaceUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindSpaceUsecase) EXPECT() *MockFindSpaceUsecase_Expecter {
	return &MockFindSpaceUsecase_Expecter{mock: &_m.Mock}
}

// FindSpace provides a mock function for the type MockFindSpaceUsecase
func (_mock *MockFindSpaceUsecase) FindSpace(ctx context.Context, input *space.FindSpaceInput) (*space.FindSpaceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for FindSpace")
	}

	var r0 *space.FindSpaceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *space.FindSpaceInput) (*space.FindSpaceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *space.FindSpaceInput) *space.FindSpaceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*space.FindSpaceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *space.FindSpaceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFindSpaceUsecase_FindSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSpace'
type MockFindSpaceUsecase_FindSpace_Call struct {
	*mock.Call
}

// FindSpace is a helper method to define mock.On call
//   - ctx context.Context
//   - input *space.FindSpaceInput
func (_e *MockFindSpaceUsecase_Expecter) FindSpace(ctx interface{}, input interface{}) *MockFindSpaceUsecase_FindSpace_Call {
	return &MockFindSpaceUsecase_FindSpace_Call{Call: _e.mock.On("FindSpace", ctx, input)}
}

func (_c *MockFindSpaceUsecase_FindSpace_Call) Run(run func(ctx context.Context, input *space.FindSpaceInput)) *MockFindSpaceUsecase_FindSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *space.FindSpaceInput
		if args[1] != nil {
			arg1 = args[1].(*space.FindSpaceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFindSpaceUsecase_FindSpace_Call) Return(findSpaceOutput *space.FindSpaceOutput, err error) *MockFindSpaceUsecase_FindSpace_Call {
	_c.Call.Return(findSpaceOutput, err)
	return _c
}

func (_c *MockFindSpaceUsecase_FindSpace_Call) RunAndReturn(run func(ctx context.Context, input *space.FindSpaceInput) (*space.FindSpaceOutput, error)) *MockFindSpaceUsecase_FindSpace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListSpacesUsecase creates a new instance of MockListSpacesUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListSpacesUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListSpacesUsecase {
	mock := &MockListSpacesUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListSpacesUsecase is an autogenerated mock type for the ListSpacesUsecase type
type MockListSpacesUsecase struct {
	mock.Mock
}

type MockListSpacesUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListSpacesUsecase) EXPECT() *MockListSpacesUsecase_Expecter {
	return &MockListSpacesUsecase_Expecter{mock: &_m.Mock}
}

// ListSpaces provides a mock function for the type MockListSpacesUsecase
func (_mock *MockListSpacesUsecase) ListSpaces(ctx context.Context, input *space.ListSpacesInput) (*space.ListSpacesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListSpaces")
	}

	var r0 *space.ListSpacesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *space.ListSpacesInput) (*space.ListSpacesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *space.ListSpacesInput) *space.ListSpacesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*space.ListSpacesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *space.ListSpacesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListSpacesUsecase_ListSpaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSpaces'
type MockListSpacesUsecase_ListSpaces_Call struct {
	*mock.Call
}

// ListSpaces is a helper method to define mock.On call
//   - ctx context.Context
//   - input *space.ListSpacesInput
func (_e *MockListSpacesUsecase_Expecter) ListSpaces(ctx interface{}, input interface{}) *MockListSpacesUsecase_ListSpaces_Call {
	return &MockListSpacesUsecase_ListSpaces_Call{Call: _e.mock.On("ListSpaces", ctx, input)}
}

func (_c *MockListSpacesUsecase_ListSpaces_Call) Run(run func(ctx context.Context, input *space.ListSpacesInput)) *MockListSpacesUsecase_ListSpaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *space.ListSpacesInput
		if args[1] != nil {
			arg1 = args[1].(*space.ListSpacesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListSpacesUsecase_ListSpaces_Call) Return(listSpacesOutput *space.ListSpacesOutput, err error) *MockListSpacesUsecase_ListSpaces_Call {
	_c.Call.Return(listSpacesOutput, err)
	return _c
}

func (_c *MockListSpacesUsecase_ListSpaces_Call) RunAndReturn(run func(ctx context.Context, input *space.ListSpacesInput) (*space.ListSpacesOutput, error)) *MockListSpacesUsecase_ListSpaces_Call {
	_c.Call.Return(run)
	return _c
}
