// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase_test

import (
	"context"
	"time"

	"github.com/mocoarow/cocotola-1.26/cocotola-audio-generator/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuestionAPI creates a new instance of MockQuestionAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestionAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestionAPI {
	mock := &MockQuestionAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuestionAPI is an autogenerated mock type for the QuestionAPI type
type MockQuestionAPI struct {
	mock.Mock
}

type MockQuestionAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestionAPI) EXPECT() *MockQuestionAPI_Expecter {
	return &MockQuestionAPI_Expecter{mock: &_m.Mock}
}

// Claim provides a mock function for the type MockQuestionAPI
func (_mock *MockQuestionAPI) Claim(ctx context.Context, item domain.PendingItem) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PendingItem) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionAPI_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockQuestionAPI_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - item domain.PendingItem
func (_e *MockQuestionAPI_Expecter) Claim(ctx interface{}, item interface{}) *MockQuestionAPI_Claim_Call {
	return &MockQuestionAPI_Claim_Call{Call: _e.mock.On("Claim", ctx, item)}
}

func (_c *MockQuestionAPI_Claim_Call) Run(run func(ctx context.Context, item domain.PendingItem)) *MockQuestionAPI_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PendingItem
		if args[1] != nil {
			arg1 = args[1].(domain.PendingItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionAPI_Claim_Call) Return(err error) *MockQuestionAPI_Claim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionAPI_Claim_Call) RunAndReturn(run func(ctx context.Context, item domain.PendingItem) error) *MockQuestionAPI_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type MockQuestionAPI
func (_mock *MockQuestionAPI) Complete(ctx context.Context, item domain.PendingItem, refs map[string]domain.AudioRef) error {
	ret := _mock.Called(ctx, item, refs)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PendingItem, map[string]domain.AudioRef) error); ok {
		r0 = returnFunc(ctx, item, refs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionAPI_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockQuestionAPI_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - item domain.PendingItem
//   - refs map[string]domain.AudioRef
func (_e *MockQuestionAPI_Expecter) Complete(ctx interface{}, item interface{}, refs interface{}) *MockQuestionAPI_Complete_Call {
	return &MockQuestionAPI_Complete_Call{Call: _e.mock.On("Complete", ctx, item, refs)}
}

func (_c *MockQuestionAPI_Complete_Call) Run(run func(ctx context.Context, item domain.PendingItem, refs map[string]domain.AudioRef)) *MockQuestionAPI_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PendingItem
		if args[1] != nil {
			arg1 = args[1].(domain.PendingItem)
		}
		var arg2 map[string]domain.AudioRef
		if args[2] != nil {
			arg2 = args[2].(map[string]domain.AudioRef)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuestionAPI_Complete_Call) Return(err error) *MockQuestionAPI_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionAPI_Complete_Call) RunAndReturn(run func(ctx context.Context, item domain.PendingItem, refs map[string]domain.AudioRef) error) *MockQuestionAPI_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function for the type MockQuestionAPI
func (_mock *MockQuestionAPI) Fail(ctx context.Context, item domain.PendingItem, reason string) error {
	ret := _mock.Called(ctx, item, reason)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PendingItem, string) error); ok {
		r0 = returnFunc(ctx, item, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionAPI_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type MockQuestionAPI_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - ctx context.Context
//   - item domain.PendingItem
//   - reason string
func (_e *MockQuestionAPI_Expecter) Fail(ctx interface{}, item interface{}, reason interface{}) *MockQuestionAPI_Fail_Call {
	return &MockQuestionAPI_Fail_Call{Call: _e.mock.On("Fail", ctx, item, reason)}
}

func (_c *MockQuestionAPI_Fail_Call) Run(run func(ctx context.Context, item domain.PendingItem, reason string)) *MockQuestionAPI_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PendingItem
		if args[1] != nil {
			arg1 = args[1].(domain.PendingItem)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuestionAPI_Fail_Call) Return(err error) *MockQuestionAPI_Fail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionAPI_Fail_Call) RunAndReturn(run func(ctx context.Context, item domain.PendingItem, reason string) error) *MockQuestionAPI_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function for the type MockQuestionAPI
func (_mock *MockQuestionAPI) ListPending(ctx context.Context, limit int) ([]domain.PendingItem, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []domain.PendingItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]domain.PendingItem, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []domain.PendingItem); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PendingItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionAPI_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type MockQuestionAPI_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockQuestionAPI_Expecter) ListPending(ctx interface{}, limit interface{}) *MockQuestionAPI_ListPending_Call {
	return &MockQuestionAPI_ListPending_Call{Call: _e.mock.On("ListPending", ctx, limit)}
}

func (_c *MockQuestionAPI_ListPending_Call) Run(run func(ctx context.Context, limit int)) *MockQuestionAPI_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionAPI_ListPending_Call) Return(pendingItems []domain.PendingItem, err error) *MockQuestionAPI_ListPending_Call {
	_c.Call.Return(pendingItems, err)
	return _c
}

func (_c *MockQuestionAPI_ListPending_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]domain.PendingItem, error)) *MockQuestionAPI_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// ReclaimStale provides a mock function for the type MockQuestionAPI
func (_mock *MockQuestionAPI) ReclaimStale(ctx context.Context, staleAfter time.Duration, limit int) (int, error) {
	ret := _mock.Called(ctx, staleAfter, limit)

	if len(ret) == 0 {
		panic("no return value specified for ReclaimStale")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) (int, error)); ok {
		return returnFunc(ctx, staleAfter, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) int); ok {
		r0 = returnFunc(ctx, staleAfter, limit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, staleAfter, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionAPI_ReclaimStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReclaimStale'
type MockQuestionAPI_ReclaimStale_Call struct {
	*mock.Call
}

// ReclaimStale is a helper method to define mock.On call
//   - ctx context.Context
//   - staleAfter time.Duration
//   - limit int
func (_e *MockQuestionAPI_Expecter) ReclaimStale(ctx interface{}, staleAfter interface{}, limit interface{}) *MockQuestionAPI_ReclaimStale_Call {
	return &MockQuestionAPI_ReclaimStale_Call{Call: _e.mock.On("ReclaimStale", ctx, staleAfter, limit)}
}

func (_c *MockQuestionAPI_ReclaimStale_Call) Run(run func(ctx context.Context, staleAfter time.Duration, limit int)) *MockQuestionAPI_ReclaimStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuestionAPI_ReclaimStale_Call) Return(n int, err error) *MockQuestionAPI_ReclaimStale_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuestionAPI_ReclaimStale_Call) RunAndReturn(run func(ctx context.Context, staleAfter time.Duration, limit int) (int, error)) *MockQuestionAPI_ReclaimStale_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTTS creates a new instance of MockTTS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTTS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTTS {
	mock := &MockTTS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTTS is an autogenerated mock type for the TTS type
type MockTTS struct {
	mock.Mock
}

type MockTTS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTTS) EXPECT() *MockTTS_Expecter {
	return &MockTTS_Expecter{mock: &_m.Mock}
}

// Synthesize provides a mock function for the type MockTTS
func (_mock *MockTTS) Synthesize(ctx context.Context, text string, voice string, lang string) ([]byte, error) {
	ret := _mock.Called(ctx, text, voice, lang)

	if len(ret) == 0 {
		panic("no return value specified for Synthesize")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]byte, error)); ok {
		return returnFunc(ctx, text, voice, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []byte); ok {
		r0 = returnFunc(ctx, text, voice, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, text, voice, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTTS_Synthesize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Synthesize'
type MockTTS_Synthesize_Call struct {
	*mock.Call
}

// Synthesize is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - voice string
//   - lang string
func (_e *MockTTS_Expecter) Synthesize(ctx interface{}, text interface{}, voice interface{}, lang interface{}) *MockTTS_Synthesize_Call {
	return &MockTTS_Synthesize_Call{Call: _e.mock.On("Synthesize", ctx, text, voice, lang)}
}

func (_c *MockTTS_Synthesize_Call) Run(run func(ctx context.Context, text string, voice string, lang string)) *MockTTS_Synthesize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTTS_Synthesize_Call) Return(bytes []byte, err error) *MockTTS_Synthesize_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTTS_Synthesize_Call) RunAndReturn(run func(ctx context.Context, text string, voice string, lang string) ([]byte, error)) *MockTTS_Synthesize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockStorage
func (_mock *MockStorage) Upload(ctx context.Context, objectPath string, contentType string, data []byte) (int64, error) {
	ret := _mock.Called(ctx, objectPath, contentType, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) (int64, error)); ok {
		return returnFunc(ctx, objectPath, contentType, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) int64); ok {
		r0 = returnFunc(ctx, objectPath, contentType, data)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = returnFunc(ctx, objectPath, contentType, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - objectPath string
//   - contentType string
//   - data []byte
func (_e *MockStorage_Expecter) Upload(ctx interface{}, objectPath interface{}, contentType interface{}, data interface{}) *MockStorage_Upload_Call {
	return &MockStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, objectPath, contentType, data)}
}

func (_c *MockStorage_Upload_Call) Run(run func(ctx context.Context, objectPath string, contentType string, data []byte)) *MockStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_Upload_Call) Return(n int64, err error) *MockStorage_Upload_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_Upload_Call) RunAndReturn(run func(ctx context.Context, objectPath string, contentType string, data []byte) (int64, error)) *MockStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}
