// Code generated by mockery; DO NOT EDIT.

package auth_test

import (
	"context"

	"github.com/stretchr/testify/mock"

	authservice "github.com/mocoarow/cocotola-1.26/cocotola-auth/service/auth"
)

// MockAuthUsecase is a composite mock that satisfies all handler usecase interfaces.
// It delegates to a single testify mock.Mock so that On/Return calls work across all methods.
type MockAuthUsecase struct {
	mock.Mock
}

func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	m := &MockAuthUsecase{}
	m.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// PasswordAuthenticateUsecase methods.

func (m *MockAuthUsecase) PasswordAuthenticate(ctx context.Context, input *authservice.PasswordAuthenticateInput) (*authservice.PasswordAuthenticateOutput, error) {
	ret := m.Called(ctx, input)
	var r0 *authservice.PasswordAuthenticateOutput
	if v, ok := ret.Get(0).(*authservice.PasswordAuthenticateOutput); ok {
		r0 = v
	}
	return r0, ret.Error(1)
}

func (m *MockAuthUsecase) CreateSessionToken(ctx context.Context, input *authservice.CreateSessionTokenInput) (*authservice.CreateSessionTokenOutput, error) {
	ret := m.Called(ctx, input)
	var r0 *authservice.CreateSessionTokenOutput
	if v, ok := ret.Get(0).(*authservice.CreateSessionTokenOutput); ok {
		r0 = v
	}
	return r0, ret.Error(1)
}

func (m *MockAuthUsecase) CreateTokenPair(ctx context.Context, input *authservice.CreateTokenPairInput) (*authservice.CreateTokenPairOutput, error) {
	ret := m.Called(ctx, input)
	var r0 *authservice.CreateTokenPairOutput
	if v, ok := ret.Get(0).(*authservice.CreateTokenPairOutput); ok {
		r0 = v
	}
	return r0, ret.Error(1)
}

// GuestAuthenticateUsecase methods.

func (m *MockAuthUsecase) GuestAuthenticate(ctx context.Context, input *authservice.GuestAuthenticateInput) (*authservice.GuestAuthenticateOutput, error) {
	ret := m.Called(ctx, input)
	var r0 *authservice.GuestAuthenticateOutput
	if v, ok := ret.Get(0).(*authservice.GuestAuthenticateOutput); ok {
		r0 = v
	}
	return r0, ret.Error(1)
}

// RefreshUsecase methods.

func (m *MockAuthUsecase) RefreshAccessToken(ctx context.Context, input *authservice.RefreshAccessTokenInput) (*authservice.RefreshAccessTokenOutput, error) {
	ret := m.Called(ctx, input)
	var r0 *authservice.RefreshAccessTokenOutput
	if v, ok := ret.Get(0).(*authservice.RefreshAccessTokenOutput); ok {
		r0 = v
	}
	return r0, ret.Error(1)
}

// RevokeUsecase methods.

func (m *MockAuthUsecase) RevokeSessionToken(ctx context.Context, input *authservice.RevokeSessionTokenInput) error {
	ret := m.Called(ctx, input)
	return ret.Error(0)
}

func (m *MockAuthUsecase) RevokeToken(ctx context.Context, input *authservice.RevokeTokenInput) error {
	ret := m.Called(ctx, input)
	return ret.Error(0)
}

// SupabaseExchangeUsecase methods.

func (m *MockAuthUsecase) SupabaseExchange(ctx context.Context, input *authservice.SupabaseExchangeInput) (*authservice.SupabaseExchangeOutput, error) {
	ret := m.Called(ctx, input)
	var r0 *authservice.SupabaseExchangeOutput
	if v, ok := ret.Get(0).(*authservice.SupabaseExchangeOutput); ok {
		r0 = v
	}
	return r0, ret.Error(1)
}
