// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_test

import (
	"context"

	authservice "github.com/mocoarow/cocotola-1.26/cocotola-auth/service/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// CreateSessionToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) CreateSessionToken(ctx context.Context, input *authservice.CreateSessionTokenInput) (*authservice.CreateSessionTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionToken")
	}

	var r0 *authservice.CreateSessionTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.CreateSessionTokenInput) (*authservice.CreateSessionTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.CreateSessionTokenInput) *authservice.CreateSessionTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authservice.CreateSessionTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authservice.CreateSessionTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_CreateSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionToken'
type MockAuthUsecase_CreateSessionToken_Call struct {
	*mock.Call
}

// CreateSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *authservice.CreateSessionTokenInput
func (_e *MockAuthUsecase_Expecter) CreateSessionToken(ctx interface{}, input interface{}) *MockAuthUsecase_CreateSessionToken_Call {
	return &MockAuthUsecase_CreateSessionToken_Call{Call: _e.mock.On("CreateSessionToken", ctx, input)}
}

func (_c *MockAuthUsecase_CreateSessionToken_Call) Run(run func(ctx context.Context, input *authservice.CreateSessionTokenInput)) *MockAuthUsecase_CreateSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authservice.CreateSessionTokenInput
		if args[1] != nil {
			arg1 = args[1].(*authservice.CreateSessionTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_CreateSessionToken_Call) Return(createSessionTokenOutput *authservice.CreateSessionTokenOutput, err error) *MockAuthUsecase_CreateSessionToken_Call {
	_c.Call.Return(createSessionTokenOutput, err)
	return _c
}

func (_c *MockAuthUsecase_CreateSessionToken_Call) RunAndReturn(run func(ctx context.Context, input *authservice.CreateSessionTokenInput) (*authservice.CreateSessionTokenOutput, error)) *MockAuthUsecase_CreateSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTokenPair provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) CreateTokenPair(ctx context.Context, input *authservice.CreateTokenPairInput) (*authservice.CreateTokenPairOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenPair")
	}

	var r0 *authservice.CreateTokenPairOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.CreateTokenPairInput) (*authservice.CreateTokenPairOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.CreateTokenPairInput) *authservice.CreateTokenPairOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authservice.CreateTokenPairOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authservice.CreateTokenPairInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_CreateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenPair'
type MockAuthUsecase_CreateTokenPair_Call struct {
	*mock.Call
}

// CreateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - input *authservice.CreateTokenPairInput
func (_e *MockAuthUsecase_Expecter) CreateTokenPair(ctx interface{}, input interface{}) *MockAuthUsecase_CreateTokenPair_Call {
	return &MockAuthUsecase_CreateTokenPair_Call{Call: _e.mock.On("CreateTokenPair", ctx, input)}
}

func (_c *MockAuthUsecase_CreateTokenPair_Call) Run(run func(ctx context.Context, input *authservice.CreateTokenPairInput)) *MockAuthUsecase_CreateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authservice.CreateTokenPairInput
		if args[1] != nil {
			arg1 = args[1].(*authservice.CreateTokenPairInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_CreateTokenPair_Call) Return(createTokenPairOutput *authservice.CreateTokenPairOutput, err error) *MockAuthUsecase_CreateTokenPair_Call {
	_c.Call.Return(createTokenPairOutput, err)
	return _c
}

func (_c *MockAuthUsecase_CreateTokenPair_Call) RunAndReturn(run func(ctx context.Context, input *authservice.CreateTokenPairInput) (*authservice.CreateTokenPairOutput, error)) *MockAuthUsecase_CreateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordAuthenticate provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) PasswordAuthenticate(ctx context.Context, input *authservice.PasswordAuthenticateInput) (*authservice.PasswordAuthenticateOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PasswordAuthenticate")
	}

	var r0 *authservice.PasswordAuthenticateOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.PasswordAuthenticateInput) (*authservice.PasswordAuthenticateOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.PasswordAuthenticateInput) *authservice.PasswordAuthenticateOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authservice.PasswordAuthenticateOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authservice.PasswordAuthenticateInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_PasswordAuthenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordAuthenticate'
type MockAuthUsecase_PasswordAuthenticate_Call struct {
	*mock.Call
}

// PasswordAuthenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - input *authservice.PasswordAuthenticateInput
func (_e *MockAuthUsecase_Expecter) PasswordAuthenticate(ctx interface{}, input interface{}) *MockAuthUsecase_PasswordAuthenticate_Call {
	return &MockAuthUsecase_PasswordAuthenticate_Call{Call: _e.mock.On("PasswordAuthenticate", ctx, input)}
}

func (_c *MockAuthUsecase_PasswordAuthenticate_Call) Run(run func(ctx context.Context, input *authservice.PasswordAuthenticateInput)) *MockAuthUsecase_PasswordAuthenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authservice.PasswordAuthenticateInput
		if args[1] != nil {
			arg1 = args[1].(*authservice.PasswordAuthenticateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_PasswordAuthenticate_Call) Return(output *authservice.PasswordAuthenticateOutput, err error) *MockAuthUsecase_PasswordAuthenticate_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockAuthUsecase_PasswordAuthenticate_Call) RunAndReturn(run func(ctx context.Context, input *authservice.PasswordAuthenticateInput) (*authservice.PasswordAuthenticateOutput, error)) *MockAuthUsecase_PasswordAuthenticate_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) RefreshAccessToken(ctx context.Context, input *authservice.RefreshAccessTokenInput) (*authservice.RefreshAccessTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 *authservice.RefreshAccessTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.RefreshAccessTokenInput) (*authservice.RefreshAccessTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.RefreshAccessTokenInput) *authservice.RefreshAccessTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authservice.RefreshAccessTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authservice.RefreshAccessTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockAuthUsecase_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *authservice.RefreshAccessTokenInput
func (_e *MockAuthUsecase_Expecter) RefreshAccessToken(ctx interface{}, input interface{}) *MockAuthUsecase_RefreshAccessToken_Call {
	return &MockAuthUsecase_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, input)}
}

func (_c *MockAuthUsecase_RefreshAccessToken_Call) Run(run func(ctx context.Context, input *authservice.RefreshAccessTokenInput)) *MockAuthUsecase_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authservice.RefreshAccessTokenInput
		if args[1] != nil {
			arg1 = args[1].(*authservice.RefreshAccessTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_RefreshAccessToken_Call) Return(output *authservice.RefreshAccessTokenOutput, err error) *MockAuthUsecase_RefreshAccessToken_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockAuthUsecase_RefreshAccessToken_Call) RunAndReturn(run func(ctx context.Context, input *authservice.RefreshAccessTokenInput) (*authservice.RefreshAccessTokenOutput, error)) *MockAuthUsecase_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSessionToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) RevokeSessionToken(ctx context.Context, input *authservice.RevokeSessionTokenInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.RevokeSessionTokenInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_RevokeSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSessionToken'
type MockAuthUsecase_RevokeSessionToken_Call struct {
	*mock.Call
}

// RevokeSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *authservice.RevokeSessionTokenInput
func (_e *MockAuthUsecase_Expecter) RevokeSessionToken(ctx interface{}, input interface{}) *MockAuthUsecase_RevokeSessionToken_Call {
	return &MockAuthUsecase_RevokeSessionToken_Call{Call: _e.mock.On("RevokeSessionToken", ctx, input)}
}

func (_c *MockAuthUsecase_RevokeSessionToken_Call) Run(run func(ctx context.Context, input *authservice.RevokeSessionTokenInput)) *MockAuthUsecase_RevokeSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authservice.RevokeSessionTokenInput
		if args[1] != nil {
			arg1 = args[1].(*authservice.RevokeSessionTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_RevokeSessionToken_Call) Return(err error) *MockAuthUsecase_RevokeSessionToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_RevokeSessionToken_Call) RunAndReturn(run func(ctx context.Context, input *authservice.RevokeSessionTokenInput) error) *MockAuthUsecase_RevokeSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) RevokeToken(ctx context.Context, input *authservice.RevokeTokenInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authservice.RevokeTokenInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUsecase_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockAuthUsecase_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *authservice.RevokeTokenInput
func (_e *MockAuthUsecase_Expecter) RevokeToken(ctx interface{}, input interface{}) *MockAuthUsecase_RevokeToken_Call {
	return &MockAuthUsecase_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, input)}
}

func (_c *MockAuthUsecase_RevokeToken_Call) Run(run func(ctx context.Context, input *authservice.RevokeTokenInput)) *MockAuthUsecase_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authservice.RevokeTokenInput
		if args[1] != nil {
			arg1 = args[1].(*authservice.RevokeTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_RevokeToken_Call) Return(err error) *MockAuthUsecase_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUsecase_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, input *authservice.RevokeTokenInput) error) *MockAuthUsecase_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}
