// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.26/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.26/cocotola-auth/service/auth"
	mock "github.com/stretchr/testify/mock"
)

// newMockuserSettingFinder creates a new instance of mockuserSettingFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserSettingFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserSettingFinder {
	mock := &mockuserSettingFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserSettingFinder is an autogenerated mock type for the userSettingFinder type
type mockuserSettingFinder struct {
	mock.Mock
}

type mockuserSettingFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserSettingFinder) EXPECT() *mockuserSettingFinder_Expecter {
	return &mockuserSettingFinder_Expecter{mock: &_m.Mock}
}

// FindByAppUserID provides a mock function for the type mockuserSettingFinder
func (_mock *mockuserSettingFinder) FindByAppUserID(ctx context.Context, appUserID domain.AppUserID) (*domain.UserSetting, error) {
	ret := _mock.Called(ctx, appUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAppUserID")
	}

	var r0 *domain.UserSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppUserID) (*domain.UserSetting, error)); ok {
		return returnFunc(ctx, appUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AppUserID) *domain.UserSetting); ok {
		r0 = returnFunc(ctx, appUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AppUserID) error); ok {
		r1 = returnFunc(ctx, appUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserSettingFinder_FindByAppUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAppUserID'
type mockuserSettingFinder_FindByAppUserID_Call struct {
	*mock.Call
}

// FindByAppUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - appUserID domain.AppUserID
func (_e *mockuserSettingFinder_Expecter) FindByAppUserID(ctx interface{}, appUserID interface{}) *mockuserSettingFinder_FindByAppUserID_Call {
	return &mockuserSettingFinder_FindByAppUserID_Call{Call: _e.mock.On("FindByAppUserID", ctx, appUserID)}
}

func (_c *mockuserSettingFinder_FindByAppUserID_Call) Run(run func(ctx context.Context, appUserID domain.AppUserID)) *mockuserSettingFinder_FindByAppUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AppUserID
		if args[1] != nil {
			arg1 = args[1].(domain.AppUserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserSettingFinder_FindByAppUserID_Call) Return(userSetting *domain.UserSetting, err error) *mockuserSettingFinder_FindByAppUserID_Call {
	_c.Call.Return(userSetting, err)
	return _c
}

func (_c *mockuserSettingFinder_FindByAppUserID_Call) RunAndReturn(run func(ctx context.Context, appUserID domain.AppUserID) (*domain.UserSetting, error)) *mockuserSettingFinder_FindByAppUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGuestAuthenticateUsecase creates a new instance of MockGuestAuthenticateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuestAuthenticateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuestAuthenticateUsecase {
	mock := &MockGuestAuthenticateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGuestAuthenticateUsecase is an autogenerated mock type for the GuestAuthenticateUsecase type
type MockGuestAuthenticateUsecase struct {
	mock.Mock
}

type MockGuestAuthenticateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuestAuthenticateUsecase) EXPECT() *MockGuestAuthenticateUsecase_Expecter {
	return &MockGuestAuthenticateUsecase_Expecter{mock: &_m.Mock}
}

// CreateTokenPair provides a mock function for the type MockGuestAuthenticateUsecase
func (_mock *MockGuestAuthenticateUsecase) CreateTokenPair(ctx context.Context, input *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenPair")
	}

	var r0 *auth.CreateTokenPairOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateTokenPairInput) *auth.CreateTokenPairOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CreateTokenPairOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.CreateTokenPairInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuestAuthenticateUsecase_CreateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenPair'
type MockGuestAuthenticateUsecase_CreateTokenPair_Call struct {
	*mock.Call
}

// CreateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.CreateTokenPairInput
func (_e *MockGuestAuthenticateUsecase_Expecter) CreateTokenPair(ctx interface{}, input interface{}) *MockGuestAuthenticateUsecase_CreateTokenPair_Call {
	return &MockGuestAuthenticateUsecase_CreateTokenPair_Call{Call: _e.mock.On("CreateTokenPair", ctx, input)}
}

func (_c *MockGuestAuthenticateUsecase_CreateTokenPair_Call) Run(run func(ctx context.Context, input *auth.CreateTokenPairInput)) *MockGuestAuthenticateUsecase_CreateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.CreateTokenPairInput
		if args[1] != nil {
			arg1 = args[1].(*auth.CreateTokenPairInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuestAuthenticateUsecase_CreateTokenPair_Call) Return(createTokenPairOutput *auth.CreateTokenPairOutput, err error) *MockGuestAuthenticateUsecase_CreateTokenPair_Call {
	_c.Call.Return(createTokenPairOutput, err)
	return _c
}

func (_c *MockGuestAuthenticateUsecase_CreateTokenPair_Call) RunAndReturn(run func(ctx context.Context, input *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error)) *MockGuestAuthenticateUsecase_CreateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// GuestAuthenticate provides a mock function for the type MockGuestAuthenticateUsecase
func (_mock *MockGuestAuthenticateUsecase) GuestAuthenticate(ctx context.Context, input *auth.GuestAuthenticateInput) (*auth.GuestAuthenticateOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GuestAuthenticate")
	}

	var r0 *auth.GuestAuthenticateOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.GuestAuthenticateInput) (*auth.GuestAuthenticateOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.GuestAuthenticateInput) *auth.GuestAuthenticateOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.GuestAuthenticateOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.GuestAuthenticateInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuestAuthenticateUsecase_GuestAuthenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuestAuthenticate'
type MockGuestAuthenticateUsecase_GuestAuthenticate_Call struct {
	*mock.Call
}

// GuestAuthenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.GuestAuthenticateInput
func (_e *MockGuestAuthenticateUsecase_Expecter) GuestAuthenticate(ctx interface{}, input interface{}) *MockGuestAuthenticateUsecase_GuestAuthenticate_Call {
	return &MockGuestAuthenticateUsecase_GuestAuthenticate_Call{Call: _e.mock.On("GuestAuthenticate", ctx, input)}
}

func (_c *MockGuestAuthenticateUsecase_GuestAuthenticate_Call) Run(run func(ctx context.Context, input *auth.GuestAuthenticateInput)) *MockGuestAuthenticateUsecase_GuestAuthenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.GuestAuthenticateInput
		if args[1] != nil {
			arg1 = args[1].(*auth.GuestAuthenticateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuestAuthenticateUsecase_GuestAuthenticate_Call) Return(guestAuthenticateOutput *auth.GuestAuthenticateOutput, err error) *MockGuestAuthenticateUsecase_GuestAuthenticate_Call {
	_c.Call.Return(guestAuthenticateOutput, err)
	return _c
}

func (_c *MockGuestAuthenticateUsecase_GuestAuthenticate_Call) RunAndReturn(run func(ctx context.Context, input *auth.GuestAuthenticateInput) (*auth.GuestAuthenticateOutput, error)) *MockGuestAuthenticateUsecase_GuestAuthenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordAuthenticateUsecase creates a new instance of MockPasswordAuthenticateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordAuthenticateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordAuthenticateUsecase {
	mock := &MockPasswordAuthenticateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordAuthenticateUsecase is an autogenerated mock type for the PasswordAuthenticateUsecase type
type MockPasswordAuthenticateUsecase struct {
	mock.Mock
}

type MockPasswordAuthenticateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordAuthenticateUsecase) EXPECT() *MockPasswordAuthenticateUsecase_Expecter {
	return &MockPasswordAuthenticateUsecase_Expecter{mock: &_m.Mock}
}

// CreateSessionToken provides a mock function for the type MockPasswordAuthenticateUsecase
func (_mock *MockPasswordAuthenticateUsecase) CreateSessionToken(ctx context.Context, input *auth.CreateSessionTokenInput) (*auth.CreateSessionTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionToken")
	}

	var r0 *auth.CreateSessionTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateSessionTokenInput) (*auth.CreateSessionTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateSessionTokenInput) *auth.CreateSessionTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CreateSessionTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.CreateSessionTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordAuthenticateUsecase_CreateSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionToken'
type MockPasswordAuthenticateUsecase_CreateSessionToken_Call struct {
	*mock.Call
}

// CreateSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.CreateSessionTokenInput
func (_e *MockPasswordAuthenticateUsecase_Expecter) CreateSessionToken(ctx interface{}, input interface{}) *MockPasswordAuthenticateUsecase_CreateSessionToken_Call {
	return &MockPasswordAuthenticateUsecase_CreateSessionToken_Call{Call: _e.mock.On("CreateSessionToken", ctx, input)}
}

func (_c *MockPasswordAuthenticateUsecase_CreateSessionToken_Call) Run(run func(ctx context.Context, input *auth.CreateSessionTokenInput)) *MockPasswordAuthenticateUsecase_CreateSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.CreateSessionTokenInput
		if args[1] != nil {
			arg1 = args[1].(*auth.CreateSessionTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordAuthenticateUsecase_CreateSessionToken_Call) Return(createSessionTokenOutput *auth.CreateSessionTokenOutput, err error) *MockPasswordAuthenticateUsecase_CreateSessionToken_Call {
	_c.Call.Return(createSessionTokenOutput, err)
	return _c
}

func (_c *MockPasswordAuthenticateUsecase_CreateSessionToken_Call) RunAndReturn(run func(ctx context.Context, input *auth.CreateSessionTokenInput) (*auth.CreateSessionTokenOutput, error)) *MockPasswordAuthenticateUsecase_CreateSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTokenPair provides a mock function for the type MockPasswordAuthenticateUsecase
func (_mock *MockPasswordAuthenticateUsecase) CreateTokenPair(ctx context.Context, input *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenPair")
	}

	var r0 *auth.CreateTokenPairOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateTokenPairInput) *auth.CreateTokenPairOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CreateTokenPairOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.CreateTokenPairInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordAuthenticateUsecase_CreateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenPair'
type MockPasswordAuthenticateUsecase_CreateTokenPair_Call struct {
	*mock.Call
}

// CreateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.CreateTokenPairInput
func (_e *MockPasswordAuthenticateUsecase_Expecter) CreateTokenPair(ctx interface{}, input interface{}) *MockPasswordAuthenticateUsecase_CreateTokenPair_Call {
	return &MockPasswordAuthenticateUsecase_CreateTokenPair_Call{Call: _e.mock.On("CreateTokenPair", ctx, input)}
}

func (_c *MockPasswordAuthenticateUsecase_CreateTokenPair_Call) Run(run func(ctx context.Context, input *auth.CreateTokenPairInput)) *MockPasswordAuthenticateUsecase_CreateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.CreateTokenPairInput
		if args[1] != nil {
			arg1 = args[1].(*auth.CreateTokenPairInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordAuthenticateUsecase_CreateTokenPair_Call) Return(createTokenPairOutput *auth.CreateTokenPairOutput, err error) *MockPasswordAuthenticateUsecase_CreateTokenPair_Call {
	_c.Call.Return(createTokenPairOutput, err)
	return _c
}

func (_c *MockPasswordAuthenticateUsecase_CreateTokenPair_Call) RunAndReturn(run func(ctx context.Context, input *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error)) *MockPasswordAuthenticateUsecase_CreateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordAuthenticate provides a mock function for the type MockPasswordAuthenticateUsecase
func (_mock *MockPasswordAuthenticateUsecase) PasswordAuthenticate(ctx context.Context, input *auth.PasswordAuthenticateInput) (*auth.PasswordAuthenticateOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PasswordAuthenticate")
	}

	var r0 *auth.PasswordAuthenticateOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.PasswordAuthenticateInput) (*auth.PasswordAuthenticateOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.PasswordAuthenticateInput) *auth.PasswordAuthenticateOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.PasswordAuthenticateOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.PasswordAuthenticateInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordAuthenticate'
type MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call struct {
	*mock.Call
}

// PasswordAuthenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.PasswordAuthenticateInput
func (_e *MockPasswordAuthenticateUsecase_Expecter) PasswordAuthenticate(ctx interface{}, input interface{}) *MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call {
	return &MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call{Call: _e.mock.On("PasswordAuthenticate", ctx, input)}
}

func (_c *MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call) Run(run func(ctx context.Context, input *auth.PasswordAuthenticateInput)) *MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.PasswordAuthenticateInput
		if args[1] != nil {
			arg1 = args[1].(*auth.PasswordAuthenticateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call) Return(passwordAuthenticateOutput *auth.PasswordAuthenticateOutput, err error) *MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call {
	_c.Call.Return(passwordAuthenticateOutput, err)
	return _c
}

func (_c *MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call) RunAndReturn(run func(ctx context.Context, input *auth.PasswordAuthenticateInput) (*auth.PasswordAuthenticateOutput, error)) *MockPasswordAuthenticateUsecase_PasswordAuthenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRevokeUsecase creates a new instance of MockRevokeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevokeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevokeUsecase {
	mock := &MockRevokeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRevokeUsecase is an autogenerated mock type for the RevokeUsecase type
type MockRevokeUsecase struct {
	mock.Mock
}

type MockRevokeUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevokeUsecase) EXPECT() *MockRevokeUsecase_Expecter {
	return &MockRevokeUsecase_Expecter{mock: &_m.Mock}
}

// RevokeSessionToken provides a mock function for the type MockRevokeUsecase
func (_mock *MockRevokeUsecase) RevokeSessionToken(ctx context.Context, input *auth.RevokeSessionTokenInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RevokeSessionTokenInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRevokeUsecase_RevokeSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSessionToken'
type MockRevokeUsecase_RevokeSessionToken_Call struct {
	*mock.Call
}

// RevokeSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.RevokeSessionTokenInput
func (_e *MockRevokeUsecase_Expecter) RevokeSessionToken(ctx interface{}, input interface{}) *MockRevokeUsecase_RevokeSessionToken_Call {
	return &MockRevokeUsecase_RevokeSessionToken_Call{Call: _e.mock.On("RevokeSessionToken", ctx, input)}
}

func (_c *MockRevokeUsecase_RevokeSessionToken_Call) Run(run func(ctx context.Context, input *auth.RevokeSessionTokenInput)) *MockRevokeUsecase_RevokeSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.RevokeSessionTokenInput
		if args[1] != nil {
			arg1 = args[1].(*auth.RevokeSessionTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRevokeUsecase_RevokeSessionToken_Call) Return(err error) *MockRevokeUsecase_RevokeSessionToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRevokeUsecase_RevokeSessionToken_Call) RunAndReturn(run func(ctx context.Context, input *auth.RevokeSessionTokenInput) error) *MockRevokeUsecase_RevokeSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockRevokeUsecase
func (_mock *MockRevokeUsecase) RevokeToken(ctx context.Context, input *auth.RevokeTokenInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RevokeTokenInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRevokeUsecase_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockRevokeUsecase_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.RevokeTokenInput
func (_e *MockRevokeUsecase_Expecter) RevokeToken(ctx interface{}, input interface{}) *MockRevokeUsecase_RevokeToken_Call {
	return &MockRevokeUsecase_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, input)}
}

func (_c *MockRevokeUsecase_RevokeToken_Call) Run(run func(ctx context.Context, input *auth.RevokeTokenInput)) *MockRevokeUsecase_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.RevokeTokenInput
		if args[1] != nil {
			arg1 = args[1].(*auth.RevokeTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRevokeUsecase_RevokeToken_Call) Return(err error) *MockRevokeUsecase_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRevokeUsecase_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, input *auth.RevokeTokenInput) error) *MockRevokeUsecase_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupabaseExchangeUsecase creates a new instance of MockSupabaseExchangeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupabaseExchangeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupabaseExchangeUsecase {
	mock := &MockSupabaseExchangeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSupabaseExchangeUsecase is an autogenerated mock type for the SupabaseExchangeUsecase type
type MockSupabaseExchangeUsecase struct {
	mock.Mock
}

type MockSupabaseExchangeUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupabaseExchangeUsecase) EXPECT() *MockSupabaseExchangeUsecase_Expecter {
	return &MockSupabaseExchangeUsecase_Expecter{mock: &_m.Mock}
}

// CreateTokenPair provides a mock function for the type MockSupabaseExchangeUsecase
func (_mock *MockSupabaseExchangeUsecase) CreateTokenPair(ctx context.Context, input *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenPair")
	}

	var r0 *auth.CreateTokenPairOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.CreateTokenPairInput) *auth.CreateTokenPairOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CreateTokenPairOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.CreateTokenPairInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSupabaseExchangeUsecase_CreateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenPair'
type MockSupabaseExchangeUsecase_CreateTokenPair_Call struct {
	*mock.Call
}

// CreateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.CreateTokenPairInput
func (_e *MockSupabaseExchangeUsecase_Expecter) CreateTokenPair(ctx interface{}, input interface{}) *MockSupabaseExchangeUsecase_CreateTokenPair_Call {
	return &MockSupabaseExchangeUsecase_CreateTokenPair_Call{Call: _e.mock.On("CreateTokenPair", ctx, input)}
}

func (_c *MockSupabaseExchangeUsecase_CreateTokenPair_Call) Run(run func(ctx context.Context, input *auth.CreateTokenPairInput)) *MockSupabaseExchangeUsecase_CreateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.CreateTokenPairInput
		if args[1] != nil {
			arg1 = args[1].(*auth.CreateTokenPairInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSupabaseExchangeUsecase_CreateTokenPair_Call) Return(createTokenPairOutput *auth.CreateTokenPairOutput, err error) *MockSupabaseExchangeUsecase_CreateTokenPair_Call {
	_c.Call.Return(createTokenPairOutput, err)
	return _c
}

func (_c *MockSupabaseExchangeUsecase_CreateTokenPair_Call) RunAndReturn(run func(ctx context.Context, input *auth.CreateTokenPairInput) (*auth.CreateTokenPairOutput, error)) *MockSupabaseExchangeUsecase_CreateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// SupabaseExchange provides a mock function for the type MockSupabaseExchangeUsecase
func (_mock *MockSupabaseExchangeUsecase) SupabaseExchange(ctx context.Context, input *auth.SupabaseExchangeInput) (*auth.SupabaseExchangeOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SupabaseExchange")
	}

	var r0 *auth.SupabaseExchangeOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SupabaseExchangeInput) (*auth.SupabaseExchangeOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.SupabaseExchangeInput) *auth.SupabaseExchangeOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.SupabaseExchangeOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.SupabaseExchangeInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSupabaseExchangeUsecase_SupabaseExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupabaseExchange'
type MockSupabaseExchangeUsecase_SupabaseExchange_Call struct {
	*mock.Call
}

// SupabaseExchange is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.SupabaseExchangeInput
func (_e *MockSupabaseExchangeUsecase_Expecter) SupabaseExchange(ctx interface{}, input interface{}) *MockSupabaseExchangeUsecase_SupabaseExchange_Call {
	return &MockSupabaseExchangeUsecase_SupabaseExchange_Call{Call: _e.mock.On("SupabaseExchange", ctx, input)}
}

func (_c *MockSupabaseExchangeUsecase_SupabaseExchange_Call) Run(run func(ctx context.Context, input *auth.SupabaseExchangeInput)) *MockSupabaseExchangeUsecase_SupabaseExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.SupabaseExchangeInput
		if args[1] != nil {
			arg1 = args[1].(*auth.SupabaseExchangeInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSupabaseExchangeUsecase_SupabaseExchange_Call) Return(supabaseExchangeOutput *auth.SupabaseExchangeOutput, err error) *MockSupabaseExchangeUsecase_SupabaseExchange_Call {
	_c.Call.Return(supabaseExchangeOutput, err)
	return _c
}

func (_c *MockSupabaseExchangeUsecase_SupabaseExchange_Call) RunAndReturn(run func(ctx context.Context, input *auth.SupabaseExchangeInput) (*auth.SupabaseExchangeOutput, error)) *MockSupabaseExchangeUsecase_SupabaseExchange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshUsecase creates a new instance of MockRefreshUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshUsecase {
	mock := &MockRefreshUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshUsecase is an autogenerated mock type for the RefreshUsecase type
type MockRefreshUsecase struct {
	mock.Mock
}

type MockRefreshUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshUsecase) EXPECT() *MockRefreshUsecase_Expecter {
	return &MockRefreshUsecase_Expecter{mock: &_m.Mock}
}

// RefreshAccessToken provides a mock function for the type MockRefreshUsecase
func (_mock *MockRefreshUsecase) RefreshAccessToken(ctx context.Context, input *auth.RefreshAccessTokenInput) (*auth.RefreshAccessTokenOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 *auth.RefreshAccessTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RefreshAccessTokenInput) (*auth.RefreshAccessTokenOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RefreshAccessTokenInput) *auth.RefreshAccessTokenOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshAccessTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.RefreshAccessTokenInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshUsecase_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockRefreshUsecase_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input *auth.RefreshAccessTokenInput
func (_e *MockRefreshUsecase_Expecter) RefreshAccessToken(ctx interface{}, input interface{}) *MockRefreshUsecase_RefreshAccessToken_Call {
	return &MockRefreshUsecase_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, input)}
}

func (_c *MockRefreshUsecase_RefreshAccessToken_Call) Run(run func(ctx context.Context, input *auth.RefreshAccessTokenInput)) *MockRefreshUsecase_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.RefreshAccessTokenInput
		if args[1] != nil {
			arg1 = args[1].(*auth.RefreshAccessTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshUsecase_RefreshAccessToken_Call) Return(refreshAccessTokenOutput *auth.RefreshAccessTokenOutput, err error) *MockRefreshUsecase_RefreshAccessToken_Call {
	_c.Call.Return(refreshAccessTokenOutput, err)
	return _c
}

func (_c *MockRefreshUsecase_RefreshAccessToken_Call) RunAndReturn(run func(ctx context.Context, input *auth.RefreshAccessTokenInput) (*auth.RefreshAccessTokenOutput, error)) *MockRefreshUsecase_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
