---
server:
  httpPort: ${HTTP_PORT:-8080}
  metricsPort: ${METRICS_PORT:-8081}
  readHeaderTimeoutSec: ${READ_HEADER_TIMEOUT_SEC:-30}
  cors:
    allowOrigins: ${CORS_ALLOW_ORIGINS:-'*'}
    allowMethods: ${CORS_ALLOW_METHODS:-'GET,POST,PUT,DELETE,OPTIONS'}
    allowHeaders: ${CORS_ALLOW_HEADERS:-'Content-Type,Authorization,X-Token-Delivery'}
    allowCredentials: ${CORS_ALLOW_CREDENTIALS:-false}
  log:
    accessLog: ${GIN_LOG_ACCESS_LOG:-true}
    accessLogRequestBody: ${GIN_LOG_ACCESS_LOG_REQUEST_BODY:-false}
    accessLogResponseBody: ${GIN_LOG_ACCESS_LOG_RESPONSE_BODY:-false}
  debug:
    gin: ${GIN_DEBUG_GIN:-false}
    wait: ${GIN_DEBUG_WAIT:-false}
  shutdown:
    gracePeriodSec: ${SHUTDOWN_GRACE_PERIOD_SEC:-1}
    shutdownTimeSec: ${SHUTDOWN_TIME_SEC:-1}
db:
  driverName: ${APP_DB_DRIVER_NAME:-mysql}
  mysql:
    username: ${AUTH_MYSQL_USERNAME}
    password: ${AUTH_MYSQL_PASSWORD}
    host: ${AUTH_MYSQL_HOST:-127.0.0.1}
    port: ${AUTH_MYSQL_PORT:-3306}
    database: ${AUTH_MYSQL_DATABASE:-local}
trace:
  exporter: ${TRACE_EXPORTER:-none}
  otlp:
    endpoint: ${TRACE_OTLP_ENDPOINT:-localhost:4317}
    insecure: ${TRACE_OTLP_INSECURE:-true}
  uptrace:
log:
  level: ${LOG_LEVEL:-info}
  exporter: ${LOG_EXPORTER:-none}
  otlp:
    endpoint: ${LOG_OTLP_ENDPOINT:-localhost:4318}
    insecure: ${LOG_OTLP_INSECURE:-true}
  uptrace:
    endpoint: ${LOG_UPTRACE_ENDPOINT:-api.uptrace.dev}
    dsn: ${LOG_UPTRACE_DSN:-dummy}
auth:
  signingKey: ${AUTH_SIGNING_KEY}
  accessTokenTtlMin: ${AUTH_ACCESS_TOKEN_TTL_MIN:-60}
  refreshTokenTtlMin: ${AUTH_REFRESH_TOKEN_TTL_MIN:-43200}
  sessionTokenTtlMin: ${AUTH_SESSION_TOKEN_TTL_MIN:-30}
  sessionMaxTtlMin: ${AUTH_SESSION_MAX_TTL_MIN:-1440}
  tokenWhitelistSize: ${AUTH_TOKEN_WHITELIST_SIZE:-10}
  cookie:
    name: session_token
    path: ${AUTH_COOKIE_PATH:-/}
    secure: ${AUTH_COOKIE_SECURE:-true}
    sameSite: ${AUTH_COOKIE_SAME_SITE:-Lax}
