---
server:
  httpPort: ${AUTH_HTTP_PORT:-8080}
  metricsPort: ${AUTH_METRICS_PORT:-8081}
  readHeaderTimeoutSec: ${AUTH_READ_HEADER_TIMEOUT_SEC:-30}
  cors:
    allowOrigins: ${AUTH_CORS_ALLOW_ORIGINS:-'*'}
    allowMethods: ${AUTH_CORS_ALLOW_METHODS:-'GET,POST,PUT,DELETE,OPTIONS'}
    allowHeaders: ${AUTH_CORS_ALLOW_HEADERS:-'Content-Type,Authorization,X-Token-Delivery,X-Service-Api-Key'}
    allowCredentials: ${AUTH_CORS_ALLOW_CREDENTIALS:-false}
  log:
    accessLog: ${GIN_LOG_ACCESS_LOG:-true}
    accessLogRequestBody: ${GIN_LOG_ACCESS_LOG_REQUEST_BODY:-false}
    accessLogResponseBody: ${GIN_LOG_ACCESS_LOG_RESPONSE_BODY:-false}
  debug:
    gin: ${GIN_DEBUG_GIN:-false}
    wait: ${GIN_DEBUG_WAIT:-false}
  shutdown:
    gracePeriodSec: ${AUTH_SHUTDOWN_GRACE_PERIOD_SEC:-5}
    shutdownTimeSec: ${AUTH_SHUTDOWN_TIME_SEC:-1}
db:
  driverName: ${AUTH_DB_DRIVER_NAME:-postgres}
  postgres:
    username: ${AUTH_POSTGRES_USERNAME}
    password: ${AUTH_POSTGRES_PASSWORD}
    host: ${AUTH_POSTGRES_HOST:-127.0.0.1}
    port: ${AUTH_POSTGRES_PORT:-5432}
    database: ${AUTH_POSTGRES_DATABASE:-local}
    sslMode: ${AUTH_POSTGRES_SSL_MODE:-disable}
    params:
      default_query_exec_mode: ${AUTH_POSTGRES_DEFAULT_QUERY_EXEC_MODE:-}
trace:
  exporter: ${TRACE_EXPORTER:-none}
  otlp:
    endpoint: ${TRACE_OTLP_ENDPOINT:-localhost:4317}
    insecure: ${TRACE_OTLP_INSECURE:-true}
  google:
    projectId: ${TRACE_GOOGLE_PROJECT_ID:-}
  uptrace:
    endpoint: ${LOG_UPTRACE_ENDPOINT:-api.uptrace.dev}
    dsn: ${LOG_UPTRACE_DSN:-dummy}
log:
  level: ${AUTH_LOG_LEVEL:-info}
  exporter: ${LOG_EXPORTER:-none}
  otlp:
    endpoint: ${LOG_OTLP_ENDPOINT:-localhost:4318}
    insecure: ${LOG_OTLP_INSECURE:-true}
  uptrace:
    endpoint: ${LOG_UPTRACE_ENDPOINT:-api.uptrace.dev}
    dsn: ${LOG_UPTRACE_DSN:-dummy}
auth:
  signingKey: ${AUTH_SIGNING_KEY}
  accessTokenTtlMin: ${AUTH_ACCESS_TOKEN_TTL_MIN:-60}
  refreshTokenTtlMin: ${AUTH_REFRESH_TOKEN_TTL_MIN:-43200}
  sessionTokenTtlMin: ${AUTH_SESSION_TOKEN_TTL_MIN:-30}
  sessionMaxTtlMin: ${AUTH_SESSION_MAX_TTL_MIN:-1440}
  tokenWhitelistSize: ${AUTH_TOKEN_WHITELIST_SIZE:-10}
  cookie:
    name: session_token
    path: ${AUTH_COOKIE_PATH:-/}
    secure: ${AUTH_COOKIE_SECURE:-true}
    sameSite: ${AUTH_COOKIE_SAME_SITE:-Lax}
  supabase:
    jwksUrl: ${AUTH_SUPABASE_JWKS_URL}
  apiKey: ${AUTH_API_KEY}
