# syntax=docker/dockerfile:1.7
FROM golang:1.26 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go mod download
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/cocotola-audio-generator ./

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/cocotola-audio-generator /usr/local/bin/cocotola-audio-generator
USER nonroot
ENTRYPOINT ["/usr/local/bin/cocotola-audio-generator"]
