---
openapi: 3.0.1
info:
  title: cocotola-auth
  description: cocotola-auth
  version: '1.0'
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Support
    url: http://www.swagger.io/support
    email: support@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: auth
  - name: group
  - name: space
  - name: user
paths:
  /api/v1/auth/password/authenticate:
    $ref: 'paths/auth.yaml#/password-authenticate'
  /api/v1/auth/guest/authenticate:
    $ref: 'paths/auth.yaml#/guest-authenticate'
  /api/v1/auth/logout:
    $ref: 'paths/auth.yaml#/logout'
  /api/v1/auth/refresh:
    $ref: 'paths/auth.yaml#/refresh'
  /api/v1/auth/revoke:
    $ref: 'paths/auth.yaml#/revoke'
  /api/v1/auth/me:
    $ref: 'paths/auth.yaml#/me'
  /api/v1/group:
    $ref: 'paths/group.yaml#/group'
  /api/v1/space:
    $ref: 'paths/space.yaml#/space'
  /api/v1/user:
    $ref: 'paths/user.yaml#/user'
components:
  schemas:
    PasswordAuthRequest:
      $ref: 'schemas/auth.yaml#/PasswordAuthRequest'
    GuestAuthRequest:
      $ref: 'schemas/auth.yaml#/GuestAuthRequest'
    AuthenticateResponse:
      $ref: 'schemas/auth.yaml#/AuthenticateResponse'
    RefreshRequest:
      $ref: 'schemas/auth.yaml#/RefreshRequest'
    RefreshResponse:
      $ref: 'schemas/auth.yaml#/RefreshResponse'
    RevokeRequest:
      $ref: 'schemas/auth.yaml#/RevokeRequest'
    GetMeResponse:
      $ref: 'schemas/auth.yaml#/GetMeResponse'
    CreateGroupRequest:
      $ref: 'schemas/group.yaml#/CreateGroupRequest'
    CreateGroupResponse:
      $ref: 'schemas/group.yaml#/CreateGroupResponse'
    CreateSpaceRequest:
      $ref: 'schemas/space.yaml#/CreateSpaceRequest'
    CreateSpaceResponse:
      $ref: 'schemas/space.yaml#/CreateSpaceResponse'
    SpaceItem:
      $ref: 'schemas/space.yaml#/SpaceItem'
    ListSpacesResponse:
      $ref: 'schemas/space.yaml#/ListSpacesResponse'
    CreateUserRequest:
      $ref: 'schemas/user.yaml#/CreateUserRequest'
    CreateUserResponse:
      $ref: 'schemas/user.yaml#/CreateUserResponse'
    ErrorResponse:
      $ref: 'schemas/common.yaml#/ErrorResponse'
  responses: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: session_token
servers: []
security:
  - BearerAuth: []
  - CookieAuth: []
