// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for PasswordAuthenticationParamsXTokenDelivery.
const (
	Cookie PasswordAuthenticationParamsXTokenDelivery = "cookie"
	Json   PasswordAuthenticationParamsXTokenDelivery = "json"
)

// AuthenticateResponse Authentication response. When X-Token-Delivery is 'json' (default), accessToken and refreshToken are returned in the body. When 'cookie', the session token is delivered via Set-Cookie header and tokens are omitted.
type AuthenticateResponse struct {
	// AccessToken JWT access token (omitted when delivered via cookie)
	AccessToken *string `json:"accessToken,omitempty"`

	// RefreshToken Opaque refresh token (omitted when delivered via cookie)
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Name string `binding:"required,max=255" json:"name"`
}

// CreateGroupResponse defines model for CreateGroupResponse.
type CreateGroupResponse struct {
	Enabled        bool   `json:"enabled"`
	GroupID        int32  `json:"groupId"`
	Name           string `json:"name"`
	OrganizationID int32  `json:"organizationId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetMeResponse defines model for GetMeResponse.
type GetMeResponse struct {
	LoginID          string `json:"loginId"`
	OrganizationName string `json:"organizationName"`
	UserID           int32  `json:"userId"`
}

// GuestAuthRequest defines model for GuestAuthRequest.
type GuestAuthRequest struct {
	OrganizationName string `binding:"required,max=20" json:"organizationName"`
}

// PasswordAuthRequest defines model for PasswordAuthRequest.
type PasswordAuthRequest struct {
	LoginID          string `binding:"required,max=100" json:"loginId"`
	OrganizationName string `binding:"required,max=20" json:"organizationName"`
	Password         string `binding:"required,min=8,max=20" json:"password"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `binding:"required" json:"refreshToken"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	// AccessToken New JWT access token
	AccessToken string `json:"accessToken"`
}

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	// Token The token to revoke (JWT access token or opaque refresh token)
	Token string `binding:"required" json:"token"`
}

// PasswordAuthenticationParams defines parameters for PasswordAuthentication.
type PasswordAuthenticationParams struct {
	// XTokenDelivery Token delivery method (json or cookie)
	XTokenDelivery *PasswordAuthenticationParamsXTokenDelivery `json:"X-Token-Delivery,omitempty"`
}

// PasswordAuthenticationParamsXTokenDelivery defines parameters for PasswordAuthentication.
type PasswordAuthenticationParamsXTokenDelivery string

// GuestAuthenticationJSONRequestBody defines body for GuestAuthentication for application/json ContentType.
type GuestAuthenticationJSONRequestBody = GuestAuthRequest

// PasswordAuthenticationJSONRequestBody defines body for PasswordAuthentication for application/json ContentType.
type PasswordAuthenticationJSONRequestBody = PasswordAuthRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RevokeTokenJSONRequestBody defines body for RevokeToken for application/json ContentType.
type RevokeTokenJSONRequestBody = RevokeRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest
