// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyScopes     = "ApiKey.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for CreateSpaceRequestSpaceType.
const (
	CreateSpaceRequestSpaceTypePrivate CreateSpaceRequestSpaceType = "private"
	CreateSpaceRequestSpaceTypePublic  CreateSpaceRequestSpaceType = "public"
)

// Defines values for CreateSpaceResponseSpaceType.
const (
	CreateSpaceResponseSpaceTypePrivate CreateSpaceResponseSpaceType = "private"
	CreateSpaceResponseSpaceTypePublic  CreateSpaceResponseSpaceType = "public"
)

// Defines values for FindSpaceResponseSpaceType.
const (
	FindSpaceResponseSpaceTypePrivate FindSpaceResponseSpaceType = "private"
	FindSpaceResponseSpaceTypePublic  FindSpaceResponseSpaceType = "public"
)

// Defines values for SpaceItemSpaceType.
const (
	SpaceItemSpaceTypePrivate SpaceItemSpaceType = "private"
	SpaceItemSpaceTypePublic  SpaceItemSpaceType = "public"
)

// Defines values for PasswordAuthenticationParamsXTokenDelivery.
const (
	Cookie PasswordAuthenticationParamsXTokenDelivery = "cookie"
	Json   PasswordAuthenticationParamsXTokenDelivery = "json"
)

// AuthenticateResponse Authentication response. When X-Token-Delivery is 'json' (default), accessToken and refreshToken are returned in the body. When 'cookie', the session token is delivered via Set-Cookie header and tokens are omitted.
type AuthenticateResponse struct {
	// AccessToken JWT access token (omitted when delivered via cookie)
	AccessToken *string `json:"accessToken,omitempty"`

	// RefreshToken Opaque refresh token (omitted when delivered via cookie)
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// AuthzCheckResponse defines model for AuthzCheckResponse.
type AuthzCheckResponse struct {
	Allowed bool `json:"allowed"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Name string `binding:"required,max=255" json:"name"`
}

// CreateGroupResponse defines model for CreateGroupResponse.
type CreateGroupResponse struct {
	Enabled        bool               `json:"enabled"`
	GroupID        openapi_types.UUID `json:"groupId"`
	Name           string             `json:"name"`
	OrganizationID openapi_types.UUID `json:"organizationId"`
}

// CreateSpaceRequest defines model for CreateSpaceRequest.
type CreateSpaceRequest struct {
	Name      string                      `binding:"required,max=100" json:"name"`
	SpaceType CreateSpaceRequestSpaceType `binding:"required,oneof=public private" json:"spaceType"`
}

// CreateSpaceRequestSpaceType defines model for CreateSpaceRequest.SpaceType.
type CreateSpaceRequestSpaceType string

// CreateSpaceResponse defines model for CreateSpaceResponse.
type CreateSpaceResponse struct {
	Deleted        bool                         `json:"deleted"`
	KeyName        string                       `json:"keyName"`
	Name           string                       `json:"name"`
	OrganizationID openapi_types.UUID           `json:"organizationId"`
	OwnerID        openapi_types.UUID           `json:"ownerId"`
	SpaceID        openapi_types.UUID           `json:"spaceId"`
	SpaceType      CreateSpaceResponseSpaceType `json:"spaceType"`
}

// CreateSpaceResponseSpaceType defines model for CreateSpaceResponse.SpaceType.
type CreateSpaceResponseSpaceType string

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	LoginId  string `binding:"required,max=255" json:"loginId"`
	Password string `binding:"required,min=8" json:"password"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	AppUserID      openapi_types.UUID `json:"appUserId"`
	Enabled        bool               `json:"enabled"`
	LoginID        string             `json:"loginId"`
	OrganizationID openapi_types.UUID `json:"organizationId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FindOrganizationResponse defines model for FindOrganizationResponse.
type FindOrganizationResponse struct {
	ID   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// FindSpaceResponse defines model for FindSpaceResponse.
type FindSpaceResponse struct {
	Deleted        bool                       `json:"deleted"`
	KeyName        string                     `json:"keyName"`
	Name           string                     `json:"name"`
	OrganizationID openapi_types.UUID         `json:"organizationId"`
	OwnerID        openapi_types.UUID         `json:"ownerId"`
	SpaceID        openapi_types.UUID         `json:"spaceId"`
	SpaceType      FindSpaceResponseSpaceType `json:"spaceType"`
}

// FindSpaceResponseSpaceType defines model for FindSpaceResponse.SpaceType.
type FindSpaceResponseSpaceType string

// GetMeResponse defines model for GetMeResponse.
type GetMeResponse struct {
	LoginID          string             `json:"loginId"`
	OrganizationName string             `json:"organizationName"`
	UserID           openapi_types.UUID `json:"userId"`
}

// GuestAuthRequest defines model for GuestAuthRequest.
type GuestAuthRequest struct {
	OrganizationName string `binding:"required,max=20" json:"organizationName"`
}

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse struct {
	Status string `json:"status"`
}

// ListSpacesResponse defines model for ListSpacesResponse.
type ListSpacesResponse struct {
	Spaces []SpaceItem `json:"spaces"`
}

// PasswordAuthRequest defines model for PasswordAuthRequest.
type PasswordAuthRequest struct {
	LoginID          string `binding:"required,max=100" json:"loginId"`
	OrganizationName string `binding:"required,max=20" json:"organizationName"`
	Password         string `binding:"required,min=8,max=20" json:"password"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `binding:"required" json:"refreshToken"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	// AccessToken New JWT access token
	AccessToken string `json:"accessToken"`
}

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	// Token The token to revoke (JWT access token or opaque refresh token)
	Token string `binding:"required" json:"token"`
}

// SpaceItem defines model for SpaceItem.
type SpaceItem struct {
	Deleted        bool               `json:"deleted"`
	KeyName        string             `json:"keyName"`
	Name           string             `json:"name"`
	OrganizationID openapi_types.UUID `json:"organizationId"`
	OwnerID        openapi_types.UUID `json:"ownerId"`
	SpaceID        openapi_types.UUID `json:"spaceId"`
	SpaceType      SpaceItemSpaceType `json:"spaceType"`
}

// SpaceItemSpaceType defines model for SpaceItem.SpaceType.
type SpaceItemSpaceType string

// SupabaseExchangeRequest defines model for SupabaseExchangeRequest.
type SupabaseExchangeRequest struct {
	OrganizationName string `binding:"required,max=20" json:"organizationName"`
	SupabaseJWT      string `binding:"required" json:"supabaseJwt"`
}

// CheckAuthorizationParams defines parameters for CheckAuthorization.
type CheckAuthorizationParams struct {
	// Org Organization ID
	Org int `form:"org" json:"org"`

	// User User ID
	User int `form:"user" json:"user"`

	// Action Action to check (e.g. create_workbook, view_workbook)
	Action string `form:"action" json:"action"`

	// Resource Resource to check (e.g. *, workbook:123)
	Resource string `form:"resource" json:"resource"`
}

// FindOrganizationParams defines parameters for FindOrganization.
type FindOrganizationParams struct {
	// Name Organization name to look up
	Name string `form:"name" json:"name"`
}

// PasswordAuthenticationParams defines parameters for PasswordAuthentication.
type PasswordAuthenticationParams struct {
	// XTokenDelivery Token delivery method (json or cookie)
	XTokenDelivery *PasswordAuthenticationParamsXTokenDelivery `json:"X-Token-Delivery,omitempty"`
}

// PasswordAuthenticationParamsXTokenDelivery defines parameters for PasswordAuthentication.
type PasswordAuthenticationParamsXTokenDelivery string

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// GuestAuthenticationJSONRequestBody defines body for GuestAuthentication for application/json ContentType.
type GuestAuthenticationJSONRequestBody = GuestAuthRequest

// PasswordAuthenticationJSONRequestBody defines body for PasswordAuthentication for application/json ContentType.
type PasswordAuthenticationJSONRequestBody = PasswordAuthRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RevokeTokenJSONRequestBody defines body for RevokeToken for application/json ContentType.
type RevokeTokenJSONRequestBody = RevokeRequest

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// SupabaseExchangeJSONRequestBody defines body for SupabaseExchange for application/json ContentType.
type SupabaseExchangeJSONRequestBody = SupabaseExchangeRequest
